### ISSUE TITLE
Change "needs alias" so that it applies only to current namespace.

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#1004]
The current logic, that a definition is conflicted with a "needs alias" message if it exists _anywhere_ in the codebase, is probably too strict.

We probably do want that message when the definition already exists in the current namespace, but only then. If it exist somewhere else, we should just create the alias and notify the user that we've done so.

**Comment by mitchellwrosen** [comment]
Hypothetical scenario mentioned by @aryairani in slack:

Say I am stubbing out a fibonacci function and I just want some symbol to write tests against.

```
fib n = n
```

I save my file and Unison just makes an alias to `base.id` (whoops...).

Later I fill out `fib` a bit more so its inferred type is `Nat -> Nat`, not `a -> a`

```
fib n = case n of
  0 -> 1
  1 -> 1
  _ -> fib (n-1) + fib (n-2)
```

Then Unison says the definition is ok to update... and I end up with a big edit frontier because I've updated `.base.id`! :(

I wonder if there is room here for a sort of "copy on write" definition?
