### ISSUE TITLE
Design and implement faster runtime

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1055]
We had a discussion today with @dolio who will be working on improving the performance of the Unison runtime. The hope is that this new version will be the thing with reasonable performance which we use for the foreseeable future until we invest in writing a proper JIT. 

### Things that we think are slow about current implementation:

* Unboxing and pointer chasing in main interpreter loop
* Boxing and unboxing of arithmetic operations
* Don't have proper tail calls, just periodic "cheney on the MTA" style garbage collection of stack, which is weird and slow
* Pattern matching implementation seems slow (runtime works directly with nested patterns and does some crazy stuff with lists of cases to consider)
  * @dolio suggested having runtime just deal with 1-level patterns, and there's a well-known transformation that can convert nested patterns to 1-level patterns which could be done as part of compilation. (We discussed if this is still valid if guards can make ability requests... I  think we should just disallow this in typechecker for now)
* Universal operations (==, <=) etc currently do some crazy things to be able to compare cyclic values. Correct fix is probably to not have cyclic values, just convert everything to supercombinators, stick all supercombinators in an array, and recursive references are just indexes into that array.
  * We can also keep a `Map Reference Int` that tracks code already compiled, keyed by hash, so that same-hash definitions can just point to literally the same slot in the code.
* Was there anything else?

Suggestion: work on a totally separate thing (maybe create `IR2` and `Rt2`) and experiment there with IR and runtime representations using some microbenchmarks, ideas below. For now, don't worry about compiling from Unison terms to whatever low level IR (as long as it's plausible that we could write such a compilation). We can do this integration once we have a sense of what representation we actually want to use because it performs well enough.

### Ideas for benchmarks:

* Add up the numbers 1 to a million (tests straight line performance for loops, basic arithmetic)
* Exponential fibonacci with no memoization (tests function call overhead)
* Given a binary tree of `Either Nat Nat` compute the sum of the `Left` values (tests pattern matching overhead). `type Tree a = Empty | Bin (Tree a) (Tree a)`
* Mapping over the builtin list type using a tail recursive loop with an accumulating parameter (tests integration with Haskell native types in the runtime)
* Add up the numbers 1 to a million using a `State` ability (tests efficiency of requests and handlers).

The thought was to encode these benchmarks directly into the IR. It's a bit tedious, but might be okay with some smart constructors.

### Other notes:

* Recommend joining the #contrib channel on our slack to discuss development, invite is: https://unisonweb.org/slack
* Don't worry about doing any sort of specialization of closures (and definitely don't do that eagerly for every partial application). Doing that efficiently / lazily could be a science project for later.
* We didn't really discuss algebraic effects. Current runtime converts to ANF and builds up continuations while unwinding. This would probably work but is something to whiteboard further. Initial phase of work could skip doing effects.

**Comment by dolio** [comment]
I did some experimenting with various stuff.

1. The open source Java-based ermine is surprisingly fast. ~4s to add up 1 million numbers in a loop on my home machine (which is reasonably beefy; i7-4770).
2. I hacked up some manual code for doing the same thing in the low level Haskell ermine interpreter that Ed and I wrote (after fixing some of its bugs), and it was actually much slower. More like 10s. I did manage to tweak the approach to some things and sped it up to match the Java version, but these were the problems I noticed:
    - We were just working toward getting it functioning, so we didn't think about making sure GHC optimized it properly, and it doesn't; too much stuff gets boxed and rebuilt (like the machine state, which is a big record).
    - The interpreter was written with respect to an arbitrary `PrimMonad`, and lack of specialization there seemed like it was blocking a lot of further optimization.
    - Implementing primitive instructions with a wrapper function caused a lot of boxing for said primitive instructions. You'd need things to be properly inlined to avoid having slow indirections in GHC's generated code, so it's probably better to just include the instructions as part of the interpreter.

I also wrote a [proof of concept interpreter](https://github.com/unisonweb/unison/files/3964321/POC.txt) and implemented some programs by hand. It's doing everything unboxed, so it's only representative of what would happen if worker-wrapper were implemented. Also some of the hand-written control flow might be more optimized than is realistic. I can add up 100 million numbers in 2 seconds, and the 36th fibonacci takes 2.6s (which is better than ghci, actually, but I think that's because of worker-wrapper). I doubt it'll be possible to match this once things are fleshed out, but it at least shows the following, I think:

1. Code represented as an ADT isn't a real problem. There's no need for actual byte code. I can even add a bunch more primitive instructions and it doesn't seem to make a big difference.
2. An ADT call stack is also pretty much fine. If you use stack, there's a lot of nominal GC going on, but it doesn't take a lot of time. I implemented a manual mutable array based call stack and it didn't seem to speed things up significantly. _Possibly_ if you went all the way to bytecode and could store program counters and the like on the call stack instead of ADT-represented code it could make a difference, but that's complication that might not be necessary.
3. GHC is actually too clever for the `loop` example in some ways, because it specializes `eval` to a degree that `Let (Dec i)` works the same as my manual stack-avoiding `DecThn i`, and so `loop` does no call stack allocation. I'm not sure what exactly is causing the optimizer to recognize that this is worthwhile, but it's pretty cool.

Incidentally, [here](http://matt.might.net/articles/cesk-machines/) is a link to an overview of CESK machines, which I think is a worthwhile abstract machine model to have in mind. For instance, the machine in that article has call/cc, and I imagine they can also handle delimited control well, which is similar to how you might implement algebraic effects.

**Comment by atennapel** [comment]
The paper ("Effect Handlers via Generalised Continuations")[https://bentnib.org/handlers-cps-journal.pdf] gives a CEK machines for algebraic effects (both shallow and deep). I believe CEK machines give you tail recursion for free (?).

For abstract machines (this research)[https://github.com/input-output-hk/plutus/blob/master/docs/fomega/evaluation/machines.md] might be relevant too.

**Comment by dolio** [comment]
Nice. That first paper looks very similar to what I had in mind, so it's good to know some people have worked it out rigorously.

**Comment by dolio** [comment]
Here are some additional notes from things I've been investigating.

First, here is a model of deep handlers based on an implementation of shift/reset:

    newtype K r m a = K { rK :: (a -> m r) -> m r }

    reset :: Monad m => K r m r -> m r
    reset c = rK c return

    shift :: ((a -> m r) -> m r) -> K r m a
    shift = K

    data Some σ m r
      = None r
      | forall c d. Some (σ c d) c (d -> m (Some σ m r))

    type Eff σ r m a = K (Some σ m r) m a

    handle
      :: Monad m
      => Eff σ a m a
      -> (a -> m r)
      -> (forall a b. σ a b -> a -> (b -> m r) -> m r)
      -> m r
    handle m d k
      = rK m (return.None) >>= fold
      where
      fold (None a) = d a
      fold (Some op arg resume) = k op arg (\y -> resume y >>= fold)

    call :: Monad m => σ a b -> a -> Eff σ r m b
    call op arg = shift $ \resume -> return $ Some op arg resume

The idea is that handling is `reset` plus folding, and effects are `shift` plus constructors. I think that shallow handlers are more analogous to control/prompt or similar, which requires a slightly different (and more tedious) presentation.

Anyhow, this suggests that any technique for efficiently implementing delimited control can be adapted to effects and handlers. And once you're manually managing stacks, 'dynamic' delimited control (control/prompt) isn't really any worse to implement than 'static' (shift/reset). Also the above uses one effect signature (`σ`), but you could have multiple signatures with multiple prompts.

It also seems worth thinking about the fact that this makes handle/effect extremely similar to case/constructor, to a degree that they seem like they could almost be the same thing in an implementation. For instance, in something like STG, the way case works is that you push an evaluation stack frame with all the branches, and evaluate the scrutinee. Each branch is code that works in a data stack that has been extended with the fields of the respective constructor.

For constructors, I don't mean the heap allocation part, I mean the evaluation part. What they do is push the right fields onto the data stack and return the tag back up the evaluation stack (the heap-allocated value is stored information that allows us to do this without re-running the computation necessary to determine the tag and fields). If we get to a case, we can examine the tag, and start evaluating the appropriate branch.

The point is, handlers and effects seem to have the same structure. The differences are:
1. Handlers expect a continuation as one of the 'fields'.
2. Evaluating an effect grabs a portion of the continuation, which is identified by marks put in place by handlers
3. The heap-allocated information is probably less relevant for effects

I think this kind of suggests that these capabilities could be fruitfully decomposed into orthogonal parts of a runtime. You have:
1. Tag scrutinizing frames
2. Marks on the continuation
3. Tag return
4. Continuation capture up to a specified mark as a value
5. Heap allocation of boxes

Data types use 1, 3 and 5. Effects use 1-4 (maybe 5 if you can reify effectful things into a first class data representation? I thought Frank had ideas about that, but I'm not certain). The point would be that each of these is kind of a well-known low level machine operation, and you can generate code that uses them from the more compound features. This keeps the machine itself (hopefully) minimal and easier to optimize. I'm not sure it makes a huge difference in an interpreter, aside from logical duplication of code. But it might be a good idea to try to follow this path in view of an eventual proper compiler to machine code.

**Comment by pchiusano** [comment]
@dolio looking good so far, can you incorporate this into an iteration of your runtime prototype? Note that we have shallow handlers in Unison, a la Frank.

**Comment by pchiusano** [comment]
Just some notes from discussion with @dolio today:

* Dan wanted to come up with a better way of constructing the `Request` lazily, so that you don't need to literally allocate something on the heap if it is going to be immediately matched on / deconstructed by the handler function. He has some ideas on this, basically providing support for 'by name' arguments in the runtime.
* In the common case, we'd like to avoid building up continuations willy nilly. One idea is that handlers can in restricted circumstances be pushed down to their use site and get a more direct interpretation there. Some likely relevant resources are [Runners in Action](http://math.andrej.com/2019/10/28/runners-in-action/) and [Algebraic effects in C](https://www.microsoft.com/en-us/research/wp-content/uploads/2017/06/algeff-in-c-tr.pdf).

In terms of next steps:

* Dan is going to do some more reading / prototyping and come up with something to represent effects + handlers in a reasonably efficient way.
* Once we have something we are happy with, next thing to sort out is interaction with `IO`. Dan thought just put the interpreter in `IO` and do something like runners in action where you push down to the use site, then `IO` operations are super efficient. Observation is that when doing this pushing down, you can't push past a scope which does its own `IO` handling with pure Unison code, which is something we still want to support (for like mocking out `IO`, say). The runners in action paper probably discusses this sort of thing.
* After that there's filling in all the primitive operations we currently support (can get inventory by checking out the existing runtime).
* And then we can integrate this into a new `Runtime` implementation. I'd like to make a tweak to the `Runtime` interface to allow the runtime to do caching of compiled forms, but we can maybe do that as part of the integration or afterwards.

Dan is going to work in a topic branch here in the main repo, will create `Rt2.hs`, `IR2.hs`, and whatever else he thinks makes sense. We can do some module reshuffling later if we want.

__Other notes:__

* The ANF transformation will just enforce that evaluation is left to right for function call syntax. This is easy enough to understand and program against, but it does have the property that effect order isn't 'depth first', so if you have `f x y (State.put 22)` and `f x y` is fully saturated and has `State` effects, those will happen _after_ the `State.put 22`. Just something to be aware of.
* I feel like there was some other interesting point of discussion that I am now forgetting. :)

**Comment by dolio** [comment]
Here's some further thoughts after getting back into this today (didn't really have any time to do anything over my holiday visit).

As mentioned, when you have certain forms of handler, you ideally want to be able to thread the handler code down into the spots where the operations are called, and just use the handler code immediately, and avoid building a continuation. The worry is that you can't always do this threading when actually capturing the continuation is necessary.

However, it seems like as long as control effects are supported by the runtime, _every_ handler can be implemented this way. My demo with shift/reset above implemented `op` by immediately calling `shift` and yielding a reified continuation. But, if we're threading handler information through, then presumably the handler code can call `shift` itself, if and only if it needs to. If handler code is generated to not `shift`, but simply do something inline when possible, then the expense is not incurred.

How the threading works with respect to nesting handlers with different properties is something I still need to think about, though.

---

I read the part of Effect Handlers in C about tail call handlers. One important thing it mentions is that you need to be careful when doing this sort of 'threading' that you still account for skipping over intermediate handlers when executing the handling code. So if you have H_2 nested under H_1, and call an operation handled by H_1, effects in H_1 itself should not be handled by H_2, because the latter is captured in the continuation. They accomplish this by adding stack frames that tell you to skip over certain handlers.

I also went back through Runners in Action, and it doesn't seem to really address much of this. It presents some mathematical underpinnings of what all this is doing, but most of the paper is about a particular set of algebras you might want to use for structuring programs with runners. There isn't really much about efficient implementation, as the implementations in the paper are pretty naive. What talk there is of efficiency is more references to other projects that might be abstractly described by the content of the paper. So, possibly the most useful aspect of the paper is a mention that Multicore Ocaml implements linearly-used continuations more efficiently, and requires you to specifically request a less efficient implementation for non-linear uses, which might be related to the idea that each part of a handler might call shift or not. I'll probably take a look later.

I'll also start digging in and actually getting some stuff committed in a branch this week.
