### ISSUE TITLE
Spurious use-clause in roundtrip

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#1063]
The following definition

```
fromDigits = Nat.fromText . join "" . map Nat.toText
```

results in the following when pretty-printed:

```
fromDigits : [Nat] -> Maybe Nat
fromDigits =
  use
   ( Nat.fromText (Text.join "")) (List.map Nat.toText)
```

**Comment by atacratic** [comment]
Could you help me compile the example?  I get

```
  The 1st argument to the function base.List.join is base.Text, but I was expecting [[a]]:
  
      3 | fromDigits = Nat.fromText . join "" . map Nat.toText
```

**Comment by runarorama** [comment]
Try this:

```
join : Text -> [Text] -> Text
join joiner l =
  case List.uncons l of
    None -> ""
    Some (h, t) ->
      use Text ++
      foldl (acc cur -> acc ++ joiner ++ cur) h t

fromDigits = Nat.fromText . join "" . map Nat.toText
```

**Comment by runarorama** [comment]
I'm pretty sure it's the name `.`

**Comment by atacratic** [comment]
Ha, yeah, that would do it.  
```
base.. : (b ->{𝕖} c) -> (a ->{𝕖} b) -> a ->{𝕖} c
```
It didn't occur to me when writing the use stuff that a name segment could itself contain a `.` - the code merrily splits names on `.` characters itself, which I was aware was a bit janky...  

But it looks like even https://github.com/unisonweb/unison/blob/master/unison-core/src/Unison/Name.hs takes the same approach - lots of `Text.splitOn`.  Does that stuff really cope with `base..`?  Seems doubtful.  

Do we have a wider issue here where `Name` should contain a `[Text]` rather than just a `Text` - either that or should use escaping at least in its internal representation (e.g. `base.\.`)?

Or are we saying that `.` is allowed as a name segment exactly when it's the final segment, and you can distinguish that case as it's the only one where the name ends in a `.`

**Comment by aryairani** [comment]
+1 to “name use `[Text]`” #741 #742

**Comment by mitchellwrosen** [comment]
@aryairani #741 indicates that a `Name` should be non-empty (so `NonEmpty Text`). Is that still true?

**Comment by aryairani** [comment]
@mitchellwrosen Yes.  IIRC we have a few places where NEL could be used but isn’t due to additional hassle over `[]`, but I’m for it.

**Comment by aryairani** [comment]
The current round trip output as of this writing is:

Before:
```
fromDigits = Nat.fromText . join "" . map Nat.toText
```

After:
```
fromDigits : [Nat] -> Optional Nat
fromDigits =
  use  
  Nat.fromText  Text.join ""  List.map Nat.toText
```

(Note three invisible `.`)
