### ISSUE TITLE
Default author and license configuration setting

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1129]
This could use some more design, but basic thought is to have a configuration setting for default author and license, and have author and license get linked automatically into new definitions. 

Also emit a warning if the user typechecks a file without having these settings in place.

Aside: configurator file format is kind of ugly, but not sure if we want to swap that out for something else now.

**Comment by mitchellwrosen** [comment]
+1 to replacing configurator... it's
- non-standard
- not maintained at all (last upload 2014)

**Comment by pchiusano** [comment]
@mitchellwrosen what do folks use these days instead?

**Comment by mitchellwrosen** [comment]
Don't know, maybe TOML? I like dhall but it is not very user friendly at the moment

**Comment by pchiusano** [comment]
What if we just use a .u file as the config? Seems better in every way.

**Comment by aryairani** [comment]
> What if we just use a .u file as the config? Seems better in every way.

Hah, I like it.

**Comment by pchiusano** [comment]
Design discussion with @runarorama on this. We liked idea that the configuration _values_ actually just live in the codebase, and the configuration file just has pointers to the names of those values. This avoids needing like a separate typechecking of config - everything in the codebase typechecks, so the only thing that can go wrong is that you are referring to a nonexistent name.

Discussed moving to [config-ini](https://hackage.haskell.org/package/config-ini) for the file format, which is the usual:

```ini
[NETWORK]
host = example.com
port = 7878

# here is a comment
[LOCAL]
user = terry
```

@runarorama brought up the good point that you might want a different author/license for different subnamespaces. How to handle this? Just gotta come up with some format for this sort of thing.

```ini
# root settings
[.]
# these named values get linked to all new definitions, and to updated definitions 
metadata = ".metadata.authors.runarorama, .metadata.licenses.MIT"
pull = "git@github.com:runarorama/unisoncode"

# settings for a subnamespace
[.work]
metadata = ".metadata.authors.runarorama, .metadata.licenses.AcmeMegacorpAllRightsReserved2020"
pull = "git@github.com:runarorama/unisoncode"
```

Also talked about having some UCM commands for viewing/editing the config, so people don't have to edit the file directly. Could potentially be done later.

To do this,

**Comment by aryairani** [comment]
You can warn or get confirmation if the user deletes a name referenced in the config file.

**Comment by anovstrup** [comment]
@pchiusano If the config is in the codebase, is there a need for a config file _at all_? Instead, a convention could identify the local configuration as an ordinary value (e.g., `.local.config : UnisonConfig`). Or maybe the config file just identifies a mapping between namespaces and config values:

```
# identify config for the root namespace
. = ".local.config"   # .local.config is a value of type UnisonConfig
# identify config for the .work namespace
.work = ".work.config" . # .work.config is a value of type UnisonConfig
```

**Comment by runarorama** [comment]
A simple idea I had: allow namespaces to have links. One link could specify the default author for any definitions under the namespace, another the default license, and there could be one for the default push/pull location.

This could have the convention that namespace links are not copied during a push or merge (i.e. they're local to *your* codebase).

**Comment by pchiusano** [comment]
Mmm... so when adding / updating a definition, it gets the metadata attached to all parent namespaces? Doesn’t seem like push/pull defaults fits into this.

**Comment by runarorama** [comment]
Attaching all the namespace links to definitions under it seems like a too-big solution. Maybe just a naming convention for things that need to get attached to definitions. E.g. a namespace link with a type like `Default a` attaches the `a` to all definitions under the namespace.

**Comment by runarorama** [comment]
Collecting all the ideas here in one place along with pros and cons.

### Just use Configurator

The idea here is to add Configurator options for default author and license, per namespace, and to do so using the existing config file.

#### Pros: 

* This is the simplest thing that could possibly work, and gets us something working without redesigning how we're doing config. We can replace configurator with something nice later, with a separate issue.

* All the work done here makes it easier to transition to a different solution later.

#### Cons: 

Configurator files are read-only, so there's no good way of manipulating the config from UCM.


### Switch to an .ini config

Essentially the same idea as above, but additionally switch to the ini file format and add UCM commands for reading/writing them.

#### Pros:

* We can easily read/write these files with existing libraries, which enables UCM commands to add/remove config values.
* More familiar file format for most people.

#### Cons:

* Libraries for loading ini files don't readily support hot-reloading of configs like Configurator does. Could just add a `config.reload` command or use the file watching we're already using for .u files.
* Might be throwaway work, since this may not be the final UX we want.


### Use a naming convention for config inside the codebase

This idea is that instead of an external config file, the config could just live in the codebase. Could just have a naming convention. For example we could reserve the namespace `._config`, so the default author for the `.foo` namespace could be `._config.foo.defaultAuthor`.

#### Pros: 

* No external config file necessary.
* We can get rid of the dependency on configurator or similar.

#### Cons:

* Seems like an ad hoc solution.
* Whatever name we choose becomes unavailable for ordinary definitions.
* UCM needs to be aware of in which contexts these names are special and in which they're not. So for example you might not want to `push` and `pull` these values, but you'll want `view` to see them as normal values.

### Allow namespaces to have links

The idea here is that namespaces, in addition to definitions, can be sources for the `link` command. A link with a particular type like `Default a` would be also linked to every definition added to the namespace (and all subnamespaces).


## Other considerations

### Changing the author/license when adding aliases?

If a definition already exists, and we add a name for it to a namespace with a default author and license, do we change the author/license? Do we retain the original links? What if there is no author or license on the original?

**Comment by pchiusano** [comment]
@runarorama great writeup!! Questions:

> Configurator files are read-only, so there's no good way of manipulating the config from UCM.

Is that true? Isn't it just a file on disk somewhere? Presumably we could write code to dump a Config value to the file, even if the libraray itself doesn't provide this. Or is there something that would prevent us from doing this?

Other comment is it probably doesn't matter what the file format is if we surface UCM commands for CRUD of config settings. Like with git, I rarely interact with the config file format (though I guess it is ini) because the tool itself provides commands for CRUD.

> UCM needs to be aware of in which contexts these names are special and in which they're not. So for example you might not want to push and pull these values, but you'll want view to see them as normal values.

Seems like pushing and pulling those values is fine, but just "not recommended". Not much different than like checking in your local editor settings or something. 

Other comment on this approach, is if we went with it I'd suggest that the actual definitions live elsewhere, and the `_config` stuff just points to it, as in:

```Haskell
_config.author = .metadata.authors.runarorama
```

So the local namespace tree looks like

```
_config/
project1/
project2/
```

And you `push` / `pull` from within your project1/2.

> The idea here is that namespaces, in addition to definitions, can be sources for the link command. A link with a particular type like Default a would be also linked to every definition added to the namespace (and all subnamespaces).

This one sounds pretty interesting but I have the most questions about it. Overall, my concern is that if namespaces are being sliced/diced/remixed/curated with definitions getting copied from elsewhere, any default metadata at the namespace level is going to become out of date or wrong. Example is I'm in a namespace that's MIT licensed by Alice, and I do an `alias.term` or `copy` for some definition that's in a namespace that's GPL licensed. Seems like we'd have to catch that and either prevent it, get user to opt into the default license, or switch the target namespace from being default licensed to having individual licenses on every definition. I could see needing to carefully audit and tweak other commands as well.

Possible I am totally misunderstanding your idea here :)

**Comment by runarorama** [comment]
The license linked to the namespace would just be the default license for new definitions in that namespace. You could always copy in definitions with different licenses and that should be fine. So we should separately have something like the `license` command that takes a namespace and lists all the licenses of everything in the namespace.

**Comment by pchiusano** [comment]
@runarorama oh I think I see, so the license gets applied to all the definitions in that namespace when those definitions are created within that namespace?

Am not sure how that would work for like author (or even license given that license includes a copyright holder), which is different for each definition. You could maybe develop new definitions in a separate namespace (which has you as default author), then copy them over once you're done with them. I have been thinking that's probably a good practice anyway (avoids polluting patches with random churn).

**Comment by runarorama** [comment]
One thing I super want to avoid is churning the license and author config. Like for example if we go with the .ini file design detailed above, every time you fork a new branch you have to make sure to configure the license for that branch. That's probably going to be unworkable. So an in-codebase solution is probably the only good option.

**Comment by runarorama** [comment]
Also, there are three kinds of configs that we want so far, and they all need to work a little differently.

1. Default author: something you probably don't modify for each namespace. You'll set it once for your whole UCM setup and leave it alone. Maybe you'll want to tweak it if you're pairing with someone else or something. If it were a per-namespace thing, it should definitely not come along during a merge into a different namespace.
2. Default license: Something you'll want to set globally for your whole codebase and then override for specific subnamespaces. Should probably get pushed/pulled/merged since you want contributors to have the same license generally.
3. Default push/pull location: Also per namespace, but should certainly not come along during a merge.

So it's rather like the author should be global config/state for UCM, default license should be part of the namespace somehow, and push/pull should be config/state for just individual namespaces.

**Comment by pchiusano** [comment]
Just discussed w/ @runarorama, outcome: just use Configurator for now, hook up Configurator options for setting default metadata on a per-namespace basis. Step 2 would be to expose some UCM commands for CRUD of config settings (Configurator provides enough of an API to make this doable), but that could be done later, and it's not the end of the world to give people some documentation for how to update a config file.

Rationale: all the other options either had too many design unknowns, drawbacks, and/or are more work, and this also seems like something that's easy enough to swap out later, especially with it not being part of the codebase format.

An interesting observation - in Unison, definitions do not belong exclusively to any one particular library, and the same definition may be included in many different libraries. Thus, it's not really expected or feasible that all the definitions in a library will be licensed in the exact same way. As a library author / "curator", you'll probably have some license constraints (like maybe you won't include GPL in your library, or maybe you ONLY allow GPL2 and GPL3) but you will allow multiple licenses. This is similar to what projects already do for their dependencies - a BSD licensed project may depend on an MIT or Apache licensed project, etc, and this works out fine.

**Comment by runarorama** [comment]
Still to do:

- [ ] Apply default metadata to definitions in subnamespaces instead of only in the exact namespace mentioned in the config.
- [ ] Apply default metadata to updates.
