### ISSUE TITLE
Recursive functions of arity > 1 whose body requires abilities get poor inference

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1185]
Example:

```
ability Stream e where
  emit : e -> ()

Stream.range : Nat -> Nat ->{Stream Nat} ()
Stream.range n m =
  if n >= m then ()
  else
    emit n
    Stream.range (n + 1) m
```

Incorrectly infers `Nat ->{Stream Nat} -> Nat ->{Stream Nat} ()` as the type of `range` (in reality, it is still pure after receiving just one argument, and only requires `Stream Nat` after getting its second argument). What's going on here is that we generate existential ability variables for the  unadorned arrows. In the body of `range`, any place a function is called, we unify that function's ability requirements  with the ambient. In the body of `Stream.range`, the ambient abilities are `{Stream Nat}` so the `Stream.range (n + 1)` partial apply picks up that same ability requirement for the existential ability var attached to the first argument of `Stream.range`.

I believe this poor inference explains needing annotations on stateful recursive handlers that handle one ability into another.

Some half-baked ideas on possible fixes:

* We currently don't do anything special for n-ary function application, it's just typechecked one argument at a time, which is quite nice. However, I could imagine treating n-ary function application differently and that fixing the problem. 
* That is, if you have `f x y` and `f` has unknown abilities for its first argument, you could leave that first argument's abilities unknown (or perhaps set it to `{}`) and then unify just the second argument's abilities with the ambient.

@dolio this could be a good one for you to look at to get up to speed on the typechecker, probably needs some discussion first though

**Comment by dolio** [comment]
I'm no expert on this part of things yet, but it seems like _at least_ you would want:

    f x y z = ...

to not make up effect variables for `f x` and `f x y`. The declaration form tells you that it can't be doing effects, because it's taking all three variables at once, and the only way to have effects in there is to move the variable binding past the `=`.

Is the problem that it's turned into nested, single-argument lambdas before type checking, so that it is less clear syntactically that this is going on?

**Comment by pchiusano** [comment]
@dolio We do translate everything to nested single-argument lambdas but there's smart patterns if you want to match an n-ary lambda, so that's nbd. 

I do think there's some special case for n-ary lambdas but not sure exactly what it is. Relevant: the type we try to infer for like `foo x y = x  *  y  + 42` is actually `forall e1 e2 .  Nat ->{e1} Nat ->{e2} Nat` (this  will be displayed as  just `Nat -> Nat -> Nat`), not  `Nat ->{} Nat ->{} Nat`. Assuming we keep that behavior, we still want to create the existentials and atttach them to the arrows, we just don't ever want to solve them to anything.

IIRC, the ability polymorphic version is a bit nicer for inference elsewhere vs the version that is pure  - it's like `forall m . Monad m => m Blah` is isomorphic to `Identity Blah`.

**Comment by dolio** [comment]
I thought about it a little more, and recognizing n-ary lambdas probably isn't ideal. It seems pretty ad-hoc. Seems like it might be better to keep track of some kind of 'ambient' effect variable to unify with for the purpose of inference, and that would always correspond to the nearest lambda or something. That way you don't immediately have the same situation with something like:

    foo x = let z = 5 in y -> ...

Being really specific to a particular syntactic form just seems like the wrong solution.

And yeah, being polymorphic instead of 'no effect' probably makes sense. I more meant that you want to be equivalent to not making up unification variables (that are actually used) for all those nested lambdas.

**Comment by pchiusano** [comment]
@dolio I think I understand what's going on. The `Stream.range (n + 1)` is calling an unknown lambda with an existential ability requirement. That gets unified with the ambient ability at this point, which is `{Stream Nat}` (the abilities of the nearest enclosing function type).

I explored a fix here: https://github.com/unisonweb/unison/compare/topic/abilities-fixes-1185 (also includes our earlier improvements)

I'm not sure it's the fix we want though. It zeros out abilities on nested lambdas before even looking at the body, so `x y -> ...` immediately becomes a type like `X ->{} Y -> ...`

It's possible that a polymorphic ability would be a better type, though I'm not actually sure about that and would like to talk through it.

There's also the issue you pointed out that it's specific to the particular syntactic form. I'd like to see if that could be improved but didn't see an obvious way.

**Comment by dolio** [comment]
That seems like a likely explanation. I don't understand why it would happen, though. This seems to be something like the sequence of events that are wanted:

1. We make up unifier variables to have `range : α ->{ε1} β ->{ε2} γ`
2. This type is used for the lambda term, so that once we walk under `λ m n`, the ambient ability is `{ε1,ε2}`
3. The recursive calls find exact matches for their unifier variables, so no instantiation happens for the recursive call

Then you will end the checking with open unifier variables and can do whatever you want with them. Is the bug caused by making up unifier variables for `range`, and then making up _separate_ variables for the lambda terms in its definition, so that an exact match is not found? If so, that is because that is not a valid strategy in combination with the 'instantiate to the whole ambient ability' behavior. The made up variables are meant to correspond one-to-one, but the instantiation is not respecting that. So identity of variables matters.

**Comment by pchiusano** [comment]
Maybe surprising, but the ambient ability actually should just be based on the innermost arrow type, not the accumulation of all outer arrows! Here's a simple example (which should definitely not typecheck) to illustrate:

```Haskell
ex : Nat ->{IO} Nat ->{Stream Nat} ()`
ex n = 
  IO.launchMissiles n
  r x =
    IO.launchMoarMissiles (n + 1)
    Stream.emit 22
  r
```

You can call `ex 10` in a context that supplies `IO`, but according to the type signature of `ex`, the function you get back has a type which says it doesn't require `IO`. So you should not be able to use `IO` inside of `r`.

IIRC, Frank didn't really have much of a treatment of partial application, but once you have partial application and think it through, the way Unison is doing it seems right.

**Comment by dolio** [comment]
Hmm, yeah, I see.

Maybe there should be multiple sorts of effect unification variable. For a function argument it makes some sense to make the entire ambient ability available, but for a recursive call you want the unification variables to push information into the ambient scope. It might be a polarity that is tracked.

**Comment by pchiusano** [comment]
We came up with a good fix for this. It's not specific to the syntactic form: 

For existentials you conjure up for ability inference, track in the typechecker whether they are in positive, negative, or invariant position. This polarity info becomes part of the ordered context elements.

During an ability check for `f : a ->{e} b`, with `{e3}` being ambient:

* If `e` is positive, make sure that `e` is contained in ambient. If ambient has an unsolved existential, `e3`, just solve it to `{e, e4}` where `e4` is fresh. (Seems like subtype e ambient should do that.) 
* If `e` is negative or invariant, then do the stuff we’re doing now: instantiate it as big as possible to all of ambient.

Question about what the right spot is to implement this, like maybe a tweak to `subtype` would do it. Ideally, only have to update 1 spot in the typechecker to make use of the polarity info.

Optional last step: If an ability variable always appears in positive position in an inferred type, just zero it out.

**Comment by pchiusano** [comment]
I am going to figure out which branch has latest WIP and update that branch to current trunk.

**Comment by dolio** [comment]
I did some investigation on this, but simple very simple approaches didn't seem to work. I have to go through what's happening in more detail, but one of my concerns is this:

Suppose we have `e1+` and `e2+` that we are inferring in the original example. We go to the main body, and the ambient effect becomes `e2+`. Then we make the recursive call, and the ambient becomes something like `{e1+, e3}`. But now there are two variables to instantiate in the ambient context, and if some other concrete ability is used, it might actually get stuck in the wrong one.

So, I think what I'm going to do is split the ambient tracking to have a designated 'slop' variable for the scope, so that the correct one gets picked. When something needs to instantiate it partially, it can replace the designated variable. Another possibility would be not unifying immediately at all, and instead just collecting up wanted ambient stuff, and trying to unify after collecting the entire scope. I'm unsure if that would make error messages worse in the near term, though.

**Comment by pchiusano** [comment]
@dolio hmm yeah I can see what you're saying. Basically, you don't want the ambient to contain multiple unsolved existentials since when you get a concrete request you won't know which it should target.

I don't totally get the slop proposal. Thinking through this example:

```Haskell
foo : (a -> b) -> a -> r
foo f a =
  f a
  foo f a
```

The signature of `foo` becomes: `(a ->{e} b) ->{+e2} a ->{+e3} r` where I'm putting `+` in front of the ability variables that are in positive position. Then when checking the `f a` call, we currently do `abilityCheck {e} {+e3}`, which succeeds with `e3 = {e, +e4}` and is problematic since now ambient has two unsolved existentials.

How would the slop proposal fix this?

> Another possibility would be not unifying immediately at all, and instead just collecting up wanted ambient stuff, and trying to unify after collecting the entire scope. I'm unsure if that would make error messages worse in the near term, though.

I don't follow this proposal, or I guess I don't see what's going to be easier about collecting up all the requested abilities. Now you have a huge list of ability requests including a bunch of unsolved existentials, and you need to figure out how to solve them. Has anything been gained by doing this? If it's somehow simpler to implement this way, is there some reason it can't be a more incremental algorithm? 

If this approach is workable, I think the error messages could be okay if you are careful to attach location information to the requests.

**Comment by dolio** [comment]
The 'slop' proposal is that we store `e3` in some type checker state as the variable you unify with to extend the ambient ability, and after your example ability check, it gets replaced with `e4` (which is the one we made up to replace `e3`). The problem I see is that the stateful stuff is the context, and the 'ambient' stuff is reader.

The way that the post-unification would help is that you aren't searching an instantiation of some 'ambient' type to find a variable to unify with (and finding out there might be two). Going out of the scope tells you which variable/type is supposed to cover all the wanted abilities in that scope, and keeping track of the wanted abilities doesn't induce such ambiguities. It's similar to keeping track of the 'slop' variable, but using scoping rather than state.

I had some other reason for thinking the latter might be useful, but I'm forgetting what it was.

**Comment by pchiusano** [comment]
K, gotcha. Let me know if you want to talk through anything. I feel like either approach could work. 

It sounds like with the slop variable you could get away with adding that to the state (rather than reader) part of the typechecking monad, and then if needed introduce a specialized combinator, something like `withAbilityInference :: M v a -> M v a` which creates a fresh slop variable at the beginning and clears it at the end.

**Comment by dolio** [comment]
After reading some more Koka stuff, I'm suspecting it wouldn't do any better on this front than Unison does. However, it's set up to encourage tupled function arguments, so you wouldn't notice if you go with the flow. I think if you wrote a curried function, though, it'd infer the same ability row for pretty much everything involved in the function, because its approach is just to have all rows agree, and there isn't even a mechanism for weakening rows in a subtyping kind of way.

**Comment by pchiusano** [comment]
I had an idea which might be very silly, but just recording it here. What if ability inference variables in positive position are always just solved to `{}` when you do an ability check for them, and ability inference variables in invariant or negative position are always solved to the entire ambient set (or else yield a type error if that can't be done).

I believe this would do fine on the `List.map` example - it would infer `(a ->{e} b) ->{} [a] ->{e} [b]`, which is a perfectly cromulent type (there's no real need to infer an extra `{e2}` on the arrow after the first parameter). It likely stops working great when a HOF internally has a `handle` block inside it and the handle block invokes a function that was passed in. I haven't played with it enough to know how bad that would be.

Another angle we have discussed that's relevant to this or any other algorithm is that if we can have a clear algorithm, even if it has limitations, we can just add nice error messages for detecting these limitations and telling the user how they can respond. It's not a big deal to have a little extra typing to satisfy the typechecker; what's not great is having an unclear model of what will satisfy the typechecker and then cryptic error messages that don't make much sense when you go outside the bounds of what can be inferred.

Another variation I considered for invariant / negative polarity variables is to try to instantiate it to the full ambient, then that minus the first ambient element, then continuing to shrink until instantiating it with `{}`. This seems like it could get exponential and just seems weird.

**Comment by dolio** [comment]
Yeah, I don't think backtracking would be advisable.

One thing I've been wondering is whether the 'negative' positions should actually be inferred to the largest possible row. There are a couple reasons not to do this:

1. If the function gets called in multiple contexts, this is an order-dependent process. I.E. if you call it in an ambient `{E1}` and then `{E1,E2}` it works, but the opposite will error (you can already cause this).
2. It _seems_ like the best solution to the parametricity bug is to make the row semantically meaningful. So inferring `a ->{e} b` means something different than `a ->{E1,e} b`. And in that case, the former might be a _better_ thing to infer by default (assume complete parametricity with respect to unannotated higher-order functions, etc.), even though it's unsound right now.

Edit: incidentally, defaulting positive things to `{}` on their first sub-ability check has the same kind of order dependence problem.

**Comment by pchiusano** [comment]
> 1. If the function gets called in multiple contexts, this is an order-dependent process. I.E. if you call it in an ambient {E1} and then {E1,E2} it works, but the opposite will error (you can already cause this).

> Edit: incidentally, defaulting positive things to {} on their first sub-ability check has the same kind of order dependence problem.

Mmm.

One example I was pondering that you've probably thought about -

```Haskell
ability Abort where abort : () -> x

-- these all seem like possible types that could be inferred
-- 1. foo : (Nat ->{} a) ->{} a
-- 2. foo : (Nat ->{g} a) ->{g} a
-- 3. foo : (Nat ->{g, Abort} a) ->{g, Abort} a
foo f = 
  x = handle f !abort with 
    { _ } -> 42
    { Abort.abort _ -> _ } -> 43
  f x
```

Here, `f` is getting called in two places - in one spot, `Abort` is in the ambient, and in the other location, it's unspecified. We could imagine switching the order as well and calling `f` before the handle block but it would be pretty weird if this changed the inferred type. 

The type 3 seems like a weird thing to infer.

**Comment by dolio** [comment]
Right. You can't swap that case, but if the second call to `f` doesn't depend on `x`,  you can move it before `x` and potentially get different inferred types.

2 seems like the most natural type to infer without annotations. The abilities are assumed to be abstract, rather than assuming concrete abilities are used just because the function is called in a scope that allows them.

This policy actually fixes one of the problems with the 'collect all ability requests' approach. When you do that, there isn't necessarily a well defined 'ambient' ability to push into negative variables. You just record a negative variable as a wanted ability and process it at the end. But by the end it's too late to figure out that the wanted negative variable actually happened inside a handler. I think it might be possible to still keep track of extra abilities from handlers, but it occurred to me that you might not want to infer that type anyway.

**Comment by dolio** [comment]
Okay, so, here are some potential strategies I've gone through, and examples of using them.

**Strategy 1**
Subtyping just pulls everything into a negative variable on the left.
Subtyping extends a positive variable on the right.

The difficulty with this is how to keep track of which positive variable it makes sense to be pushing into. The example in this issue has two positive variables, and eventually we get to:

     e1+ < e2+

where `e1+` is the thing we _want_ to be inferred as `{}` or completely polymorphic. However, naively keeping track of a set of ambient effects will give us an ambient row of `{e1+,e2'+, ...}`, and when you perform the 'find an open variable in the ambient context' operation, you might get either one. My first solution to this was to keep track of `e2'` explicitly, but the problem with that is that there are other subtyping calls in the type checker that don't come from checking against the ambient effects. So the variable I was keeping track of could get unified with something else in these other subtype checks, and then we're back to the problem of figuring out which is the correct choice of ambient variable to check against.

**Strategy 2**
Keep track of upper and lower bounds for effect variables, rather than instantiating them. When they are generalized over, negative variables become the intersection of their upper bounds and positive variables become the union of their lower bounds.

The primary problem with this strategy is that it is completely different from the current design of the type checker. The current checker uses ordered contexts, and variables are instantiated based on this ordering. Upper/lower bounds are not necessarily ordered at all, and don't involve instantiation. You also can't use the bounding information to substitute in for variables incrementally, because e.g. the intersection may change based on checks you haven't done yet.

There also seem to be some situations where it's difficult to explain why we should actually infer a desired type. Consider the example:

    handler : (a ->{e0} b) ->{e1} a ->{e2} b
    handler f x =
      handle f x with cases
        { E.e ... -> k } -> handler k z
        { x } -> x

where the `e` variables are being inferred. The final bounds are:

    {{E}} < e0 < {{E,e2}}
    {} < e1 < {{e2}}
    {{e1}} < e2 < {}

So, we want `e0 = {E,e2}`. We can say `e1 = {}` because its lower bound is empty and it's positive. However, based on this decision, `e2` also has an empty lower bound, and is positive. So it isn't clear why we should infer a type like `(a ->{E,e} b) -> a ->{e} b`, instead of specializing `e` to `{}`. I suppose some information about the occurrence of `e2` in `e0` needs to be taken into account to make this decision, but it doesn't seem terribly straightforward.

**Strategy 3**
Don't have an 'ambient' ability set. Rather, checking `x -> m` against `a ->{e} b` just collects up the wanted abilities of `m` (with location info) and then performs an all-at-once check against `e`. A handler in `m` just subtracts the abilities it handles from the wanted ability set.

The advantage of this is that it seems like a better division of the process. Conceptually, the rule is something like:

    Γ,x:A ⊢ m : B | E0 ⊣ Δ
    E0 < E1
    ------
    Γ ⊢ λx.m : A ->{E1} B | E2 ⊣ Δ

Instead of this, the current approach just uses `E1` in place of `E0` and tries to perform every subtyping check locally. This leads to having to locally refine variables and keep track of which variables ought to be used for ambient inference.  With this more global check, keeping track of which abilities are necessary for `m` is a separate question from how to realize the subtyping for the function type, and there is less ambiguity about how things should be instantiated (e.g. a single unification of all the missing parts of `E1` could be done all at once, instead of incrementally).

I think another advantage of this algorithm is that variable polarity is unnecessary. Polarity was trying to improve the behavior of the local checks, but instead we are performing a check that already has significantly more information at its disposal.

A potential downside is illustrated by the same `handler` example above. The question is what effect we infer for `f`. If we simply collect all effects, we recognize that `e-` is needed in the body of `handler`. The recursive call actually requires that `{E} < e-`, but that is the only piece of this algorithm constraining `e-`. This means that absent the recursive occurrence, we'd probably infer the currently unsound `(a ->{e} b) -> a ->{e} b`. However, per the comment above, it seems like this might actually be a more sensible type to infer once the soundness issue is worked out.

**Comment by pchiusano** [comment]
In case anyone is lurking on this ticket and wants to follow along, @dolio and I met and talked through these options. Strategy 3 seemed like the best choice (easiest to implement, well-behaved, not order-dependent) and we couldn't figure out a way to break it despite our best efforts. So he's going to move forward with implementing that.

Some random notes that I recall from our conversation:

- Strategy 1 seemed like it leads to a mess where you have multiple ability variables in the ambient that you could potentially subtype against, and all kinds of order-dependence.
- Strategy 2 seems interesting but doesn't fit well in the existing typechecker, as Dan mentioned.
- Strategy 3 probably breaks down if you're trying to do higher rank stuff, but we decided that's fine. Higher rank stuff requires type signatures anyway. We discussed augmenting the polarity info with rank info, so we could possibly just bail with a nice error if trying to infer an ability variable that's rank 2 or higher. ("Please annotate the ability requirements of this arrow, it's too complicated for me to infer.") This would be straightforward to do.

**Comment by pchiusano** [comment]
@dolio FYI we are curating a bibliography here for Unison https://github.com/unisonweb/unisonweb-org/blob/master/src/data/docs/bibliography.md and you might have some good additions to the programming language theory > other references section. Even if you don't end up using some research directly, it can still be good to mention. Like I could see mentioning the algebraic subtyping work there, with a note that it was something we explored for ability inference.

**Comment by pchiusano** [comment]
@dolio I've got an example for you to try with the new algorithm: 

```Haskell
ability WeightedStream a where
  emit : a -> () 
  weight : Nat -> ()

ability Gen where
  done : x
  cost : Nat -> () 
  pick : ['{Gen} a] -> a

Gen.toWeightedStream.handler : Request {Gen} a ->{WeightedStream a} ()
Gen.toWeightedStream.handler = cases
  { _ } -> ()
  { Gen.done -> _ } -> ()
  { Gen.cost w -> tl } -> 
    weight w 
    handle !tl with handler 
  { Gen.pick gs -> tl } -> 
    gs2 = foldb (g -> '(handle !g with handler)) merge '() gs
    todo "above line doesn't typecheck" 

-- merge : '{WeightedStream a} () -> '{WeightedStream a} () -> '{WeightedStream a} () 
-- foldb : (a ->{e} b) -> (b ->{e} b ->{e} b) -> b -> [a] ->{e} b 
```

This yields

```
  The expression in red  needs these abilities: {Gen, WeightedStream a364, WeightedStream a364}, but this location only has access to the {Gen} ability,
  
     19 |     gs2 = foldb (g -> '(handle !g with handler)) merge '() gs  

```

The `gs` is highlighted.

It looks like the lambda passed to `foldb` is picking up some abilities it shouldn't.

**Comment by dolio** [comment]
The new algorithm can't handle it either (yet).

I can get it to type check by factoring the lambda expression out with a type, and also by reordering the arguments to `foldb`. There is sensitivity to the instantiation order, so putting the list first helps `a` get instantiated to something that will be valid for the lambda expression, but putting the lambda first seems to cause problems for the list.

Isn't the (original) algorithm supposed to have some way of dealing with sensitivity to argument ordering? I can't exactly recall what it is, and it might not actually work as well for abilities (because of the more complicated subtyping).

**Comment by pchiusano** [comment]
Ah, that's too bad. :| 

Yes, they do talk about instantiation order issues in the [original paper](https://research.cs.queensu.ca/home/jana/papers/bidir/) but I forgot what the trick was there. I want to say it may have something to do with how variables are instantiated - they are basically only refined the minimum amount needed based on their current usage, so there's always room for them to get refined further, in whatever order new information becomes available.

**Comment by dolio** [comment]
I think maybe the paper side-steps this issue by not having impredicative instantiation. That is the usual reason for considering an entire argument spine at once. I think maybe the second paper gets into that, because it has more ambiguous typing. Row subtyping is a similar kind of problematic subtyping as impredicativity.

**Comment by dolio** [comment]
By the way, here is the reasoning in the new process:

When we check the lambda expression, we infer something like `'{e} a -> '{e, WeightedStream a} ()` because there is no reason to assume that `e = Gen`, and would get handled. However, later on we're going to find out that the result is expected to be `'{WeightedStream a} ()`, which means that `e = {}`. However, this means that the list must have type `['{} a]` instead of `['{Gen} a]`. Doing the list first causes the lambda argument to be known to be `'{Gen} a` so that the handler should actually handle it.

This is kind of a significant problem if we ever make the types semantically (for handlers) meaningful. If you ever got into a situation where both ways checked, then the exact behavior would depend on how the inference worked out, but there is no real way to tell from the code written.

**Comment by pchiusano** [comment]
Aside, I think we should have a syntax for annotating lambdas with their allowed abilities. And then we should try to just bail gracefully for things that are hard to infer and suggest the user annotate their lambdas. Proposed syntax:

* `a b ->{IO} a + b` - a lambda that takes two arguments and allows `IO`
* `'{Random} (1 + natIn 0 10)`, shorthand for `_ ->{Random} (1 + natIn 0 10)`

```Haskell
printBoth x y = {IO}
  printLine x
  printLine y

-- equivalent to
printBoth = x y ->{IO} let
  printLine x
  printLine y
```

I don't see any syntactic ambiguity to doing this.

The AST modification would be straightforward, I'd just add an optional `Type` parameter to the `Lam` constructor of the term AST, and then make use of that within the typechecker. It can also also be made backwards compatible with the codebase format since all the existing lambdas can just assume `Nothing` there.

**Comment by dolio** [comment]
Should we close this issue now that the new algorithm is merged?

**Comment by pchiusano** [comment]
Yes! I actually thought this had already been closed, but I guess not.
