### ISSUE TITLE
Typechecker doesn't like pointfree style

### ISSUE THREAD

**Issue by sullyj3** [unisonweb/unison#1304]
I'm just assuming these two cases are related:
Case 1:
```
List.takeWhile : (a -> Bool) -> [a] -> [a]
List.takeWhile p = cases
  x +: xs -> if p x
             then x +: List.takeWhile p xs
             else []
  [] -> []
```
```
  _____     _
  |  |  |___|_|___ ___ ___
  |  |  |   | |_ -| . |   |
  |_____|_|_|_|___|___|_|_|
  Welcome to Unison!
  I'm currently watching for changes to .u files under ~/Code/unison_experiments
  Type help to get help. 😎
.>
  scratch.u:4:3:
  unexpected x
      4 |   x +: xs -> if p x
.>
```
Case 2:
https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1577039673008800
```
f xs = map g xs --ok
f = map g -- not ok
```
```
  These definitions depend on each other cyclically but aren't guarded by a lambda: updateAll287
     11 |   updateAll2 : [Text] -> {UpdateContext} ()
     12 |   updateAll2 = map_ update2
     13 |
     14 |   update2 : Text -> {UpdateContext} ()
     15 |   update2 = bug ""
```

> [..] the error would be in the definition of updateAll2. If written like above, I get that error, but if written like this instead, I don't.
> ```
> updateAll2 : [Text] -> {UpdateContext} ()
> updateAll2 planets = map_ update2 planets
> ```

**Comment by anovstrup** [comment]
@sullyj3 Which unison version? If M1h or earlier (not `master`), the `cases` syntax won't work. That could explain the first example, but not the second.

**Comment by pchiusano** [comment]
@sullyj3 those definitely are not related! One is a parse error (which might be because you're using a pre-`cases` version of Unison, can you check that?), one is a typechecker error. 

And the second one seems like not a bug though I'd need to see the whole program - you can't have unguarded forward references within a block. In general, in a strict language with effects, like Unison, eta reduction isn't something that can always just be done as in Haskell. It could probably use a better error message though. /cc @mitchellwrosen 

Also, FYI the `cases` syntax literally parses the same as if you added another parameter to the definition and immediately matched on it, so that is really a separate issue than the eta reduction limitations. Like if you write `foo x = match x with ...` that will actually get pretty-printed back to you as `foo = cases ...` - they parse as the same thing! (Only difference is that if you use `cases` it will make up the variable name for you behind the scenes)

**Comment by pchiusano** [comment]
Just confirmed this parses fine in `master`, so going to close!

**Comment by sullyj3** [comment]
That makes sense, thanks for the explanation!
