### ISSUE TITLE
unfortunately-punctuated message when creating new codebase in `.`

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1320]
```
$ ucm -codebase . init
  ⚠️
  
  Initializing a new codebase in: ..
```
Recommend: 
- removing the period
- maybe removing the colon (bikeshed away!)
- removing the ⚠️ and extra lines
- maybe removing the indent

**Comment by pete-ts** [comment]
https://github.com/unisonweb/unison/blob/b85f54e88607ea70d7f1d0b75acae5c699177c60/parser-typechecker/src/Unison/Codebase/FileCodebase.hs#L126-L142

The fix is straightforward I think, in the section above if the directory is punctuated ("." or "..") make it absolute.

Can take care of it, but I think it looks a tad ugly if run from deep in the build folder:

```
$:~/unisonweb/unison/.stack-work/install/x86_64-linux/fd8751afd3efe7a4a550a8daa061e9a3c7a8fb0b2c155e4a5a01b36dc1720450/8.6.5/bin$ ./unison -codebase .. init
  ⚠️
  
  Initializing a new codebase in:
  /home/x/unisonweb/unison/.stack-work/install/x86_64-linux/fd8751afd3efe7a4a550a8daa061e9a3c7a8fb0b2c155e4a5a01b36dc1720450/8.6.5/bin.
```

**Comment by aryairani** [comment]
@pete-ts You can run `stack exec unison — -codebase p init` from the project root, you shouldn’t have to go deep into the build folder.
