### ISSUE TITLE
Archived definitions and namespaces

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1340]
Idea: for any namespace, a child namespace starting with `_archive` is lazily loaded and its results don't show up in `find`, etc, and its names are effectively invisible. A typical use case might be archiving past releases of a library.

You can still `cd` into the archive to bring it into memory, and you can `fork` or `move.namespace` an archived namespace to bring it back into the non-archived present namespace.

```
.> find
   
  frobnicate : Nat -> Nat

.> move.term frobnicate _archive.frobnicate
 
.> find
  
  Nothing here

.> cd _archive
._archive> find
  
  frobnicate : Nat -> Nat

._archive> copy frobnicate .

  Done

.> find

  frobnicate : Nat -> Nat 
```

So this would add / tweak a few commands:

* `cd` would have to be aware of this lazy loading, I don't think any other commands need editing
* (optional) `archive.{term,type,namespace} <arg>` - this moves the definition / namespace to `_archive` under the current path. So if you are in `.foo>`, then `archive.term` will add to `.foo._archive` - that is, archives can be nested.

### Implementation ideas

No repo format changes needed (child pointers can already be lazy, they just aren't in the current `Branch` type). 

So we maybe just make the `_children` field of `Branch0` an `Either (Branch m) (m (Branch m))` (probably create a new type for this) and then update the various `Branch` functions accordingly.

**Comment by aryairani** [comment]
@pchiusano Does this relate to old names?

**Comment by runarorama** [comment]
A couple of proposals on this:

1. Get rid of the idea of old names, and instead have "archived names", which we deprioritize in the pretty-print environment (and suffix with the hash in case of a name conflict).
2. Alias the `delete` command to `archive`. Or even just have `delete` move things to `_trash` instead of `_archive`. Maybe retain the current `delete` and call it `delete.forever` or something.

Also, it seems that this issue depends somewhat on #1348.

**Comment by aryairani** [comment]
@runarorama I like the `_trash` idea — I think it might interact nicely with whatever mechanism we use to borrow external names into a republished library that depends on them.

Question about proposal 1., what's the difference between "old names" and "archived names"?  Would "archived" be a flag on a name, or something different?

**Comment by pchiusano** [comment]
Phase 1: timeboxed (1 day) of design and (1 day) start sketch of an implementation just to reduce uncertainty.

**Comment by aryairani** [comment]
@pchiusano Is there an existing writeup that lays out the DX problem that archived namespaces is meant to solve? (I couldn't find on github or notion). If not, could we put our heads together about it and the goal output is a writeup about the problem?

**Comment by pchiusano** [comment]
There's not a good writeup. Here are some notes.

1. Currently, all names in your whole namespace tree are in scope and can be referenced by code in your scratch file or turned up by various commands like `find`. Typically you only want to be able to reference things that are relevant for the current thing you are working on. For instance, while working on a PR, you don't likely need or want the ability to reference symbols that exist in other PRs for the same project. Archived namespaces are a way of achieving this.
2. There's also just a basic need for archiving of things that are no longer being actively referenced or that have become read-only, like a merged/abandoned PR or an old release.
3. Putting aside the DX issues, there's performance issues with having the full root namespace tree in memory. In principle those performance issues could be addressed by a different representation of `Branch` and likely a revamp of the `Codebase` interface and a lot of `HandleInput`. However this is a rabbit hole I don't want to go down or make critical path.

A couple observations:

- We use suffix-based name resolution. Which is overall pretty great, but becomes rapidly less useful when there are multiple versions of things, all active at the same time in your tree. If we didn't do suffix-based name resolution, and if we also were careful in commands like `find` to not return results outside the current namespace (without some `find.global` variant or something), then that might alleviate the DX issues we have now - though it might have other rough edges.
- However, I still think you want somewhere to stash old releases and such, if for no other reason than performance.
- Another solution which I was very intrigued by is having everything outside the current namespace be invisible and not even loaded into memory. A bit like if all namespaces are archived. In this model, `cd` is used more infrequently, basically just for "switching branches", not for just zooming into a random subnamespace. I'd probably rename the command and do a few other things in conjunction:
  - The return of `namespace` blocks in scratch files, but they actually work well and you can even supply absolute names, as in `namespace .foo.bar where`
  - We should remember the last path you were at and when restarting UCM, `cd` there immediately, ideally without ever loading the root.
  - There's some retraining of users - anything you `cd` into has to be a self-contained thing, likely with a `lib` (which includes all dependencies) and a `src` subnamespace. If the namespace isn't self-contained, then you won't have names for any external dependencies. Whereas right now we often have dependencies existing in like a great aunt/uncle of the current namespace.

**Comment by ChrisPenner** [comment]
I took a crack at an initial spike on this [here](https://github.com/unisonweb/unison/compare/trunk...cp%2Farchived-namespaces). The spike just does the minimum necessary to avoid loading 'archived' namespaces, it doesn't actually support interacting with them.

I left a few `undefined`'s in the merge implementation but those should be easy to clean up once we decide how archived stuff should be merged.

For this attempt:
* Every branch starting with a `_` is considered "archived"
* Archived branches aren't loaded into memory on startup.

Overall, it was relatively easy to add and sped up the loading of my codebase by ~33%.

There are a few questions to answer before proceeding:

1. Do we want a specific "_archived" namespace, or is the `_` prefix better?
2. Which commands should consider archived namespaces vs not?
3. How do we handle archived namespaces in merges? Do we just merge them as normal?

(2) really affects how much work this is, if we only want archived names to show up in `ls`, and be able to `cd` into them it's probably fine, but if we add much more than than we'll need to thread an `m` through a lot of code that's currently pure, and that's going to be a pain. We also need to figure out what happens with the various `stepManyAt` commands, I think we'll need to thread the `m` through everywhere for that as well, which is a pain but probably not a deal-breaker.

All that said, threading the monad through is probably worthwhile anyways, since if we want to eventually get towards lazy-loading everything we'll need to do that anyways.
