### ISSUE TITLE
RFC: Unified APIs for distributed programming, durable state, fault-tolerance and live redeployments (v3)

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#144]
Updated version here:

https://github.com/unisonweb/unison/blob/master/docs/distributed-programming-rfc.markdown

Thanks especially to @atacratic for your detailed comments, also to @refried for feedback (which led to splitting up `Capability` and refining how `Durable` values get loaded / discovered).

Feeling better about this version than anything previous. (#142, #141)

**Comment by atacratic** [comment]
Looking good!  Comments from me...  (I've checked this supersedes all my previous comments so no need to look again at those.)

The fact that `Durable` is backed by `Box` and `Box` can be empty - that's going to mean pervasive matching on the Optional from `Box.read` - no type-level guarantee the box is non-empty.  Is too many Boxes like programming with NULL I wonder?  It also harms the ergonomics of building data structures with Durables.  But I don't have a better idea.  (Or maybe everyone maps their Optionals and it doesn't look too bad.)

Ah, you've switched to explicit syncing of Durables.  I did quite like the implicit version, if there were a way that Unison could make this fully transparent in a non-leaky but reasonably performant way.  But I can't see a way, if Durables might be megabytes in size (or transitively reference a million other Durables).  So I think it's the right call.  Fundamentally, big data transfers are an effect that the user will need to manage explicitly.

I wonder if it's still true that Durables are GCd on a per-node basis and can't contain cycles.  I guess the GC should have a minimum grace time to give remote nodes a chance to decide to sync.  

Observation: `load-from` makes it indistinguishable whether the node didn't have that `Durable` or whether it did but the `Box` was empty.

Inconsistency: your 'is somewhat analogous' bullet uses `Name` in `durable name blah : Name Number`, but your `cluster-peers` example doesn't use `Name` except in the comment.  The `: Name Number` variant makes more sense to me.

If the `durable name` declaration scheme gives you a `Box` which is durable under the covers, then I'm not sure what the status of the `Durable` type is.  Seems funny that some durable Boxes are called `Box` and some are called `Durable`.  I guess this is coming from not wanting to spawn variants of `Name`.  (If we had enough type system smarts then maybe `Name` could become something like `Local` and take a `* -> *` param, so you could write `Local Box a` and `Local Durable a`.  Or maybe you can do it without higher kinds (`Local (Box a)`).  I do quite like this idea, if it could work, as it also addresses my old concern about putting the per-node-ness in the name.)

`Durable.peers` - implementation sketch looks good!  I wonder if it's really right to expose the peer list to the user code, since (a) the user code is unlikely to have any special insight into which member to choose (since it doesn't have a chance to attach any metadata of its own to the nodes to remind itself what role they're each playing) and (b) the list is very implementation dependent (e.g. dependent on pruning strategies.)  The alternative would be that `Durable.load` is a primitive which walks along the peer list itself.

Is the run-time representation of a Durable going to include a hash of the value or a GUID?  (or neither)

I like the way foreign functions are no longer kept in mutable cells.

**Comment by atacratic** [comment]
I was thinking about how you'd be able to monitor what each Unison node was up to and why.  Also about tracing.  I think we could do with a primitive to attach some data to a thread that is then 'infectious' - it sticks around over transfers and forks.  You could then use that for (say) a GUID to help with distributed tracing à la [zipkin](http://zipkin.io/); or accounting data like usernames/accounts to help understand where your node resource is going; or more generally for user-interfaces allowing reflection of objects that exist in the Unison runtime.  Maybe some GUI could then show the operator why they have so much Unison state on disk - they can see the accounting Context of the caretaker tasks that have references to it.  (I imagine there's another view in which accounting for that sort of thing is kept at Node or Sandbox scope.  But does that really work if your Node is receiving work from lots of different sources and lots of different reasons?)

Maybe an API would look like this:

```haskell
-- Create a `Context`, which is a key that can be used to store 
-- context information in a running Task.
Context.make : ∀ a . Remote (Context a)  -- (assign GUID)

-- Set or update the value associated with a given Context key 
-- in the current Task.  The context is preserved across a 
-- Remote.transfer.  The context is cloned into any Tasks 
-- that are spawned from this one using Remote.fork, Remote.spawn, 
-- or Remote.spawn-sandboxed.  (Updates in to the context in subtasks
-- do not affect the Context in the original parent Task.)
-- The Context can be non-empty even for fresh 'root' tasks 
-- initiated outside Unison.  For example, a webserver might handle a
-- user's HTTP request by initiating a Unison Task, and populate a 
-- 'user' entry in that Task's Context.  This entry is then associated
-- with all Tasks which that request (transitively) spawns within Unison.
Context.update : ∀ a . Context a -> (Optional a -> a) -> Remote (Unit)

-- Read the Context value associated with some key.
Context.read : ∀ a . Context a -> Remote (Optional a)
```

Here's an argument for this to be a primitive:  suppose you had a hybrid setup with a mix of Unison and REST services (or whatever), with requests passing between the two.  Say you want distributed tracing that works regardless.  You will need to pipe trace IDs through Unison so it can get from one REST hop to the next.  That says you need a way of injecting metadata on Tasks you initiate outside Unison, and recovering it later when Unison kicks back out via some effectful Foreign API.  And I think you want to be able to keep it hidden from the Unison user-land code if you want to, simply by making your own (non-well-known) Context key.  That speaks against explicitly threading this sort of stuff through forks/spawns in Unison user-land code (as well as the fact that you'd want it to work even for Unison code that does not play ball by doing that explicit threading.)

I know new primitives need to really pay their way...

But while I'm about it here's another one.  How about having:

```haskell
-- Sleep the current computation until the node next restarts (if it 
-- ever does.)  Node restart is an event in which all running computations
-- (except ones running sleep-until-restart) and all ephemeral state are lost.
Remote.sleep-until-restart : Remote Unit

-- [comment should have xref to definition of ephemeral state: all Boxes, all recollection 
-- on this node of any ephemeral Names.. what else?]  
-- [?? do Durables on the stack of the slept thread get synced?
-- or do we make their peers state Durable?]
```

Either there's some mechanism like this within Unison for registering code to run after a restart, or we say that all initial Task invocations originate outside Unison and it's the runtime environment's job to kick stuff off again after a reboot.  I don't see any strong arguments either way yet, but I rather like the sleep-until-restart idea.  Restart is anyway a concern on this API (with ephemeral vs durables) so seems to make sense to have it represented on the computational side of the API as well as the storage side.  Also plays nicely with 'Durables are GCd' - might make a lot of sense for your computations acting as caretakers for your root Durables to be the same as your bootstrap initiator thread.

**Comment by pchiusano** [comment]
@atracratic haven't gotten a chance to rely in detail yet but I think there is some confusion here - Durable (the uppercase type) and Box have little to do with each other. You have have a lowercase durable name, which is a dynamically bound Box whose state survives restarts, but that is unrelated. (Said box might contain a Durable or any other value)

Maybe I should use a different term for one or the other...

**Comment by atacratic** [comment]
@pchiusano thanks - I will digest that later.

A quick one on my `Remote.sleep-until-restart` idea.  I think it doesn't actually work as a plan for bootstrap computations - there's always going to be a window after restart where the computation is not in this special 'durable sleep' mode and so you're not reboot-protected.

I'm now thinking
```haskell
-- Make this computation 'durable'.  After a node restart it will resume from this point.  
-- If this is called multiple times then only the last call matters.
Remote.set-restart-point : Remote Unit

-- Remove durability on this computation.  It will not resume after a node restart.  
Remote.clear-restart-point : Remote Unit
```

I realise durable continuations is a non-trivial thing to be suggesting throwing in...  Note that I'm not proposing a full call/cc system in which continuations can be captured in arbitrary variables.

**Comment by atacratic** [comment]
(have now updated previous comment following the Durable/Box clarification)

**Comment by atacratic** [comment]
Hmm, `Context` from [above](https://github.com/unisonweb/unison/issues/144#issuecomment-282170010) wasn't a very good suggestion was it?  Heavyweight, clearly not fundamental to distributed computing, obscure use case.  I think I was making the mistake of writing an API I might want to code to directly, rather than working out the minimum primitive footprint to support an implementation of that API.

So how about this instead?

```haskell
-- Get the current task, that is, the one from which Task.this is being called.
Task.this : Remote Task

-- Get the task that created the given one (or None if it
-- was created from outside Unison.)
Task.parent : Task -> Remote (Optional Task)
```

If you have `Task.this` and `Task.parent`, you could implement something like `Context` in library code (as a mutable map keyed on Task - assuming `Task` can be used as the key of a map).

**Comment by pchiusano** [comment]
Task.this was something I considered... I think it's reasonable, though not
sure how useful it is. (I'd call it Task.current)

Not sure about Task.parent. IMO it's giving too much power to the child
tasks - a child task should not be able to stop the parent task... think
about what that means. In theory you could split Task into two types - the
thing that you supervise, and the thing that you pass to Task.stop. Then
`Task.parent` just returns the thing you can supervise. Again, not sure how
useful it is.

Another thing you could do is use the node's Sandbox to control access to
Task.parent... also not a big fan of this approach either.

**Comment by atacratic** [comment]
Omitting Task.parent is not enough to stop people writing child tasks that kill their parents - the parent could write its Task into a Box shared with the child, or simply pass it as an argument when it forks the child, or people might write themselves a discovery service which tasks write themselves into.  I agree that having access-to-parent as an API seems to invite it more.  But it's not as if we're losing some kind of parametricity style guarantee.

Also, why shouldn't child tasks kill their parents?  Could be quite a useful pattern.  Say a parent task is an umbrella over a bunch of tasks implementing some service.  One thing the parent starts is a 'watch for the signal to kill the service' task.  Quite convenient for that child then to kill the whole service by killing the parent.  Don't see why it's better if we make people signal to the parent and the parent kill itself. 

Absolutely if a child task kills its parent, that still in turn kills the child and everything else under the parent.  

The thing I'm imagining implementing with Task.parent is something that acts as a mutable `Map Task (Set a)`, where tasks inherit the set their parent had, but can then diverge.  And I want it to work without instrumenting all `fork` calls with extra stuff.  Because I think this helps with accounting and distributed tracing.

**Comment by pchiusano** [comment]
Sure, I was just saying I like the default that child tasks do not have the
ability to kill the parent, unless the parent does something very explicit
to allow it. This is a very useful guarantee for reasoning purposes. It
means you can contain and limit the damage of tasks that are opaque to you
that you are running. They can fail, but you the parent are always in
charge of how that failure should be handled or propagated. I don't think
there's any loss of expressiveness with this choice, it's just that there's
a certain default for where this info is specified by the programmer.

We don't totally know what programming will be like with these
primitives... but I don't want to add primitives just because we can
imagine some possible usage that would be convenient if some primitive
existed. It's hard to know where to stop... 😀 Instead I'd rather keep the
primitives as minimal as possible for now. Then we can revisit as we get
more experience and it becomes obvious what a better formulation would be
or where there's an expressiveness gap with existing primitives.

**Comment by atacratic** [comment]
Ah yes good point, that is a very useful guarantee.  I'd not clocked that the parent deciding to give the child a copy of the parent's Task handle is a very different thing to the child being able to go and get its parents handle itself.

And you are doing a good job of defending the minimal/conservative approach! :+1:

**Comment by pchiusano** [comment]
archiving this.. will be getting back to this stuff soon enough though
