### ISSUE TITLE
Q<newbie>: how to deploy actual executables

### ISSUE THREAD

**Issue by yatesco** [unisonweb/unison#1483]
Hi - I've read the doc, but something just isn't clicking - once I have written an app, how do I actually ship _that app_ (i.e. not unison itself but my app) to Windows/Linux/MacOS etc.?

Will Unison always be interpreted and require a Unison runtime?

Thanks :-)

**Comment by orvi** [comment]
Had the same question myself.
I found [this paragraph](https://www.unisonweb.org/2020/03/12/march-update/#whats-next) so I'm guessing it's still work in progress

**Comment by pchiusano** [comment]
Good question. Unison will always require a runtime that does some form of compilation or JIT. Why is that?

* Unison is garbage collected so it needs a runtime like any other garbage collected language. 
* Distributed execution inherently requires the ability to compile code on the fly, since computations can be moved between nodes during execution, and not all nodes are necessarily even running the same operating system. Thus, there needs to be some representation of Unison code which the runtime knows how to JIT or at least compile to some low-level efficiently interpretable form.

That said, since the runtime is fairly small, it does seem possible to package both the runtime that up as a single executable though, as other languages do (Haskell for instance).

In the meantime, see `ucm help` for options on running Unison programs in batch mode rather than the interactive loop.
