### ISSUE TITLE
Crash when pulling

### ISSUE THREAD

**Issue by thoradam** [unisonweb/unison#1502]
On `ucm` version `release/M1l`:

```
.> pull https://github.com/zenhack/unison-parsers.git parsers
ucm: 😞 I was trying to copy a term fromcodebase...                        
        /Users/thoradam/.unison/v1/terms/#lj5rkikgh4co2alhitrghobej29gb5gojagk3vistb5uihpfksv9jo4g3gmgeh2ilm6q4tvkfqi8mcv7ntp680jp57denlpmddu062o/compiled.ub
but there was nothing there.
CallStack (from HasCallStack):
  error, called at src/Unison/Codebase/FileCodebase/Reserialize.hs:125:16 in unison-parser-typechecker-0.1-1n4fxMa6V58C0oQoOr6uen:Unison.Codebase.FileCodebase.Reserialize
```
@aryairani [looked into it](https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1588341442055500?thread_ts=1588338636.055100&cid=CLUNF0J5S):
> There was a bug in ucm at the time that that repo (zenhack/unison-parsers) was created, which caused it to be created incompletely.

**Comment by aryairani** [comment]
We'll want to create a better error message.

**Comment by Ninlives** [comment]
Still crash, any progress or workaround?

**Comment by pchiusano** [comment]
@Ninlives I don't think there's much we can do about the repo that's missing that hash (it's literally just missing a definition), but I think @aryairani's new codebase format he's working on will have much better reporting and handling of this sort of thing.

I guess there's a question about whether this condition should just get logged with a warning or if it should stop the `pull` process.

My feeling is that the ideal behavior would be to, rather than crash, skip any definition that is missing or that depends on a missing definition, and then nicely report all those missing definitions at the end.

**Comment by aryairani** [comment]
@Ninlives This ticket was from an older release, M1l, and I believe (80% confidence) the latest binary release, M1m, no longer crashes for this particular reason.

The next release should handle this even more kindly.

**Comment by Ninlives** [comment]
@pchiusano @aryairani thanks for your response, and yes the M1m version works fine. For nix users: until the version in nixpkgs is updated, you can install the more recent version form [unision-nix](https://github.com/ceedubs/unison-nix)
