### ISSUE TITLE
stepManyAt0 should reflect the order of input actions

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1552]
There was a possibly-unwritten expectation of `stepManyAt0` that it should produce the same resulting namespace as if the actions had been executed sequentially.

Breaking this resulted in #1430 / #1495 (and possibly undiscovered others).

I suspect this was a regression in #1225/#1333; e.g. working from the children to the root causes these actions to happen out of the expected order:

```
MoveBranchI Nothing dest -> do
  b <- use root
  stepManyAt [ (Path.empty, const Branch.empty0)
             , BranchUtil.makeSetBranch (resolveSplit' dest) b ]
  success
```

and the root gets wiped as the last step instead of the first step.

Maybe we can't generally consolidate everything into a single action, especially if individual actions are allowed to change things deeper than their rooted path, but hopefully we can do something to minimize the number.

**Comment by aryairani** [comment]
A transcript to reproduce #1495:
    ```ucm
    .> alias.term ##Nat.+ .Nat.+
    .> ls
    .> move.namespace Nat Nat.operators
    .> ls
    ```

**Comment by aryairani** [comment]
I ran into this again today, and it seems pretty bad as it somewhat throws away information.  I'm thinking we should reimplement #1333 that introduced the issue. Maybe we just apply the actions to branches in memory, then squash them before applying them to the user's history. That should minimize the number of visible nodes.

**Comment by pchiusano** [comment]
Yeah, good idea. You could, just within `stepManyAt`: 

1. Build a `Map Path Hash` of the hash at each subpath in the tree.
2. Apply the updates sequentially in the order they are given.
3. Squash the updates so that each path has at most one hash after the hashes established in 1.
4. Return the squashed branch

I don't think there's anything more efficient you can do if the updates are just opaque functions - you have no idea if an update at path A will commute with an update at path A.B.

One other possible optimization - updates at path A.B will commute with updates at A.B2, since they are updating unrelated parts of the tree. More generally, updates commute as long as the two updates don't have a subpath relationship.

**Comment by aryairani** [comment]
Another alternative would be to use some symbolic primitive DSL instead of opaque functions, letting all the paths be inspectable until they're finally applied, but squashing might be less work.

**Comment by aryairani** [comment]
@ChrisPenner This is another good short one. LMK if any questions. Basically update `Branch.stepManyAt0M` to just run all of the actions in order, and then as a final step, squash changes to a child `Branch`es into a single step before returning.

**Comment by ChrisPenner** [comment]
Sounds good! Thanks for picking out some good issues for me 👍🏼
