### ISSUE TITLE
add mac builds to CI

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1616]
We want to avoid surprises like the mac build fail in #1611 / #1615.

Maybe useful references:
* https://docs.travis-ci.com/user/multi-os/
* https://docs.travis-ci.com/user/reference/osx/
* #1614 "Add windows to CI"

**Comment by mitchellwrosen** [comment]
Btw, @aryairani, any opinions on GitHub Actions? I was messing around with them the other week on `mitchell/github-actions`, you can see the results here. https://github.com/unisonweb/unison/actions

Mostly, I was interested in the better caching - you can have "fallback" keys, so (for example) commit `A'` can reuse commit `A`'s build artifacts of local packages (not just cached dependencies).

The `ci.yaml` file in that branch isn't done, I think I've learned a couple things since then, but adding windows/mac support is easy. (I'm sure it's easy in Travis, too).

**Comment by sharno** [comment]
@mitchellwrosen Actuall Actions might be a good solution for Windows as well, Travis has an experimental Windows support and it's giving me a weird message in #1614 
> Automatic restarts limited: Please try restarting this job later or contact support@travis-ci.com.

**Comment by aryairani** [comment]
@mitchellwrosen No strong opinion yet.  I'd be interested in understanding the caching thing better?

Side note: I'm not sure it's a good idea to cache `.stack-work`, as it can sometimes become busted, requiring a `stack clean`.  Caching `~/.stack` seems safe, thankfully.
