### ISSUE TITLE
display.to persistently changes scratch file

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#1634]
Using the `display.to` `ucm` command appears to have a stateful effect on the default scratch file. See the following session where `edit` uses `scratch.u`, but after I run `display.to doc.md Boolean.and`, a subsequent `edit` uses `doc.md` instead of `scratch.u`.

```
❯ ucm

   _____     _
  |  |  |___|_|___ ___ ___
  |  |  |   | |_ -| . |   |
  |_____|_|_|_|___|___|_|_|

  Welcome to Unison!

  You are running version: release/M1m

  I'm currently watching for changes to .u files under ~

  Type help to get help. 😎

.>

  I loaded scratch.u and didn't find anything.

.> cd _base
._base> edit Boolean.and

  ☝️

  I added these definitions to the top of /Users/cody/scratch.u

    Boolean.and : Boolean -> Boolean -> Boolean
    Boolean.and x y = x && y

  You can edit them there, then do `update` to replace the definitions currently in this namespace.

._base>
._base> display.to doc.md Boolean.and.doc

  ☝️

  I added this to the top of /Users/cody/doc.md

    Boolean 'and'. Note that this function cannot short-circuit, as it's strict in both arguments. For
    a short-cirquiting version, use the built-in syntax `&&`.

._base> edit Boolean.and

  ☝️

  I added these definitions to the top of /Users/cody/doc.md

    Boolean.and : Boolean -> Boolean -> Boolean
    Boolean.and x y = x && y

  You can edit them there, then do `update` to replace the definitions currently in this namespace.
```

**Comment by pchiusano** [comment]
That's unfortunate, thanks for reporting. I think the fix for this one is as simple as just deleting these lines in `doDisplay` -

https://github.com/unisonweb/unison/blob/trunk/parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs#L1838-L1841

The thinking there was just wrong... for `edit` command that behavior makes sense, but for displaying to a markdown file, that won't actually trigger UCM since it only looks for `.u` files anyway.

Want to do a PR @ceedubs? I think manual testing of the fix is fine for this one, as long as all the other tests still pass.
