### ISSUE TITLE
unknown data reference

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1663]
In 67bf4aed, evaluating this expression

```
> handle 1 with cases { a } -> a
```

gives
```
unison: unknown data reference: PR {matches = [EffectPure Var], guard = Nothing, body = Var User "a"}
  error, called at src/Unison/Runtime/Pattern.hs:550:18
```

/cc @dolio

**Comment by dolio** [comment]
I see. This actually makes me realize that there is a second way some assumptions I made can go wrong. I think if you do:

    cases
      { a } -> ...
      { A1.e -> k } -> ...
      { A2.e -> k } -> ...

you will only get `A1` matches, because I look for a single reference for the type of a pattern. However, ability patterns match against 0 or more referenced types.

I'll work out a fix for this, and it'll probably cause a compilation issue further down the line due to only having a pure case, but I think that should be easy to check for and just turn into `let a = 1 in a` or something.

**Comment by aryairani** [comment]
works now

```
    1 | > handle 1 with cases { a } -> a
          ⧩
          1
```
