### ISSUE TITLE
Round trip fails for parenthesised let block + operator

### ISSUE THREAD

**Issue by lrworth** [unisonweb/unison#1778]
`ucm version: release/M1m`

Place this code in scratch.u:
```
x = '(let
  abort
  0) |> Abort.toOptional
```

Then
```
>. update
>. edit x
```
prepends to scratch.u:
```
x : Optional Nat
x =
  'let
    abort
    0 |> toOptional
```
which is different and doesn't typecheck.

**Comment by pchiusano** [comment]
Thanks for reporting. @atacratic is this something obvious?

**Comment by atacratic** [comment]
@pchiusano There's an easy fix (change 12 to 10 around line 334 of TermPrinter.hs) that also causes us to add brackets in the following case.  So `'let` doesn't look so tidy any more.

```
  a : 'Nat
  a =
    '(let
      foo = 1
      2)
```

Do you want that fix?

Avoiding this side-effect is a bit more tricky because it means we need to step out of adding brackets purely on the basis of ambient precedence.  ('Explanation of precedence handling' at the top of TermPrinter.hs).

**Comment by pchiusano** [comment]
Blarg, accidentally hit close with comment before I was even done. Updating.

@atacratic I was thinking it's possible to do just with ambient precedence, analogous to what's done with binary operators depending on their associativity, although I think you are currently doing binary operators in a simpler way with a pattern that pulls out a full chain of operators so you don't have to worry about nesting.

For example, when you have `a + b + c + d`, where `+` is a left associative operator with precedence (say) 5, so that technically parses as `((a + b) + c) + d`. Suppose you are at the root expression, and you are moving to the `((a+b) + c)` - for this, you keep the ambient precedence at 5 (equal to the precedence of `+`). But for the _right_ side of the `+`, the `+ d`, you bump the precedence to 6 when printing the `d`. In this way, if you have `(a + b + c) + (d + 1)`, the `d + 1` correctly gets parens, but `a + b + c` correctly does not.

If you have a right associative operator, you bump the precendence by 1 when looking at the _left_ argument.

So I'm imagining if I have:

```Haskell
foo bar =
  x + y + let
    bar
    qux bar + quaffle
```

Then no parentheses are needed around the `let` as it's the rightmost argument. But if the `let` is nested in any position other than the rightmost one as in the original report, then it needs parens. It would definitely be possible to handle this with a separate reader-style parameter "is rightmost" but I wondered if it could also be done just with the precedence (might require rejiggering the existing precedence levels).
