### ISSUE TITLE
Can't unify an ability variable with {}

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#1779]
Unison doesn't seem to want to match the type `'{S (R g), g} ()` with `'{S (R {})} ()` in the definition of `run'` below, but I think it should?

```haskell
unique ability S a where
  s : a

unique type R g = R ('{g} ())

run : '{S (R g), g} ()
run _ = todo ()

run' : '{S (R {})} ()
run' = run

--  The expression in red  needs these abilities: {S (R {}), }, but this 
--  location only has access to the {S (R {})} ability,
--
--     10 | run' = run
```

(trunk@b586abb)

**Comment by pchiusano** [comment]
@dolio I might have some ideas on this, something in ability checking

Thanks for report @atacratic

**Comment by dolio** [comment]
It doesn't seem like it's failing to unify `g` with `{}`, since it's printing out that it needs access to `S (R {})`. I think what might be happening is that the first part of the ability check does that unification, but then `{}` ends up in the ability check list (which is normally pre-flattened). Then that check falls through. At least, I assume that's what the need for `{S (R {}), }` means. I.E. the nested `{}` is showing up as that blank.

It might be pretty easy to cover this case.
