### ISSUE TITLE
(feature request) diagnostic tooling for determining "self-containedness" of a namespace

### ISSUE THREAD

**Issue by samgqroberts** [unisonweb/unison#1802]
In general, I'd like to know when any terms in a namespace N refer to terms or types that don't have current names within N.

This can happen when:
1. A term / type has a current name outside of N
2. A term / type has an old name within N
3. A term / type does not have a name in the Codebase at all.

In each of these cases, I want to know about it and deal with it. My current strategy for doing this involves `edit`ing out all the terms in a namespace and looking for either namespace qualifications in references (sometimes indicative of case 1) or hash qualifications (indicative of case 2 or 3). 

I believe a "healthy" top-level branch, like a library's `trunk` branch, should be "self-contained" in this way. I'm often trying to clean up `pr` branches using this clunky strategy before merging back to `trunk`. 

The `todo` command provides some solution for case 1 and 2, but that has two weaknesses that I've observed. One is that this requires that the local `patch` has tracked the changes that landed your namespace in this state, which isn't always guaranteed. I'm not 100% on patch management, but I believe if pushing / pulling work may affect this?

The second weakness is that the `todo` command seems to miss work done in sub-namespaces. If I have the following structure...
```
trunk/
    Bar (term that refers to ns.Foo)
    ns/
        Foo (unique type)
```
...and I perform the following procedure...
1. `fork trunk prs.doit`
2. `cd prs.doit.ns` (work inside `ns` instead of at the `prs.doit` level)
3. update `Foo` (could just be re-loading the scratch file with the `unique type Foo` declaration`, since that would generate a new hash)

...then `prs.doit.Bar` will now refer to `trunk.ns.Foo` and the `todo` command will sadly not show anything needed to be done when run in either `prs.doit` or `prs.doit.ns`. Perhaps working in sub-directories is not canonical or something, but I'm doing that regularly during development. 

I've only encountered case 3 when pulling another developer's library into my Codebase. I believe this happens when the external library has a self-containedness issue as described here, leading my Codebase to not have an old or unpulled (because it was out of the pulled namespace) name for some term or type. 

Perhaps after having some diagnostic tooling for this, we could then dream about automated refactoring tooling for what the diagnostic catches, but for now I'd be happy to do the latter manually as long as I can efficiently and confidently know the breadth of issues I need to deal with in a namespace.

Thanks as always!

**Comment by aryairani** [comment]
There's a couple of different things in here, but: Yes we should definitely have a command for determining the "self-containedness" of a namespace.

> I believe a "healthy" top-level branch, like a library's trunk branch, should be "self-contained" in this way.

Yes.

> Perhaps working in sub-directories is not canonical or something, but I'm doing that regularly during development.

It's not, right now, and this causes problems; we need to make it easier for folks to zoom into sub-directories without losing track of the project level they're trying ultimately to develop at.

> I'm not 100% on patch management, but I believe if pushing / pulling work may affect this?

Nobody is 100% on patch management yet. 😅  But we will make it clearer / easier.

At any rate, let's add a command that lists the names/hashes of any definitions referenced with the current/supplied namespace which aren't named within it.   Each should probably also list the definitions within the namespace that reference it.

```
1. .mylib.function1
2. #affs4d
```

I'm undecided on how to display / number the referents, proposals are welcome.

**Comment by aryairani** [comment]
@samgqroberts Would you want to take a stab at this? :)

Create a command `debug.check-self-contained` or `namespace.check-self-contained` that takes an optional path (defaults to the current path) and reports either that it's self contained, or lists the dependencies that are missing, along with the definitions present that depend on them.

**Comment by aryairani** [comment]
@ChrisPenner This would be a super valuable easy-ish one; I'm going to assign you. :) Ping me w/ any questions.

**Comment by ChrisPenner** [comment]
Some notes from a chat about this:

* We have a bit of a complication in the sense that our dependents-index only captures dependencies at the granularity of a Reference (e.g. component and position) but not at the level of Referent (e.g. component and position and constructor).
* This means that there is no _fast_ way to determine which Referents a term depends on
* Our namespace contained-ness check isn't complete unless we check for individual constructors, because it is possible (but unlikely) that your namespace has a name for a type, e.g. `Maybe` but doesn't have a name for a constructor, e.g. `Nothing`. In this case, you're missing a name for something you depend on, but I can't detect it using the dependents index.
* We can determine the constructor dependencies, but only by hydrating terms into their ABT, then manually crawling that ABT searching for Referents with constructor IDs.
* Which unfortunately is pretty inelegant, and likely to be much slower than simply querying a table.

Options for moving forward:
1. Only detect dependencies on Type Decls, not constructors, this will give us the right answer in 99% of cases, but is still technically incorrect and could lead to mis-information
2. Do the manual work of hydrating all the terms and crawling their referents, leading to the correct answer but with a slow implementation
3. Expand our dependencies table to include optional Constructor-ids (as described in https://github.com/unisonweb/unison/issues/2545); this would require rebuilding the index.

**Comment by ChrisPenner** [comment]
I took a few minutes to look into what it'd take to run the migration to update the dependents index to include ConstructorIds in and here's what I came up with:

1. DB schema update to add the constructor field to the dependents index. This would add a Nullable constructor ID for both the dependent and dependency. Since it's nullable, we can add it to the existing table without needing to worry about breaking table constraints.
2. Edit U.Util.Term.dependencies to return another tuple field of (ref, Maybe ConstructorId) for constructor refs.
3. Edit addToDependentsIndex to permit the `Maybe ConstructorId`
4. Write a simple Sync which deletes the dependents index, then round-trips every term object through load -> save, or copy the logic for just the dependencies index to avoid extra work.

Which seems pretty simple I think.

After that, we'd need to update all the `getDependency*` and `getDependents*` query to use Referent's where applicable instead of references, and of course update everything upstream of that.

Am I missing anything here?

A side-benefit of this is that it might also make the `dependents`/`dependencies` command aware of constructors. This might actually end up being too noisy, but it's easy to simply ignore the constructor IDs in that implementation if we like.

**Comment by aryairani** [comment]
Following on to Slack conversation from earlier today, I'm very confident that the actual dependency lookup implementation for (2) will not take long at all to write.  The more time-consuming part is creating the `Input`, `Output`, and `OutputMessage` pieces, and these would be shared by approaches (2) and (3).

Let's do (2) first, and then we can slot a "faster `referent-dependencies` lookup" feature into an appropriate spot in the work heap.

**Comment by ChrisPenner** [comment]
@aryairani  I implemented most of 2 this afternoon haha, should have a PR tomorrow if I have a bit more time 😄

**Comment by aryairani** [comment]
@ChrisPenner Awesome! Let me know if you want to pair on the dependency lookups.

**Comment by ChrisPenner** [comment]
@aryairani  I ended up doing a slightly more conservative version since it was easiest, so if your namespace depends on a type or constructor, it will tell you if any of that type's constructors are unnamed in your namespace, even if a specific constructor is unused, but I think that's a perfectly reasonable thing to do for now and should be sufficient for 99.999% of cases, and I'd say encourages "Best practices" anyhow

I can show you tomorrow 😄
