### ISSUE TITLE
Decompilation in new runtime reverses output of constructors?

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1844]
See this minimized example: https://github.com/unisonweb/unison/issues/1844#issuecomment-801344682

----

Original report, disregard -

The new runtime seems to mix up bound variables during pattern matching. The issue does not arise with the old runtime.

```Haskell
type One a m = One a m 
type Deep l m r x = Deep l m r x
unique type Z = Z

snoc f k aN mN = 
  go k aN mN = match k with 
    One a0 m0 -> Deep (One a0 m0) [] (One aN mN) (f 0 m0 mN)
  go k aN mN

> snoc (_ _ _ -> Z) (One 1 Z) 2 Z
```

Yields: 

```
    12 | > snoc (_ _ _ -> Z) (One 1 Z) 2 Z
           ⧩
           Deep Z (Cons 2 Z) [] (Cons 1 Z)
```

The example above is the result of some minimization - it isn't triggered in the obvious cases, and I'm not sure what's unique about this case.

**Comment by pchiusano** [comment]
Here's a bit simpler example: 

```Haskell
type One a = One a 
unique type Woot a b c = Woot a b c

snoc k aN = 
  go k aN = match k with 
    One a0 -> Woot (One a0) (One aN) 99
  go k aN

unique type Z = Z

> snoc (One 1) 2

---
    12 | > snoc (One 1) 2
           ⧩
           Woot 99 (One 2) (One 1)
```

**Comment by pchiusano** [comment]
And simpler:

```Haskell
type One a = One a 
unique type Woot a b c = Woot a b c
unique type Z = Z

snoc k aN = match k with 
  One a0 -> Woot (One a0) (One aN) 99
  -- One a0 -> [a0,aN] -- returns [1, 2] as expected
  -- One a0 -> (a0, aN) -- returns (1,2) as expected

> snoc (One 1) 2 -- produces Woot 99 (One 2) (One 1)
```

This makes me think the constructor arguments are just being reversed when the term is decompiled.

```Haskell
snoc k aN = match k with 
  One a0 -> Woot (One a0) (One aN) 99

gow = cases
  Woot _ _ w -> w

> gow (snoc (One 1) 2) -- produces 99 as expected
```

**Comment by dolio** [comment]
Does this only happen for data types with 3 or more fields?

There are special cases for up to size 2 constructors, but others are just stored in a similar way as the stack (for easy dumping onto the stack), and thinking about it briefly, I do think they'd be reversed in that scenario. The culprit is a pattern alias `DataC` (or rather, the functions it uses) which gets used in the decompilation, so that it doesn't have to care about all the special cases.

There are other uses of `DataC`, but the only one where the difference would be visible is decompilation. (De)serialization uses it, but it goes through the pattern alias in both cases, so things get swapped in both directions. Technically if you got into a situation where you had a non-special-case value of size 2, it would end up swapped, but I don't know how that would happen.

**Comment by pchiusano** [comment]
@dolio yes, it only happens for constructors with more than 2 elements!

**Comment by dolio** [comment]
Okay. Should be easy to fix, then.
