### ISSUE TITLE
Pretty-printer megaticket: fix bugs which produce weird or unparseable code

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1898]
Collecting various pretty-printing bugs here. Feel free to leave a comment with other examples, or with a refinement of any of the existing examples.

- [ ] As noted in https://github.com/unisonweb/unison/pull/1897 lists that span multiple lines get weird treatment. See doc.output.md for an example. I think it still parses fine but it looks pretty weird.
- [ ] Revisit breaking of doc blocks. Again look at doc.output.md.
- [ ] `f x y` should render as `f x y` or 

```
f 
  x 
  y
```

But I think I've seen it render as:

```
f
x
y
```

which will not even parse. I don't have a minimal example of this one though, and this specific example works as expected I think.

**Comment by rlmark** [comment]
Adding to the pretty printer mega ticket: 

Stringing together multiple boolean expressions: 

```
myMultipleBooleanExpression = let
  use Universal
  ("case1" == "a red wheel barrow") && ("case2" == "upon") && ("case3" == "glazed with rain") && ("case4" == "water")
```

comes out of the UCM as: 

```
myMultipleBooleanExpression : Boolean
myMultipleBooleanExpression =
  use Universal ==
  ((("case1" == "a red wheel barrow") && ("case2" == "upon"))
  &&
  ("case3" == "glazed with rain"))
  &&
  ("case4" == "water")
```

Which fails to parse. It looks like there's some indentation issues

**Comment by hojberg** [comment]
Here's a few more:

* https://github.com/unisonweb/unison/issues/2260
* https://github.com/unisonweb/unison/issues/2224
* https://github.com/unisonweb/unison/issues/2165
* https://github.com/unisonweb/unison/issues/1035

**Comment by runarorama** [comment]
Some issues that collide with this:

* Almost no `Doc.Deprecated` documentation in Base can be parsed correctly after pretty-printing. Rather than hack this in the pretty-printer, we should just convert all docs to the new type. Tracked in https://github.com/unisonweb/base/issues/39
* A number of terms in Base have an overly general ability type, which interacts with general ability inference goofiness and causes a need for additional type annotations: https://github.com/unisonweb/unison/issues/1271
* Those terms sometimes can't be updated because the inferred type matches the new type signature. https://github.com/unisonweb/unison/issues/2276
