### ISSUE TITLE
Merging unrelated histories is slow

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#1943]
[base.md](https://github.com/unisonweb/unison/files/6473429/base.md)
Merging `builtin` into `base` takes >5 minutes on a modest laptop and otherwise new codebase.

See attached transcript.

**Comment by runarorama** [comment]
[base.md](https://github.com/unisonweb/unison/files/6473426/base.md)

**Comment by pchiusano** [comment]
Update on this:

@aryairani and I are working in https://github.com/unisonweb/unison/pull/1948 on updating things so that the LCA calculation used by merge is done by SQLite rather by Haskell in memory. So rather than loading all those intermediate points in history into memory, it'll just compute the LCA in the database and load that one needed point in history.

That should make merge a lot snappier.
