### ISSUE TITLE
`docs` command fails to render documentation in the UCM with error message and unexpected exit 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#1970]
On a recent pull of trunk: `version: devel/M1m-1350-g878a8734b` I have noticed that UCM crashes when attempting to render docs: 

Sample code in a scratch file: 

```
{{this is a doc associated with a value}}
myValue3 = "I am a string"
```

calling `docs myValue3` will cause UCM to exit with the following error: 
```
.playground> docs myValue
unison2.2: PE Lit
  AnnotatedText (fromList [Segment {segment = "Unknown term reference: #4522d", annotation = Nothing}])
```

Adding the value to the codebase does not appear to have an effect on the error.

**Comment by dolio** [comment]
I was able to temporarily reproduce this. However, I can't starting from scratch now. Here's the steps I did:

1. Ran `builtins.mergeio` so that I could do the doc thing above
2. Added the values to my codebase
3. Saw that it worked
4. Realized that my repo was out of date, so pulled trunk
5. Ran `docs myValue3` and it crashed

However, now that I'm up to date, if I restart by blasting my `.unison` directory and doing `ucm init`, the docs work again. So it seems like something in the last 30-odd commits might have caused a hash to change or something? Whatever was `#4522d`, which I imagine is somehow related to docs.

I tried typing in some other examples, and the crash always complained about `#4522d`.

Perhaps @pchiusano has some insight?

**Comment by pchiusano** [comment]
Okay, I get what's going on here. Some context is that the `display` command calls a Unison function defined in `IOSource.hs` to do doc rendering.

The `display` command hardcodes the hash of the Unison function it uses for rendering docs based on whatever is in the latest `IOSource.hs`. This is okay, except there's no guarantee that hash exists in the codebase unless the user has done `builtins.mergeio` _with the current version of `IOSource.hs`_. The implementation of doc rendering changed slightly recently, resulting in a different hash, which means you'd need to do `builtins.mergeio` to obtain the new hash for the doc rendering function.

Anyway, we can fix just by making base consistent with the latest `IOSource`, and a more robust fix would be to just make sure the `display` command gets access to all the definitions in `IOSource` if needed. You don't even need the names for the stuff in `IOSource`, just the mapping from hashes to terms. 

I'll look into how easy this is.

**Comment by pchiusano** [comment]
This can be worked around by doing another `builtins.mergeio` to add the latest doc rendering functions to your codebase.
