### ISSUE TITLE
`dependents` ucm command has loop problem when called with hash from old IO

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2003]
This is probably an unlikely corner case, but if you run `dependents` on a hash representing old state, the UCM gets caught in a loop, and just increments a counter in the print out, failing to quit with `q` as expected. 

a transcript with the following body will show the issue in the printout. 
```
    ```ucm:hide
    .> builtins.mergeio
    .> pull https://github.com/unisonweb/base_v2:.trunk .base
    ```

Dependents command appears to be stuck in infinite loop when looking up hash reference from old base. 

    ```ucm 
    .> dependents #fgaevis4bl
    ```
```

Which will look something like this: 

```
  Dependents of #fgaevis4bl#0:
      [...]
  Dependents of #fgaevis4bl#1:
      [...]
  Dependents of #fgaevis4bl#2:
      [...]
```

At that point you have to terminate the process to reclaim your terminal.

**Comment by aryairani** [comment]
Whoa.

**Comment by pchiusano** [comment]
Does this just happen when listing dependents of any recursive data type or function?

**Comment by aryairani** [comment]
Fwiw, this terminate for me; both interactively on a new codebase, or with a transcript (output [here](https://gist.github.com/aryairani/12c9c40dac2f44c8810c49861d6576e4)):

````
```ucm
.> pull https://github.com/unisonweb/base_v2:.trunk .base
.> dependents #fgaevis4bl
```
````

Old `IO` does have a lot of constructors (0–37), could it just be "needs more `q`?"

Or could it be something particular to the affected codebases?

**Comment by rlmark** [comment]
Oh it's entirely possible this isn't a loop and is just 37 pages of the dependents list. I honestly stopped hitting enter after about 10. 😬  If this is valid / expected behavior I'll close this issue.

**Comment by pchiusano** [comment]
If you type 'q' that will quit the pager (it should say this in the status line at the bottom) and actually since all the results are generated up front as a big string and then passed to the pager, I think if you can 'q' successfully then it's working as expected.

Dependents could maybe restrict itself to only those found in the current namespace. I thought it did this but maybe not.

**Comment by rlmark** [comment]
Ah, ok it takes around 40 seconds (🤔 ) but if I hit 'q' the pager does indeed quit and allow me to use the ucm again. I suspect I just wasn't patient enough to see that happen. I'll close this as it appears to be working, maybe just a big sluggish on my machine.

**Comment by aryairani** [comment]
Ok sounds good; it should not be at all sluggish though, as far as I know (unless it's something to do with looking up the names? but I'm not sure that it would be), so that is still something we could take a look at.

Here it is on my machine; it takes about 3 seconds including UCM startup time.

In a smaller window, paged:

https://user-images.githubusercontent.com/538571/119554710-ff291e80-bd6a-11eb-992d-abfd65aecbef.mov

In a larger window, no pager:

https://user-images.githubusercontent.com/538571/119554789-17993900-bd6b-11eb-8cd9-9d8b40649679.mov

**Comment by rlmark** [comment]
Hmmm maybe it's just a difference in our respective machines? Here's a screencap version of what I've observed, for reference. 

https://user-images.githubusercontent.com/7613551/119556632-1e688180-bd54-11eb-9b72-34cc7a25d400.mov

**Comment by aryairani** [comment]
Oof, thanks for the recording.  I wonder what it's doing? I do have a newish machine _but_ it shouldn't really be doing any work, IDK.
