### ISSUE TITLE
UCM docs rendering fails with `cannot decompile to local recursive binding` 

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2061]
UCM command for docs fails with 

 `cannot decompile to local recursive binding` 

for particular documentation circumstances. 

A zipped transcript and .u file is attached to better showcase the issue.
[zipped2061.zip](https://github.com/unisonweb/unison/files/6586743/zipped2061.zip)

The transcript text is simply: 
`````

```ucm:hide
.> builtins.mergeio
.> load 2061.u
```

```ucm 
.> docs bracket
```
`````

**Comment by pchiusano** [comment]
Another thing we noticed: 

* `docs bracket` works if you delete EITHER of the embedded examples. Like we tried to minimize, thinking it was one example or the other that was triggering the bug, but that doesn't seem to be the case. So I suppose this is a possible workaround - just only one example in your docs.
* It looks like it's failing when attempting to decompile the document after evaluation. FYI, when you do `doc foo`, it evaluates `docFormatConsole foo.doc`, decompiles that, then calls some Haskell code to actually do the rendering.
* Doing an `add` first didn't make any difference.

@dolio I don't think we'll hold up M2 for this but since it could easily come up when people are writing docs I'd say it's high priority.

**Comment by pchiusano** [comment]
Here's a workaround, moving the definitions inline to a let block just before they're used:

```
    catch '(let 
        op : '{Exception} Nat 
        op = '(Exception.raise (Generic.failure "Exception in body" ())) 

        onComplete : '{Exception} ()
        onComplete = '()

        make : '{Exception} ()
        make = '(Exception.raise (Generic.failure "Trouble making the resource" ()))
        
        Exception.bracket make onComplete op)
```

This makes me think that the definitions are being floated out and then decompilation isn't able to inline them back in, or something?

**Comment by dolio** [comment]
Not exactly sure what the problem is. It's not really obvious from tracing the code that goes into making the doc.

I _think_ that the exception is caused by the example results, but I don't know why two examples would be a problem but one wouldn't, or why it would think these functions are recursive.
