### ISSUE TITLE
References to terms in SyntaxText show up in the UI as TypeReference

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2154]
I opened up `List.filter` then clicked through to `List.foldLeft` and got this:

<img width="594" alt="Screen Shot 2021-06-10 at 9 16 05 AM" src="https://user-images.githubusercontent.com/11074/121541098-98dc0700-c9cc-11eb-83e2-8bf242f51262.png">

Notice the URL.

Interesting is that if I refresh the page, the definition still loads but has the wrong url.

**Comment by mitchellwrosen** [comment]
This one might be fixed. The URL looks right to me in share today:

https://share.unison-lang.org/@bbipr4ode027l26cc9m5obsvo06dn5uaqogm5hc7bllgi5qjdrh9t024td24ihg1ioabpncv3i3nrpgqkcf103u0fnjbrnhpqk7c438/terms/unison/base/List/foldLeft

**Comment by hojberg** [comment]
I think its still not working. It's dependent on how you open the definition. It works fine if you open via the finder or sidebar, but if you click through to a term from another definition via its source, it'll show up with a "types" in the URL.

This is due to how `SyntaxText` is rendered. It seems to somewhere pick the `TypeReference` variant over `TermReference`.

**Comment by pchiusano** [comment]
@hojberg Yeah, I'd check `TermPrinter`, I think this line is wrong:

```Haskell
    Ref' r -> parenIfInfix name ic $ styleHashQualified'' (fmt $ S.Reference r) name
```

That should be `S.Referent (Referent.Ref r)` I think.

I'd also rename that constructor to `TypeReference` or some such for clarity. You should be using `S.Referent` for any sort of term reference.
