### ISSUE TITLE
Type inference regression for parameterized abilities

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2167]
This doesn’t typecheck with trunk but did in M2g:

```Haskell
ability R t where
  die : () -> x
  near.impl : Nat -> Either () [Nat]

R.near n = match near.impl n with
  Left e -> die ()
  Right a -> a

R.near1 region loc = match R.near 42 with
  [loc] -> loc
  ls -> R.die ()
```

```
  I found a value  of type:  t1
  where I expected to find:  t
  
      3 | ability R t where
      4 |   die : () -> x
      5 |   near.impl : Nat -> Either () [Nat]
      6 | 
      7 | R.near n = match near.impl n with
      8 |   Left e -> die ()
      9 |   Right a -> a
  
    from right here:
  
      3 | ability R t where
```
The location is highlighting the entire body of `R.near` starting from the `match` keyword.

This one feels pretty big, it seems to prevent writing even basic combinators for any ability that has type parameters like `R` does.

**Comment by dolio** [comment]
I ran into this yesterday. It seems related to the fact that the type of `near` doesn't involve `t`, although I'm unsure why that matters at this point.

**Comment by dolio** [comment]
I think I've figured out what's happening. There are two `t` variables in play from `near.impl` and `die`. They get unified together because they're wanted as part of the `R` ability. However, when that happens, the `t` from `near.impl` has dropped off the context (I think) and is no longer a valid type. So the attempt to solve the variable bombs.

Still trying to figure out the right solution.

**Comment by dolio** [comment]
Here's a more accurate problem description:

It's actually the type variable from `die` that is a problem. Checking cases adds a marker and truncates the context at the end, which includes the `t` from the case, but the variable bubbles out in the wanted abilities. For wanted ability variables I just default them, but that doesn't work for this case.

It can't be solved by e.g. threading in the `near.impl` wanted abilities so that they get opportunistically unified, either. You might have the `near.impl` in a sequence after the context truncation, which would cause the same error, but the sequence of events would happen in the wrong order to coincidentally work out.

So, the idea I'm pursuing now is to re-add the unsolved existentials to the context if they're needed to make sense of the wanted abilities. I think the context truncation is mainly there to deal with existential types, and the strictly ordered context requires more management when context is accumulated out of band rather than via 'unification' in the context.

**Comment by pchiusano** [comment]
Mmm, I see. Does it just work out to avoid doing the context truncation? I might be imagining this, but I think neelk said there's no real harm in doing that, it's more that it makes proofs of correctness easier.

Like you can mark and retract the context only at the scope of a closed term or cycle of definitions rather than as part of each sort of expression you are typechecking.

**Comment by dolio** [comment]
Don't you need to truncate the context for existential types, because it's part of how what would otherwise be skolem escape stuff works? And polymorphic effects in abilities are like existential data types.
