### ISSUE TITLE
Extend `pull` command to work with Unison Share

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2171]
We want to allow users to pull directly from Unison Share with a simple command:

```
.> pull unison/base .base
```

The idea is that we host the _Unison Share_ codebase on GitHub (at least for the time being), and using the `pull` command with a fragmented path will use the _Unison Share_ GitHub repository URL behind the scenes. This allows a very tight connection between _Unison Share_ and `ucm` and allows us in the future to share how code is hosted on _Unison Share_ without any impact on the UX in `ucm`.

--

There are 2 main efforts involved in this work:

* _Unison Share_ is based off of a codebase on GitHub
* update `pull` to support paths instead of full URLs and have those paths be connected a URL that redirects to the GitHub repository URL (such that we control the redirection scheme for future changes)

**Comment by aryairani** [comment]
The current situation with Github hosting makes this somewhat expensive, because the user has to download all of everything in the git repo in question, but we could accept that slowness and improve it later by swapping out the back end.

It looks like redirects will work for http/https-based git repos, but wouldn't work in general.

**Comment by hojberg** [comment]
> but we could accept that slowness and improve it later by swapping out the back end.

Yeah, I think this sets us up well to do that

**Comment by hojberg** [comment]
Closing in favor of https://github.com/unisonweb/unison/issues/2698
