### ISSUE TITLE
Universal.compare of negative floats is backwards

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/unison#2257]
I don't expect `-1.0 < -2.0` to be true.

```
# scratch.u
> 0.0 < 0.0
> 0.0 < 1.0
> 1.0 < 2.0
> +0.0 < +1.0
> +1.0 < +2.0
> -1.0 < 0.0
> -2.0 < -1.0
> -1.0 < -2.0

# ucm
  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.


    1 | > 0.0 < 0.0
          ⧩
          false

    2 | > 0.0 < 1.0
          ⧩
          true

    3 | > 1.0 < 2.0
          ⧩
          true

    4 | > +0.0 < +1.0
          ⧩
          true

    5 | > +1.0 < +2.0
          ⧩
          true

    6 | > -1.0 < 0.0
          ⧩
          true

    7 | > -2.0 < -1.0
          ⧩
          false

    8 | > -1.0 < -2.0
          ⧩
          true
```

**Comment by pchiusano** [comment]
Thanks for reporting. Try using `Float.lt` instead.

At the moment, `Universal.<` (which is what your code is using) compares floats by bitwise casting to ints and comparing those. More discussion here: https://github.com/unisonweb/unison/issues/1717

I think that is reasonable since we want it to be a total order, but it looks like it handles signed values incorrectly? Is the fix as simple as flipping the sign bit before comparison? If yes @dolio could you make this tweak?

**Comment by pchiusano** [comment]
I'm actually a little confused since I think what is currently being done should be correct (ignoring NaN) according to https://github.com/unisonweb/unison/issues/1717#issuecomment-705328570

**Comment by dolio** [comment]
Yeah, I thought it would happen to work out. Did it get flipped to use unsigned comparison for all/most unboxed things at some point?

**Comment by dolio** [comment]
I looked into this a little more. Apparently comparing as integers _almost_ works, but negatives are handled in a slightly different way so that two negative numbers won't actually compare correctly as integers. There are ways to fix it up using integers, but you'd need to know that you're dealing with floating point numbers in the first place, which is the whole issue.

**Comment by pchiusano** [comment]
@dolio It seems like when descending into a boxed float you’ll know that and can switch to different logic, right? And the float tag is just an Int at that point so pretty fast to check.

similarly for nats which have issues for nats bigger than an Int.

**Comment by dolio** [comment]
Yeah, I can add some special cases if desired. It'll only handle, like `Float` `Int` and `Nat`, though. If some unboxed floating point data ends up in a closure somehow, it won't really be possible to detect that. I'm not exactly sure how that'd happen, though. Probably not until we get around to writing actual optimizations.

**Comment by pchiusano** [comment]
That makes sense and seems fine / unavoidable.
