### ISSUE TITLE
Parser rejects if-then-expression if it's a direct element of a list

### ISSUE THREAD

**Issue by alvaroc1** [unisonweb/unison#2258]
```
/Users/acarrasco/workspace-ac/unison-scratch-v2/scratch.u:1:30:
  unexpected ]
      1 | > [if true then "x" else "y"]
```

this works fine:
```
1 | > [(if true then "x" else "y")]
          ⧩
          ["x"]
```

Unfortunately, it gets rendered by the pretty-printer in the correct, but un-parsable version:
```
.> view x

  x : [Text]
  x = [if true then "x" else "y"]
```

version: release/M2g

**Comment by alvaroc1** [comment]
Simpler version that also fails:
```
x = [let true]
```
But this parses fine:
```
x = [let true
      ]
```

**Comment by runarorama** [comment]
The issue here is that the `]` doesn't close the `if` block. 

One thing we could do is add a `Close` lexeme on `]` or `,`. Although I think that might result in even worse parse errors. We could also just lookahead on a missing `Close`, looking for `]` or `,` instead. But again, bad parse errors.

Another idea I had was to add a parser state for whether we're inside a list expression, then a `,` or `]` should close any open block in lieu of a `Close` lexeme.

Any more ideas @pchiusano?

**Comment by pchiusano** [comment]
@runarorama I'm thinking just have `[` do an `Open "["` and `]` emit however many `Close` are needed to pop that `[` off the stack. Exactly like how parens are handled by the lexer.

Then I think this parser in `Parser` will need updating:

```
seq :: Ord v => (Ann -> [a] -> a) -> P v a -> P v a
seq f p = f' <$> leading <*> elements <*> trailing
  where
    f' open elems close = f (ann open <> ann close) elems
    redundant = P.skipMany (P.eitherP (reserved ",") semi)
    leading = reserved "[" <* redundant
    trailing = redundant *> reserved "]"
    sep = P.try $ optional semi *> reserved "," <* redundant
    elements = sepEndBy sep p
```

You can peep `tupleOrParenthesized` for inspiration.

**Comment by runarorama** [comment]
That won't quite do it since a comma can also close a block inside a list.

**Comment by pchiusano** [comment]
> That won't quite do it since a comma can also close a block inside a list.

Ah yeah good point. But my idea could be combined with your idea

> Another idea I had was to add a parser state for whether we're inside a list expression, then a , or ] should close any open block in lieu of a Close lexeme.

Proposal: a comma should pop everything from the stack until (but not including) the innermost block which is comma-separated.

Just thinking through an example here. Suppose I have:

```
[ if a then blah
  else handle foo with fst (h, ignored),
  cases a, b -> a + b -- mutli-arg cases lambda
]
```

just before the comma in `(h,ignored)`, the layout stack will be `[` `else` `with`, `(`.  The innermost comma-separated block is the `(` block, so since there's nothing after that on the stack, it leaves that unchanged.

After the closing `)`, the `(` is popped from the layout stack and the next comma will pop everything from the stack until but not including the innermost comma-separated block, which will be the `[`, so it will result in the stack `[` with nothing after it.

The `cases a, b -> a + b` works with this, if we consider `cases` to be a comma-separated block.

WDYT?
