### ISSUE TITLE
Changes to Docs elements do not get propagated to enclosing docs

### ISSUE THREAD

**Issue by rlmark** [unisonweb/unison#2267]
While I've had a hard time reproducing this in a transcript, this appears to be reliably happening in my codebase (probably not a fluke). Say you've added a doc term `glossary.arity` to be used in a tooltip element. You fix a typo in that element, but when you go back to where the doc element is used as a tooltip, your change is not present. You notice that the docTooltip now contains a reference to a hash: `{{docTooltip {{ arity }} {{ {{ #i5p5c82uob }} }} }}` which represents the old version. If you then update the enclosing doc element to point to the new version, any doc elements which reference _that_ doc by termlink are now referenced by the old hash of that doc, so your doc tree is stale and the cycle of removing hashes begins anew.

**Comment by pchiusano** [comment]
Going to close this, but what we figured out was that `update` was being applied to a subnamespace `some.subpath`, so it only propagated the change within that subnamespace. This is sometimes what you want but it's also a footgun and UCM should give better feedback. #2248 

For the docs, where patches aren't really kept around, the fix is to `cd` to the project root and do `patch some.subpath.patch`. Then that patch can be deleted using `delete.patch`.

We came up with some other tips / best practices, and I don't remember what they all were, but I think @rlmark took notes. :)
