### ISSUE TITLE
Projects: Outline all the pieces that goes into the Project term and type

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2288]
We'll identify projects by a special term called `project` with the type of `Project`. This ticket tracks the design of that term and type by gathering all the information that would need to go into this term and how it will be displayed.

Things to consider
* Maintainers
* Contributors
* Releases (along with Changelogs and release notes)
* Semver
* Activity like "last updated at" (similar to latest commit in Github—should we have commit messages?)
* Dependencies
* Readme
* Licenses
* Dependents

An example of what this would look like when displayed:

```
unison/http
-----------

Last change:
  Aug 3 2021 by Simon Højberg

Maintainers:
  Simon Højberg
  Rebecca Mark

Licenses:
  MIT - Unison Computing

Releases:
  _latest -> v3.2
  v3.2    -> #0f6ehr9tfe
  v3.0    -> #2ta519s14d
  v2.1    -> #alk9jqts4n
  v2.0    -> #p9g2huu8da
  v1.0    -> #v5f0lerou3
```

**Comment by hojberg** [comment]
I worked on a draft proposal for the `Project` type:

# Unison Project type and definition proposal
We've discussed having a definition in a namespace called `project` of type `Project` to denote a namespace as a _project_. Examples of _projects_ are things like `ucm` and the Codebase UI as well as the FuzzyFind library or Servant.

This is a design proposal for what the `Project` type could look like. It is very much open for feedback, iteration, and collaboration.

## Elements
A definition named `project` of type `Project` type is the way to identify a namespace as a _project_. Creation of it will be aided with `ucm` commands.

The `Project` type includes a way to identify a project, a name and description—useful for at-a-glance info on Unison Share—version and dependency information, and minor metadata. It is defined in full like so:

```hs
unique type Project = 
  { id : ProjectId
  , name : Optional Text
  , description : Text
  , maintainers : Set Author
  , website : Optional Website
  , latest : Optional Release
  , releases : Releases
  , compatibility : Set UnisonVersion
  , dependencies : Releases
  }
```

### ProjectId
A `ProjectId` is used both by `Project` and various dependency related sub types.  This is modeled simply as a wrapper around `Text`, but should probably be better typed. It could perhaps be a `GUID` and on Unison Share a `GUID` of the namespace it resides in or it could be something like `ProjectId "unison" "http" which would match a user/org + namespace combo for Unison Share much like we see on Github.
```hs
unique type ProjectId = ProjectId Text
```

### Release, Releases, Version
A `Release` denotes a point in time for a project. It has `ProjectId` to identify the release with a `Project`, a `Version` and a `Hash` of the project
namespace.
```hs
unique type Release = Release ProjectId Version Hash
```

A `Version` is a simple wrapper around some text the user defines. This could need some iteration to perhaps have a `SemVer` type to help users communicate versions better.
```hs
unique type Version = Version Text
```

`Releases` is a wrapper around `Set` to include some guarantees around uniqueness such that 1 version number couldn't be used for 2 distinct hashes. `Releases` is used in a `Project` both to denote the releases of that project and to track it's dependencies.
```hs
unique type Releases = Releases (Set Release)
```

### Misc
`UnisonVersion` A simple sum type that corresponds to the releases of Unison we make, allowing for compatibility checks with regards to libraries that use builtins. We would expand on this each new release.
```hs
unique type UnisonVersion = M1a | M1b | M2g -- | .. | .. 
```

A project can—but isn't required to—be hosted on Unison Share, but if it is we can more a more integrated `UnisonShare` variant.
```hs
unique type Website = UnisonShare ProjectId | Web Url
```

## Example Projects

```hs
unison.http.project : Project
unison.http.project = 
  projectId = ProjectId "unison.http"

  { id : projectId
  , name : "HTTP"
  , description = "Simple and low level http library"
  , maintainers = Set.fromList [rlmark, hojberg]
  , website : Some (UnisonShare projectId)
  , latest = Some (Release projectId (Version "preview" (Hash "#djtw24sglI"))
  , releases = 
      Releases.fromList
        [ Release projectId (Version "v1") (Hash "#5xa4ggki3")
        , Release projectId (Version "v2") (Hash "#frjw5w12kf")
        ]
  , compatibility = Set.singleton M2g
  , dependencies = 
      Releases.fromList
        [ Release (ProjectId "rlmark.parsing") (Version "preview") (Hash "hktydc24s4e")
        , Release (ProjectId "stew.logging") (Version "v2") (Hash "gkjr214skI")
        ]
  }
```

```hs
hojberg.html.project : Project
hojberg.html.project = 
  { id : ProjectId "hojberg.html"
  , description = "Combinations for building HTML"
  , maintainers = Set.singleton hojberg
  , website = None
  , latest = None
  , releases = Releases.none
  , compatibility = Set.singleton M2g
  , dependencies = Releases.none
  }
```

## Rough edges and open questions
* The naming of field and types could be improved.
* `ProjectId` needs a bit more work
* Should `Version` enforce Semantic versioning?
* A project can depend on itself...

## Minor/Insignificant details
* I didn't specify the `Url` type used by `Website`. This should likely be a type in base with some  nice guarantees or even a whole library (some exploration of this has been done in the http library)
* <details><summary>Helper functions</summary>

  ```hs
  Releases.none : Releases
  Releases.none = 
    fromSet (Set.empty)

  Releases.fromList : [Release] -> Releases
  Releases.fromList list = 
    Releases (Set.fromList list)

  Releases.fromSet : Set Release -> Releases
  Releases.fromSet set = 
    Releases set

  Releases.singleton : Releases
  Releases.singleton release = 
    Releases (Set.singleton release)
  ```
  </details>

**Comment by atacratic** [comment]
Nice 😊

Various comments from me...

- I think there should be a principle that a `Project` definition is not *needed* - it's sugar that can make things nicer to use and understand, but is not mandatory.  I think it's an important part of the unison vision (at least as far as I understand it) that programs are just made up of definitions (terms+types), with any other stuff just being metadata.  And, more concretely, I think it would be nice if the path remained open to one day people being able to publish single functions, with one click.  I don't think anything you've said above goes against any of this, but I thought it was worth calling out to see if people disagree.  

- I winced a bit when I saw the `dependencies` stuff.  I thought 'wasn't part of the point of unison so we didn't have to wrangle all that stuff?'  Trying to make sense of that a bit better:  Unison tracks dependencies at the level of individual references between functions.  If you're using v2 of a library, then all your functions will point to that library's hashes as they stood at v2.  If you then need to restate that at the level of the project then (a) you're repeating yourself, (b) if you want to mix and match which versions of a library's functions you're using (one of unison's selling points!) then at the project level you'll be telling a half-truth.  
  - Wouldn't it be better if (one day) the unison tooling analyzed things and told you the real situation?  "this project depends on a bunch of hashes which are named in the latest release of that project, but also 3 that were named in previous releases but no longer."
  - (And anyway, wouldn't the dependencies be a function of time?  Your dependencies change release to release.  Why are we only describing the latest release in this project metadata?  Similarly with `compatibility`.)

- Do we really have to state `compatibility` with Unison versions? Changes in Unison that affect what existing Unison terms evaluate to should be either bugfixes or vanishingly rare, right?  And surely we don't want project maintainers to have to take action, with every new unison release, to update their project metadata to confirm it works with the new release too?
  - I assume the base library is not relevant for `compatibility`, since it's a library like any other.  
  - Also looking at the `UnisonVersion` type, I wonder if it will be hairy that every time there's a new release, the `UnisonVersion` type hash itself changes.  

- You've got `Version` as free text.  I think it might be good to mandate what library version IDs look like, to ease consumption of libraries by making them more uniform.  Maybe this is what you had in mind with your note about semver.  I think there's a big design space here, which would be worth exploring.  
  - For example I'd be tempted to explore something like the following:  the version ID is the hash of the trunk namespace; metadata available for each version include the release date, the ID of the immediate ancestor release, whether there have been breaking changes or new function since that release, and if so a list of the affected terms (or maybe names).  
  - I wonder if, by working in terms of explicit named release versions, it will end up being harder to work with library versions which did not happen to be releases.  For example, how to find out if there have been breaking changes in trunk since the last release?  Also, are we mandating a worldview in which all releases are equal?  What if your project requires (gulp) manual testing or manual test validation, or has a compute-intensive suite of tests that need `IO`?  You might want to be able to publish a small or patch release without redoing all that.  Can you do that without updating `latest`?
  - Could information like "includes breaking change to the behavior of xyz" or "all relevant tests for the project pass" maybe be metadata added to *any* point in the library's timeline?  So, trying to unbundle the 'release' concept into more specific things.  

- Other stuff:
  - Should `description` be `Text` or `Doc2`?
  - Could `website` support the case where you want a link to both Unison share and also your own site?
  - I think you might be saying that the project info will be a term named `mylib.project.project`.  Could it just be `mylib.project`?
  - What about projects within projects?  e.g. `mylib.external.someotherlib.project`  (I forget what the convention is.)

**Comment by hojberg** [comment]
@atacratic thanks for looking over this, really good feedback. I've tried to respond below as best as I can.

## Project goals

Firstly, I apologize, there isn't much context in this ticket about the goals of projects, how we came to this ticket, etc.

This ticket here is part of a series of effort all pertaining to projects:

* [Projects: Outline the project namespace structure](https://github.com/unisonweb/unison/issues/2317)
* [Projects: New ucm commands](https://github.com/unisonweb/unison/issues/2318)
* We also have a separate design task with regards to dependencies, pending a brainstorm session

Here's some of the things we want developers to be able to do with Projects (especially as it relates to Unison Share):

* Search, discover, download, and publish projects
* Host private projects (either personal or for an organization)
* Inform other developers how and where to contribute to the project (pull requests, code review).
* Keep track of project updates (security patches, perf improvements etc)
* Set up local projects and download dependencies

## Projects shouldn't be mandatory

> I think there should be a principle that a `Project` definition is not needed - it's sugar that can make things nicer to use and understand, but is not mandatory. I think it's an important part of the unison vision (at least as far as I understand it) that programs are just made up of definitions (terms+types), with any other stuff just being metadata. And, more concretely, I think it would be nice if the path remained open to one day people being able to publish single functions, with one click. I don't think anything you've said above goes against any of this, but I thought it was worth calling out to see if people disagree.

The plan is not to make projects mandatory. That said, we do do intend to make them very integrated and they will be the main way to share code on Unison Share and we definitely also want to allow for publishing very small projects of single functions etc. This could perhaps be done with an "anonymous project" or similar.

## Dependencies

We definitely have a lot of exploration in this area still to make and, because of that, I should probably have left it out of the initial `Project` type design.  We have some brainstorm work planned for this in the coming weeks.

The main goals of the dependency part of this work is to enable library authors, maintainers and consumers to speak in a common language about their code.  A question that comes up a bunch is "which version of base are you using?" and there's currently no way for people to easily figure that out right. Providing good support for security patches etc also seems key.

I think deriving dependencies could be really cool way to deal with this to avoid storing these in the `Project` definition. The challenge with derivition, I guess, is embedding enough information into what goes into `_external` to support it.

We could have ucm commands, like you suggest, to deal with this in a nice way instead of embedding versions into the `Project` definition. I'm liking this idea—will keep that in mind as we move the dependency portion of projects along.

## Unison Compatibility

Currently we're introducing new builtins with pretty much every Unison release, though I imagine that will slow down some. Based on that the goal here being to allow both maintainers and consumers to quickly understand if they can use a library.

I think the concept of compatibility needs to exist in some form, but you're making me think that it might be better off determined via dependencies of base instead of having to manually track it. Its definitely information we'd want to show on a project in Unison Share or when someone tries to install it on a incompatible version of Unison.

> Also looking at the UnisonVersion type, I wonder if it will be hairy that every time there's a new release, the UnisonVersion type hash itself changes. 

Yeah this is a good point.

## Version

> You've got Version as free text. I think it might be good to mandate what library version IDs look like, to ease consumption of libraries by making them more uniform. Maybe this is what you had in mind with your note about semver. I think there's a big design space here, which would be worth exploring.
>
> For example I'd be tempted to explore something like the following: the version ID is the hash of the trunk namespace; metadata available for each version include the release date, the ID of the immediate ancestor release, whether there have been breaking changes or new function since that release, and if so a list of the affected terms (or maybe names).  I wonder if, by working in terms of explicit named release versions, it will end up being harder to work with library versions which did not happen to be releases. For example, how to find out if there have been breaking changes in trunk since the last release?  Also, are we mandating a worldview in which all releases are equal? What if your project requires (gulp) manual testing or manual test validation, or has a compute-intensive suite of tests that need IO? You might want to be able to publish a small or patch release without redoing all that. Can you do that without updating latest?  Could information like "includes breaking change to the behavior of xyz" or "all relevant tests for the project pass" maybe be metadata added to any point in the library's timeline? So, trying to unbundle the 'release' concept into more specific things.

:100: there's a lot to explore here still.


## Other notes

> Should description be Text or Doc2?

I think we'd want to keep it `Text`. My intention is really for this to be a 2 line summary like you see on Github and `Doc` might be too much. Separately we'll support READMEs that will be `Doc`s.

> Could website support the case where you want a link to both Unison share and also your own site?

Yeah this is a good point!

> I think you might be saying that the project info will be a term named mylib.project.project. Could it just be mylib.project? 

Sorry, I think my wording was bad. Its intended to be `mylib.project`.

> What about projects within projects? e.g. mylib.external.someotherlib.project (I forget what the convention is.)

Tentatively, it'd be like that yes. I think we'll find out more about the specifics of that as dependencies are explored further.

**Comment by atacratic** [comment]
@hojberg thanks very much for the replies, lots of interesting context there, all makes a lot of sense 👍

**One follow up:**

> I think the concept of compatibility needs to exist in some form, but you're making me think that it might be better off determined via dependencies of base instead of having to manually track it.

Actually, probably can't do that: base ought to be a library like any other, and you're right there needs to be a way to work out how new a set of builtins a given version of base needs.  I guess as long as the `compatibility` field is an inequality ("make sure we have a unison version *at least* as new as x") then it's fine.  Probably that's what you meant to begin with.  

Most libraries ought not to need to specify a unison compatibility version - it should be optional.  Typically they'll achieve the same end by specifying the minimum version of base they need.  That might be what you meant with your comment.

**One random idea that might be bad:**

I wonder if the dependency tracking stuff could be internalized into core unison concepts a bit more?  So:
- A project defines a sentinel term representing its version.
- Other projects list their dependencies by referencing those terms.  

e.g.:

```haskell
unique type alicelib.id = ID
alicelib.version = Version alicelib.id.ID "v1.0"

boblib.dependencies = Dependencies [alicelib.version, base.version]
```

So when Bob pulls in a new version of alicelib, that is auto-propagated into boblib.dependencies just as with any other dependency on Alice's definitions.  

**And another:**

In your proposal there's a `Hash "#5xa4ggki3"` needed when specifying releases and dependencies.  I guess it will be populated by tooling.

But another approach might be having something like `@namespaceLink mylib.trunk`, yielding the namespace hash.

**Comment by hojberg** [comment]
Closing. We have projects :)
