### ISSUE TITLE
Need either `unsafeCoerce` or some more restricted version

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2341]
This has come up several times. Currently it’s blocking work on a local interpreter of `Remote`.

**Comment by dolio** [comment]
This is easy to do, but what version do you actually need? The version with type:

    forall a b. a -> b

will cause subtle problems unless it's actually the case that `a` and `b` are identical. If the desire is for reinterpreting bits, those need to be written for specific types to actually work correctly.

**Comment by pchiusano** [comment]
Right. The version I need for now is just:

```Haskell
unsafeCoerceAbilities : forall a g g2 b . (a ->{g} b) -> (a ->{g2} b)
```

Which doesn't seem too unsafe... at worst it leads to uncaught requests. Maybe we add this for now and consider other kinds of coercing for later? WDYT.

**Comment by dolio** [comment]
That can only be the general one in behavior, I think. I just needed to know which one to implement, and there should probably be caveats documented that using it for `Nat -> Int` isn't actually going to work correctly, because you'll get an `Int` that still has information specifying that it's a `Nat`.

I guess you could restrict the type to be somewhat less unsafe, but people might eventually want the general one for something.

**Comment by pchiusano** [comment]
I think it's likely someone will want `unsafeCoerce` at some point, but I'd be inclined to hold off on adding the fully general version for now.

**Comment by dolio** [comment]
Okay.
