### ISSUE TITLE
`transcript` test tool doesn't support custom stack settings

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2383]
At https://github.com/unisonweb/unison/blob/trunk/parser-typechecker/transcripts/Transcripts.hs#L78, `transcripts` calls stack explicitly, using just default settings, to launch a sibling `unison` executable to run each test transcript.

If you are using a custom stack configuration (/cc @ChrisPenner), this will miss it.

We probably shouldn't be calling `stack` at all here, and use some other method to find `unison`. Maybe something like https://hackage.haskell.org/package/system-argv0 to find the sibling, via
`/path/to/transcripts` -> `/path/to` -> `/path/to/unison`

**Comment by ChrisPenner** [comment]
Interesting; curious if it would be reasonable to just import the Unison library and call it directly rather than shelling out? Or is this a better "integration" test? Presumably we could re-factor the Arg parsing layer to handle that.
This would ensure you're always running tests against the "current" build of unison, which might not be the case if it just searches for any old `unison` on your path. This approach would also (probably) mean that this test works on Windows.

Another option would be to tweak the testing process to dump a unison build into `./bin/unison` or something and we can shell out to that specific path in all cases.

**Comment by aryairani** [comment]
IIRC it's just a hack, not a better integration test.

We should have a separate conversation about what works on Windows. 😅

**Comment by aryairani** [comment]
We no longer spawn another executable in `transcript`
