### ISSUE TITLE
Signed metadata

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2417]
Would be nice to allow metadata to be cryptographically signed, so that, for instance, you could verify that someone with Alice’s private key associated some metadata with a hash.

**Comment by aryairani** [comment]
You could do it with the existing metadata mechanism, given
```unison
unique type Signed a = { data : Link, metadata: a, key : PublicKey, signature: Signature }
-- and/or
unique type AnonymouslySigned a = { data : Link, metadata : a, signature: Signature }
```
where `signature = sign(k_r, (data, metadata))`
instead of linking plain metadata with a hash, you can link the signed metadata to it.  Then when searching for definitions with a particular type of metadata `Foo` you could search for both `Foo` and `Signed Foo`.

**Comment by aryairani** [comment]
Closed as moot without metadata
