### ISSUE TITLE
pretty printer roundtrip issue with nested constructors involving lists

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#2492]
Given this (simplified) JSON type:

```haskell
unique type Json
  = JString Text
  | JObject [(Text, Json)]
  | JArray [Json]
```

This parses:

```haskell
myJson = JArray [ JObject
    [ ("ID", JString "40e4a748-2192-161a-0510-9bf59fe950b5"),
      ("Node", JString "t2.320")
    ]
  ]
```

Now we watch it to pretty-print it:

`> myJson`:

```haskell
Json.JArray
  [ Json.JObject
    [ ("ID", Json.JString "40e4a748-2192-161a-0510-9bf59fe950b5"),
      ("Node", Json.JString "t2.320") ] ]
```

But if we copy that output:

```haskell
> let
  Json.JArray
    [ Json.JObject
      [ ("ID", Json.JString "40e4a748-2192-161a-0510-9bf59fe950b5"),
        ("Node", Json.JString "t2.320") ] ]
```

We get:

```
  unexpected [
  expecting ,
    110 |       [ ("ID", Json.JString "40e4a748-2192-161a-0510-9bf59fe950b5"),
```

**Comment by kanwren** [comment]
After doing some digging, this looks like a specific case of a more general and annoying round-trip problem: hanging the arguments to a function application might cause them to end up at the same indentation level as the function itself (due to parentheses, lists, ticks, etc.), which causes the parse error.

For example, if there is an application like this, in which the arguments are long and the line breaks:
```
f
  veryLongExpression1
  veryLongExpression2
```
This is fine, but if this expression needs to be parenthesized _exactly twice_, the following will happen:
```
((f
  veryLongExpression1
  veryLongExpression2))
```
This causes a parse error, since `f` is at the same column as the arguments. This isn't that the arguments need to be indented more, though that would work; it would also work to _dedent_ them by one space (or add a third pair of parens).

The issue above looks like the same thing, but with parens replaced by a list. As a contrived example:
```hs
ex : [Nat]
ex =
  [ Nat.and
      (123456789 + 123456789 + 123456789 + 123456789 + 123456789 + 123456789)
      (123456789 + 123456789 + 123456789 + 123456789 + 123456789 + 123456789) ]
```
This code fails to roundtrip, as it reads and pretty-prints to this:
```hs
ex : [Nat]
ex =
  use Nat +
  [ Nat.and
    (123456789 + 123456789 + 123456789 + 123456789 + 123456789 + 123456789)
    (123456789 + 123456789 + 123456789 + 123456789 + 123456789 + 123456789) ]
```
which fails to parse for the aforementioned reason.

**Comment by pchiusano** [comment]
@nprindle thanks for digging into this one, so does your #2819 PR also fix this as well?

**Comment by kanwren** [comment]
No; unfortunately, this looks more involved. I'm not quite sure what in the parser causes it to fail, but if it's intended behavior, then from what I've seen the pretty-printer would just have to avoid that indentation level, which doesn't seem very trivial to do. If it's just a bug in the parser, then it should be easier to fix.

**Comment by aryairani** [comment]
I'm not very familiar with the parser, but would it work to require the arguments to be indented relative to the first non-whitespace character on the line, instead of relative to the function being applied?

**Comment by aryairani** [comment]
It looks like this round-trips today?
Both Simon's example (without the `let`) and @kanwren's
