### ISSUE TITLE
`ucm` is slow to start

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#2528]
Currently `ucm` is slow to start up: about 4.5 seconds on my beefy machine to load `base` (2486 definitions).

I created this ticket just to track some stats about what's going on, as well as have a place to hang performance improvements that we might in pursuit of bringing this number down.

**Comment by mitchellwrosen** [comment]
Idea: a prepared statement cache.

I believe currently we are, for each query, preparing the statement, using it once, and finalizing. Because we are performing each individual query so many times when deeply decoding a root namespace, we may get big wins by reusing these.

#2532

**Comment by mitchellwrosen** [comment]
Factoid: 

- We perform about 33,000 sqlite queries when loading today's `base` of 2486 definitions
- 60,000 to load a namespace with two copies of `base` at the top level

**Comment by mitchellwrosen** [comment]
#1340 would reduce startup time for codebases that would use that feature

**Comment by iacore** [comment]
Here because database migration is slow.
Any plan to use https://github.com/LMDB/sqlightning? It's about 20x faster than SQLite. No haskell bindings though.

**Comment by pchiusano** [comment]
Looks interesting, but probably not something we can consider in the short term, and I doubt SQLite's data structures are the bottleneck anyway. We're just loading too much stuff on startup that isn't really necessary, and also doing too many point queries. 

FWIW, it looks like the claimed ~ 20x is only relevant for inserts (and does that come with same durability guarantees as SQLite?) - other access patterns look more similar even according to the author's benchmarks. 

That said, @mitchellwrosen I think the prepared statement cache https://github.com/unisonweb/unison/issues/2532 seems like a good thing to try, and then I think we could cut the number of queries way way down just by doing things in bulk. Like rather than looking up mappings from object id to hash individually, you could just, load the entire range of the table, covering the object ids in question. And then resolve all the ids in bulk.

... not highest priority right now, but could be interesting to try later. 

Ultimately, I think ucm should just not load hardly anything in memory on startup, and then startup will be instantaneous, but that's a bigger refactoring.

**Comment by ceedubs** [comment]
@mitchellwrosen @ChrisPenner I think that the startup time story is much better now. Should this be closed out?

**Comment by mitchellwrosen** [comment]
I guess so, yeah - though it's kind of an illusion; we still load the whole root branch, which is slow, but we at least let you use your prompt meanwhile, and a few commands don't require the root branch. :)

**Comment by ChrisPenner** [comment]
@mitchellwrosen I also improved the non-instant start up times by 95% by an earlier patch 😄 
But yes, we should continue to iterate and knock down usages of the root branch.

**Comment by mitchellwrosen** [comment]
Oh, cool. What patch was that?

**Comment by ChrisPenner** [comment]
By earlier I mean over a month ago haha: https://github.com/unisonweb/unison/pull/3297
