### ISSUE TITLE
Long names are sometimes picked for source on share

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#2567]
See:

<img width="795" alt="CleanShot 2021-10-29 at 14 33 19@2x" src="https://user-images.githubusercontent.com/2371/139485085-095a2ac7-13b5-4c94-a02f-0877a03b651e.png">

Current theory is that the `pending` namespace on Share is causing, but needs more investigation.

**Comment by hojberg** [comment]
@ceedubs is the `pending` namespace supposed to be deleted after sync?

**Comment by ceedubs** [comment]
@hojberg the current code to update share looks like this:

```
pull https://github.com/unisonweb/share .pending
reset-root .pending
```

So we don't exactly delete it, but it's not a thing that you should ever see (unless maybe you get extremely unlucky with timing your request).

Even if `pending` _were_ being caught, I'm not sure why it would cause this issue. If it were causing trouble, I'd expect you to see something like `pending.bascott...`. But I'm not familiar with how name resolution works.

**Comment by hojberg** [comment]
@ceedubs i'm definitely seeing `pending` hanging out a lot on Unison Share.

@pchiusano might have context on the resolution part.

**Comment by ceedubs** [comment]
@hojberg hmm that's good to know. I assumed that the namespace wouldn't show up until it was fully hydrated and that by that time it would only be milliseconds before we reset the namespace. But maybe that was a bad assumption. I'll write up the issues that we've had with updating Share and share them with Arya and see whether he has any thoughts.

**Comment by hojberg** [comment]
@ceedubs @pchiusano FYI in a codebase without pending these long names definitely still happen

**Comment by pchiusano** [comment]
Something else that's not adding up up is that I'm almost certain the `Either` and `Failure` types referenced are the same in `pending` as elsewhere. It shouldn't use a longer suffix to disambiguate when both suffixes refer to the same thing.

@ceedubs does it help if you `quit` and restart UCM after the `reset-root pending`?

**Comment by ceedubs** [comment]
@pchiusano If we quit and restart UCM, Share isn't going to be able to serve requests while UCM starts up. I'm not sure how long this takes in headless mode for the share repo; I'd have to check it out. But the way that the server pulls in share updates probably needs an overhaul anyway. I talked with Arya about this for a while on Friday, and we have a couple of options that we are going to investigate as we find time.

But based on what @hojberg said, it sounds like the `pending` namespace and the update process are a separate concern from the long names. I'm guessing that we are just seeing this on share because of the longer names in the namespace?
