### ISSUE TITLE
unique types not unique within transcript

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#2629]
The following is the output of [this raw transcript](https://gist.github.com/ceedubs/c0b236c38d558bc72ea559e918ac921a).

# summary

Within a transcript, if you add two unique types with the same structure, they become the same type despite the `unique` modifier.

I can't reproduce this using `ucm` interactively as opposed to in a transcript. This means it's not _as_ big of a deal. But since we are relying on transcripts for tests, it could mask issues or create false positives for issues.

It also doesn't seem to happen if you add the two types in the same `add` command.

# example

```unison
unique type Foo = Foo Nat
```

```ucm
.> add

  ⍟ I've added these definitions:
  
    unique type Foo

```
Now we declare a `Bar` type that looks the same as `Foo`:

```unison
unique type Bar = Bar Nat
```

We see that `Foo` and `Bar` are in fact the same type, even though we declared them as `unique`.

```ucm
.> add

  ⍟ I've added these definitions:
  
    unique type Bar
      (also named Foo)

.> names Foo

  Type
  Hash:  #00k3c9bp6m
  Names: Bar Foo
  
  Term
  Hash:   #00k3c9bp6m#0
  Names:  Bar.Bar Foo.Foo

.> names Bar

  Type
  Hash:  #00k3c9bp6m
  Names: Bar Foo
  
  Term
  Hash:   #00k3c9bp6m#0
  Names:  Bar.Bar Foo.Foo

```

**Comment by aryairani** [comment]
Looks like it's fixed; here's the current output:

# summary

Within a transcript, if you add two unique types with the same structure, they become the same type despite the `unique` modifier.

I can't reproduce this using `ucm` interactively as opposed to in a transcript. This means it's not _as_ big of a deal. But since we are relying on transcripts for tests, it could mask issues or create false positives for issues.

It also doesn't seem to happen if you add the two types in the same `add` command.

# example

```unison
unique type Foo = Foo Nat
```

```ucm
.> add

  ⍟ I've added these definitions:
  
    type Foo

```
Now we declare a `Bar` type that looks the same as `Foo`:

```unison
unique type Bar = Bar Nat
```

We see that `Foo` and `Bar` are in fact the same type, even though we declared them as `unique`.

```ucm
.> add

  ⍟ I've added these definitions:
  
    type Bar

.> names Foo

  Type
  Hash:  #b509v3eg4k
  Names: Foo
  
  Term
  Hash:   #b509v3eg4k#0
  Names:  Foo.Foo
  
  Tip: Use `names.global` to see more results.

.> names Bar

  Type
  Hash:  #m99dsi205a
  Names: Bar
  
  Term
  Hash:   #m99dsi205a#0
  Names:  Bar.Bar
  
  Tip: Use `names.global` to see more results.

```
