### ISSUE TITLE
when updating a code cycle, not all dependents of the cycle get updated

### ISSUE THREAD

**Issue by stew** [unisonweb/unison#2649]
- [x] Blocked on #2471 
---

I'll let the transcript speak for itself, but essentially when you trigger an update of a cycle by updating something that cycle depends on, not all dependents of the cycle get updated

**Transcript**

    ```ucm
    .> builtins.merge
    ```
    ```unison
    usedBy1 _ = ()
    
    cycle1 _ = !usedBy1
               !cycle2
    cycle2 _ = !cycle1
    
    uses1 = !cycle1
    uses2 = !cycle2
    ```
    
    ```ucm
    
    .> add
    ```
    
    ```unison
    usedBy1 n = "hi"
    ```
    
    ```ucm
    .> update
    .> view uses1 uses2
    ```
**transcript output**

    ```ucm
    .> builtins.merge
    
      Done.
    
    ```
    ```unison
    usedBy1 _ = ()
    
    cycle1 _ = !usedBy1
               !cycle2
    cycle2 _ = !cycle1
    
    uses1 = !cycle1
    uses2 = !cycle2
    ```
    
    ```ucm
    
      I found and typechecked these definitions in scratch.u. If you
      do an `add` or `update`, here's how your codebase would
      change:
      
        ⍟ These new definitions are ok to `add`:
        
          cycle1  : 'r
          cycle2  : 'r
          usedBy1 : ∀ _. _ -> ()
          uses1   : r
          uses2   : r
    
    ```
    ```ucm
    .> add
    
      ⍟ I've added these definitions:
      
        cycle1  : 'r
        cycle2  : 'r
        usedBy1 : ∀ _. _ -> ()
        uses1   : r
        uses2   : r
    
    ```
    ```unison
    usedBy1 n = "hi"
    ```
    
    ```ucm
    
      I found and typechecked these definitions in scratch.u. If you
      do an `add` or `update`, here's how your codebase would
      change:
      
        ⍟ These names already exist. You can `update` them to your
          new definition:
        
          usedBy1 : n -> Text
    
    ```
    ```ucm
    .> update
    
      ⍟ I've updated these names to your new definition:
      
        usedBy1 : n -> Text
    
    .> view uses1 uses2
    
      uses1 : r
      uses1 = !cycle1
      
      uses2 : r
      uses2 = !#j1ulmkutk2.1c2
    
    ```

**Comment by stew** [comment]
This one is hurting us constantly in our Remote project since we have a large cycle of code there

**Comment by aryairani** [comment]
Once fixed, the end of the transcript output should be:
```
.> view uses1 uses2

  uses1 : r
  uses1 = !cycle1
  
  uses2 : r
  uses2 = !cycle2
```

**Comment by aryairani** [comment]
@mitchellwrosen and I dug into this on Friday, through some hairy update-propagation code.  The upshot is that updating with cycles is kind of busted, resulting in both this issue and the earlier #2425 issue.

I think we can do a quick fix that I think will solve this for working with _new_ definitions 🤞. Then, a more comprehensive fix for updates in general soon after.

**Comment by mitchellwrosen** [comment]
A question about this one.

Let's say you have the following cycle already in the codebase.

```haskell
even : Nat -> Boolean
even = cases
  0 -> true
  n -> odd (n-1)

odd : Nat -> Boolean
odd = cases
  0 -> false
  n -> even (n-1)
```

Now you pull `even` into a scratch file and give it a different type, so propagation of such an update would fail at `odd` and propagate no further:

```haskell
even : Nat -> Nat
even n = n + 1
```

What do we want the terminal output to be when you save this file?

Currently it would simply say:

```
  I found and typechecked these definitions in ~scratch.u. If you do an `add` or
  `update`, here's how your codebase would change:

    ⍟ These names already exist. You can `update` them to your new definition:

      even : Nat -> Nat
```

I'm wondering if we want to preserve this behavior (because sure, it's true that this `update` could succeed, it just wouldn't even propagate to its own component-mates, and so you'd be left with the old `odd` referring to a now-nameless `even`), or if we want to report something fancier (and perhaps more confusing)

**Comment by ChrisPenner** [comment]
Hrmm, I'd say a good rule of thumb is that an update/propagation step probably shouldn't leave anything nameless, since having names for everything is an invariant most folks will want to hold; so that'd leave:

1. Add `odd` to the `todo` list and mention that some updates failed to propagate, maybe warning that these terms are missing names for the dependency now or something?
2. Leave some name for the old `even` around, so it's not nameless inside `odd`'s. definition; maybe we have a convention for this? Something like `even.outdated`, we could possibly link it to some metadata so it could be cleaned up easily in the future? Not sold on this.
3. Fail the update, tell the user that the component must be updated all at once, and add the relevant pieces of the component to the scratch-file for them.

These are just ideas, TBH I'm not sold on any of them and would like to discuss more.
