### ISSUE TITLE
Merge containers util modules

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#2673]
Right now we have multiple copies of some util modules (e.g. `Unison.Util.Set`, `U.Util.Set`), which exist in different packages and are drifting apart.

I think we should move these into the `unison-prelude` package, as they are just generally useful `containers` utils, which `unison-prelude` already depends on (to re-export the types).

**Comment by ChrisPenner** [comment]
Agreed on moving more things into the Prelude 👍🏼

**Comment by aryairani** [comment]
wdyt about moving them to u.util?

**Comment by mitchellwrosen** [comment]
> wdyt about moving them to u.util?

I think the module naming convention should have a predictable structure. `U` or `Unison` are both good with me. Why `U`, though?

**Comment by aryairani** [comment]
Ah sorry, I meant, to the unison-util package instead of unison-prelude.

As far as the naming, I started using U when there was two of just about
everything during the codebase refactor. I was vaguely planning to move
everything over to the U (for Unison) namespace as we reviewed them, but
then stopped partway because it was taking too long.

In any case, those new packages currently use the U. module naming
convention and have a cleaner package delineation.  The actual name U vs
Unison isn’t important to me (and I agree that they should be consistent)
but currently it helps me distinguish between “new” and “old” packages.

Now this may seem terrible, and it might be terrible, but that’s the
current situation.

**Comment by mitchellwrosen** [comment]
@aryairani Ah, I see. Hmm, is this the motivation for moving these modules into unison-util?

> have a cleaner package delineation

If so - I agree we should strive to have clean delineation for all packages (including "old" and "new") but I think they actually belong better in unison-prelude than unison-util.

unison-prelude is a prelude/base replacement package, which exists basically because the actual `base` has some warts, and doesn't include a lot of core ecosystem types like Text, Map, Set, Vector. 

And importantly, as a base replacement, it should be fairly conservative about transitive dependencies so that our own mini packages and libraries of any scope will be happy to incur them.

unison-util currently contains these Map/Set utils, but also hashing utils, component utils, cache utils, and a couple other things that probably don't qualify as "of general interest to all other packages".

As somewhat of a sin-bin package, it does not have a small dependency footprint by design, and thus anything wishing to use, for example, our own `Set.mapMaybe` will either have to incur the transitive deps of all of the other utils modules in total, or redefine `Set.mapMaybe` inline.

Or put another way, I think unison-util would ideally depend on unison-prelude too, to benefit from the standardized imports and other functionality that it provides.

**Comment by aryairani** [comment]
> unison-util currently contains these Map/Set utils, but also hashing utils, component utils, cache utils, and a couple other things that probably don't qualify as "of general interest to all other packages".

Yeah, good point.

I didn't catch until now that you were moving those out of U.Util too.  I just didn't want to have two homes for the same thing, if we're trying to find a better home for them.
