### ISSUE TITLE
Aliases for remote URLs

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#2698]
## Problem

* Typing long URLs like `https://github.com/ChrisPenner/unison-codebase` is extremely annoying and error-prone.
* As @hojberg and I have been discussing how Share might distribute its code to users it's clear that the actual location and method that the code is hosted with may change over time, and keeping documentation up to date may be a challenge.

## Solution

Aliases for remote codebases.

E.g.

Old way:

```ucm
.> pull git@github.com:unisonweb/share.git:.chrispenner.duration .duration
```

New Way
```ucm
.> pull @share:.chrispenner.duration .duration
```

This also allows us to do nice things like provide "built-in" aliases for things like `base`; which is nice because base versions are tied to a specific UCM version (due to builtins).

So for instance:

```ucm
.> pull @base:.io .base.io
```

Could conceptually expand to the following (with the correct UCM version baked in):

```ucm
.> pull git@github.com:unisonweb/base.git:.releases._M2k.io .base.io
```

If you want to work on `base:.trunk` you can of course just provide the fully qualified path.

As an optional feature we could support setting your own aliases in your `.unisonConfig`:

```
Remotes {
  me = "https://github.com/ChrisPenner/unison-codebase"
  gists = "https://github.com/ChrisPenner/unison-gists"
  myproject = "https://github.com/ChrisPenner/unison-codebase:.myproject"
}
```

```ucm
.> pull @me:.duration .duration
```

```ucm
.> push @myproject .myproject
```

```ucm
.> push.gist @gists
```

---

An alias may resolve to either a git repo, OR a git-repo and namespace prefix.
E.g. `base = "git@github.com:unisonweb/base.git:.releases._M2k"` would allow the use of `@base:.io` to refer to `git@github.com:unisonweb/base.git:.releases._M2k`

---

I'd propose we start with built-in aliases for base and share and see how that goes, then can add user-configurable ones if we like it.

**Comment by pchiusano** [comment]
Exploring a few variations here:

```
pull share/pchiusano/myproject .blah
pull.share pchiusano.myproject .blah
pull pchiusano.myproject .blah
pull share:pchiusano.myproject .blah
pull pchiusano.myproject@share .blah
pull @share pchiusano.myproject .blah
```

This last one seems like the winner - 

```
pull @share pchiusano.myproject .blah
```

The `@share` is interpreted as a function `[String] -> Either (P.Pretty CT.ColorText) [String]` which just interprets or munges the remaining arguments to the command. This replaces the notion of aliases with the notion of modifiers. And it looks pretty! :)

This seems like a one-liner change in `InputPatterns` for the `pull` commands.

We want this for M3 release because it lets us hide the `:v2` branch identifier from the pull command (the "v2" is confusing to the user since they have no idea what that refers to - is it the library version, the unison version, the unison database schema version??)

**Comment by aryairani** [comment]
Ok so we will hack something together for `push`/`pull`, and add a ticket to revamp `InputPatterns`.

**Comment by pchiusano** [comment]
I think @aryairani has me convinced that for the short term we just go with something like `pull share://pchiusano.myproj blah`. (This could even do autocomplete using the shallow namespace listing endpoint.)

Eventually this can just become the default, and the old pull will require `pull.git` or something.

The modifier idea might be cool to explore for later. But I kinda think I want just a more general ability to define custom commands.

**Comment by aryairani** [comment]
WDYT about if we add both `pull.share` and `pull.git` and for the time being leave `pull` as an alias for `pull.git` and then eventually switch it to be an alias for `pull.share`, and never introduce `share://`?

**Comment by pchiusano** [comment]
I'm cool with that.

**Comment by aryairani** [comment]
Rereading the original proposal I like that better (doesn’t change the number of arguments), although I think presets should have a different namespace, like `@@base` or `@@share`, wdyt.

We can independently still split off a separate command for pushing to share vs to arbitrary git repo, and that new command could become the default later.

**Comment by pchiusano** [comment]
I really dislike `pull @share:.blah`, particularly the `:.` business, which is super easy to screw up, is annoying to type, and looks bad. :) Seriously, imagine having to explain to someone why they have to write `:.` there: "well, it's because technically that's expanding to a string that's going to become the prefix of a git url plus a unison path specification, so therefore..."

like, just no! When installing from share, I really want to specify the absolute minimum info, with no extraneous stuff or weird punctuation. `pull.share` seems pretty good for this (or maybe `install`?)

Having aliases or modifiers as a general facility does seem like a good idea for other reasons, but it's not getting us to where I'd like for the "painless pulling from share" use case.

**Comment by hojberg** [comment]
Given we now have projects, I don't think we need this anymore.
