### ISSUE TITLE
Improve the update workflow for conflicting edits

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2711]
This came up when @ceedubs and @stew had a conflicting edit to a type, `Foo` and then some further edits on top of that. The `todo` output included a big list of all these other conflicts, but most of the other conflicts had one of the versions of `Foo` as a transitive dependency.

The user wants to know: what's the thing I actually need to act on. We can tell them that there's some transitive conflicts (just a count) but don't spam them with a big list of them. 

Also specifically for a type conflict, you *always* want to first resolve conflicts on any functions that do direct pattern matching on the type or which directly call the constructor of that type. Once those are resolved, autopropagation can get a lot farther. I don't think the "what to work on first" output of `todo` properly reflects this - it looks for immediate dependents of the updated thing, but some of the immediate dependents might just mention the type in their signature. That doesn't matter, we want to update the things that actually pattern match or call a constructor.

When you go to resolve the conflict, ideally you can just dump both versions to the scratch file, resolve them, and assign the name `Foo` to the resolved version. Right now this doesn't work because you can't an entry to a path for `Foo` if `Foo` is currently conflicted. Maybe just relax that restriction?

**Comment by pchiusano** [comment]
Related #2248

**Comment by aryairani** [comment]
Things from call w/ @ceedubs:
1. When `update` a term that has a name conflict, maybe just update both of them instead of throwing an error. Make sure transitively propagated name-conflicted terms that are updated to be the same on both sides of the dependency divergence reconverge to the same hash and same term without craziness.
2. We are missing 3-way merge for definitions — so ucm presents a lot of edit conflicts that could potentially be automatically resolved — or somehow help the user do it manually.
3. Concerns about non-type-preserving edits / pattern matches in the presence of edit conflicts; does this work?  We need to construct an example and then to see how it works out.

**Comment by ceedubs** [comment]
For what it's worth I would mark 2 as a low priority. I'm happy to resolve it manually if UCM will propagate the change for me.

**Comment by aryairani** [comment]
Done in #3375

**Comment by mitchellwrosen** [comment]
Note: this comment from @pchiusano wasn't addressed by #3375 

> Also specifically for a type conflict, you always want to first resolve conflicts on any functions that do direct pattern matching on the type or which directly call the constructor of that type. Once those are resolved, autopropagation can get a lot farther. I don't think the "what to work on first" output of todo properly reflects this - it looks for immediate dependents of the updated thing, but some of the immediate dependents might just mention the type in their signature. That doesn't matter, we want to update the things that actually pattern match or call a constructor.

But the "make `update` able to resolve a conflicted term" is fixed. Should that idea be pulled out into a different ticket?

**Comment by ceedubs** [comment]
@mitchellwrosen Thanks a lot for working on this! I created #3533 to track the other change.
