### ISSUE TITLE
Dynamically rendered pretty source for codebase repo format

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#282]
Hi, this is a quick writeup of something we are going to need, but am not sure the best way to do it yet. Idea is that for each hash / referent in the codebase, we'll have a `<hash>/compiled.ub` and a `<hash>/index.html` where `index.html` has nicely pretty-printed and hyperlinked source / docs.

* __The dream:__ You write your code, and at all times the codebase is browsable as a gorgeous, hyperlinked website, which you also use when developing locally. Simply by pushing to GitHub, this hyperlinked website is now on the web and viewable by anyone, without you having to take any extra steps. The codebase repo format also doubles as the format for publication, so there's no extra step needed to "publish" your code. Your code is already published by virtue of you pushing it to GitHub.
* __The problem:__ The names of things are not fixed. We can't just generate static HTML for a definition like `factorial n = product (range 1 n)`, since the names of `product` and `range` will differ depending on what branch we're viewing this hash from. We could imagine "baking" the names in, but that's pretty poor. We've talked about just doing the baking at certain times, like when you produce a "release". Also meh.

Here's the solution: for each definition, we generate a JS file (the "rendering file") which is basically a `Relation Referent Name -> HTML`. It's a function which given the names produces a HTML rendering of that definition. We would produce this at the same time as we create the binary file for the definition itself. This file never changes, so hyperlinks between these files work fine. When hyperlinking to another file, you pass along the same `Relation Referent Name`.

Whenever we write out a `Branch` file `fj09sdfjs.ubf`, we also write out `fj09sdfjs.names`, which has that same `Relation Referent Name` which is expected by the rendering files. And finally, to tie it all together, when creating a branch, we also create an `index.html` for that branch. The `index.html` file never changes, it's just a shell. For a Unison codebase repo at `<url>`, you can just visit `<url>/branches/radBranch23?asOf=fj09sdfjs` to get a hyperlinked view of the code as of that version of the branch.

### Difficulties

The difficulty is that because the names are dynamically chosen, we don't know the widths of anything in advance, which means we can't do pretty-printing accurately. We also can't do things like column alignment, as that depends on knowing the widths of things in advance. 

I'm not sure the best way around this. Here are a couple ideas:

* GHCJS to just compile our existing pretty-printing code to JS. Drawback: want the index.html file to be lean and mean, and GHCJS tends to produce huge output. Like it would not be cool to have a 5MB JS file for every single Unison hash. Also I find working with GHCJS to be annoying.
* Port the whole AST and the pretty printer to PureScript. I think this is a nonstarter, too much duplication, and PureScript lacks some features (view patterns) that are kinda crucial to making the pretty printer not be a total mess.
* Have the pretty printing produce some sort of intermediate representation, call it `Pretty0`, which doesn't need to know about the term / type AST but which still has the basic pretty-printing structure expressed. Then the PureScript would just need a port of the `Pretty.hs` module (not really the whole module, just the type itself and the rendering function which is like 30 LOC total), and a function from `Pretty0` to `Pretty`. I feel like this is probably the right answer. The `Pretty0` type just needs to be figured out.

@noahhaasis I was thinking this could be a good first project for you once we get it sorted out exactly how we're doing it.

**Comment by atacratic** [comment]
I haven't worked with GHCJS so can't really form a view on that vs the `Pretty0` option.  
* Maybe artefacts produced by GHCJS only need to be loaded into the browser once, rather than for every new hash you view?  I got a 3 second load time on the js resources when I browsed https://github.com/ghcjs/ghcjs-examples.  3 seconds just at the start of a session wouldn't be so bad.  
* The fact that GHCJS gives us code sharing between the browser and the rest of the tooling, means we have a smoother path to adding further IDE-like bells and whistles to the browser-based UI, if we felt like it (hover over anything to display its type...)  

I guess in the GHCJS option, we don't need the per-hash rendering file - we can just have a js artefact that converts .ub (and some name info) to html.  That's probably what you meant.  

An important early step will be to create a mock-up github repo containing toy examples of these various files, and see if it really renders properly, and if following hyperlinks really works.  

This might be off-topic, but I think a system which only shows you one function definition at a time wouldn't be very nice to use.  People will want to be able to 'pin' definitions into their 'buffer', add dependents, drag to reorder.  I think that going in that direction is consistent with what you've written, because multiple rendering files can be involved in rendering a single page, but wasn't entirely sure.  

Is it possible that in the future we will feel drawn to extending this code viewing UI into (a) a live execution environment, (b) an IDE?  Might those be good directions, or do we think we'll want to keep the code view UI as a bare-bones thing that lets people see their code when they browse github, and save any broader UI efforts for something else, maybe not web based?

**Comment by pchiusano** [comment]
@atacratic thanks for the comments. Still noodling on this. 

A few thoughts: overall, this is really about reaching or exceeding parity with existing workflows. With existing workflows, you can view your code on GitHub, that's useful, and it would be unfortunate if we lost that! But in the process of preserving that expectation, we have some easy wins: we can make the code hyperlinked, autoformatted, and with names chosen dynamically based on the viewing branch or their preferences, so that's nicer than what people have now. Anything beyond this I'd probably consider out of scope unless it's totally trivial to do.

Am leaning more strongly toward the `Pretty0` solution (and avoiding GHCJS). It's nice and simple and I don't anticipate much code duplication. I realized the pretty printing process can be separated into two steps - there's producing the document (this is the thing that needs to know about Unison and has a huge number of dependencies on the Haskell code), and there's resolving the names (this is actually a really dumb, simple process with 0 dependencies). Currently we do both at the same time, but you could imagine just doing the first step, and then leaving the name resolution and actual rendering for a given width for later. On the JS / PureScript side, __the viewer becomes a dumb thing that doesn't know anything about Unison__, it's just taking a document with some unresolved names, and it resolves those names and renders it to the DOM at whatever width. It's simple, or rather, any complexity is more around having dynamic JS goodies.

> This might be off-topic, but I think a system which only shows you one function definition at a time wouldn't be very nice to use. People will want to be able to 'pin' definitions into their 'buffer', add dependents, drag to reorder. I think that going in that direction is consistent with what you've written, because multiple rendering files can be involved in rendering a single page, but wasn't entirely sure.

Totally. I could imagine the viewer as a more dynamic JS widget. It shows the current hash, and clicking on any dependency opens it up in the same page (above or below the current definition), with an `x` button to close and a pop out button to open in a new tab. At the bottom there could even be a `[+]` button which if you click brings up a search box letting you look for any other definition?

> Is it possible that in the future we will feel drawn to extending this code viewing UI into (a) a live execution environment, (b) an IDE? Might those be good directions, or do we think we'll want to keep the code view UI as a bare-bones thing that lets people see their code when they browse github, and save any broader UI efforts for something else, maybe not web based?

That's going to be an separate effort I'd say that will have to work quite differently so I wouldn't say that is a big consideration. At most the viewer will have a link "open in IDE" or something which could just embed a URL that can open a definition for editing in some other JS widget or in a native app of some sort.

**Comment by atacratic** [comment]
Great, all makes sense, and the `Pretty0` direction is good.

**Comment by pchiusano** [comment]
Update: started working on this with @aryairani but hit a snag - there are some layout decisions that need to know the names, like whether function application is shown infix or prefix (which have totally different layouts). The question is what to do about this.

For each such case, we can make it a Pretty0 constructor. It can be resolved during conversion to Pretty, once names are available. My concern is that Pretty0 is going to accumulate too many weird special cases. I’d like to avoid having a “binary operator” constructor in Pretty0, for instance. Before deciding how to proceed, I want to audit how many such cases we have and think about if there’s some more generic way to express them. If it’s getting too ugly, will reconsider the GHCJS option.

**Comment by pchiusano** [comment]
FYI, here is latest WIP: https://github.com/unisonweb/unison/blob/topic/pretty1/parser-typechecker/src/Unison/Util/Pretty.hs

**Comment by pchiusano** [comment]
I think we are going to pick this up again, some realizations:

- infix vs prefix decision could be made up front, even if the names aren't known.

**Comment by ceedubs** [comment]
Wow a lot has changed in the past few years! A codebase is now a SQLite file instead of a collection of definition files. [Share](https://share.unison-lang.org/) now exists and renders beautiful code and docs. It's still possible to publish Unison code to a git repo, but I think that we've given up on this approach supporting a nice graphical UI. I'm going to go ahead and close this issue out, but if there are pieces that have been missed, feel free/encouraged to open new issues that apply to the modern incarnation of Unison.
