### ISSUE TITLE
Pretty-printing should emit `use` statements rather than needing FQNs everywhere

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#285]
Just tracking this as an actual issue. A proposed algorithm described here:

https://github.com/unisonweb/unison/pull/269#issuecomment-444998664

@atacratic if you are working on this you can assign it to yourself :)

**Comment by atacratic** [comment]
Just having a first think about this now.  Thanks for proposing spec ideas and algorithm.

In terms of spec:
- I'm quite keen on minimizing the scope of the use statements (i.e. pushing them deeper)
- I don't like depending on shadowing.  Would be easy to misread the code by not noticing a use statement intervening between the call site and the use statement you noticed.  
- Not even sure I like picking a 'winner' based on number of occurrences.  If there are two names with the same suffix kicking around then maybe best to always be specific to avoid reader confusion (at least until you get into a subtree where only one remains).  Also picking a winner has a discontinuity in how the code looks at 50:50 - is that annoying?  Not sure about this though.  (Also depends on TDNR question below, since (say) leaving `Nat.+` fully qualified just because you use some other `+` in the same function would be rubbish.)

Question: do use statements always refer to a single name?  Or can they bring a whole namespace into scope (i.e. all the names that share some suffix.)  (And probably there are follow-on questions to do with multi-level names, ones that have have more than one . in them.)  

TDNR: would we ideally be trying to reverse TDNR, so to output a `+` rather than a `Nat.+` if we know that the types will disambiguate it?  Do we have type provenance info that could help the pretty-printer with that?  e.g. the type of this function was deduced from the value to which it was applied, which was in turn found by checking the type declaration for the top-level definition, so the same should be true next time round after print-and-slurp.  The hazards would be in cases when TDNR only worked because of some other full qualification that was present elsewhere, but which we might decide to drop on printing.

The above paragraph has the flavour of 'come on, we don't need this...' but on the other hand if TDNR was worth it for parsing hand-written code, why wouldn't it be worth it when parsing pretty-printed code.  Outputting a load of 'use Nat.+' and the like just for basic arithmetic expression code would be uncool I think.

**Comment by pchiusano** [comment]
Hey @atacratic -

Yeah, to start let's avoid shadowing. Just push the imports down until they uniquely identify the suffix without any shadowing (might be never, and that's ok), and put the imports as deep in the tree as possible while still covering all the use sites. I'd also say don't rely on TDNR for now - the resulting file should not require any TDNR to successfully typecheck.

I guess we haven't decided exactly the semantics of imports, but here's a keep-it-simple proposal:

* `use XYZ blah` brings `XYZ.blah` into scope, bound to the name `blah`. More generally, `use` is followed by a FQN prefix, then the local suffix. Concatenate the FQN prefix with the local suffix, with a dot between them, and you get the FQN.
* `use XYZ blah qux` is equivalent to the two statements (and this generalizes for any N symbols):
  * `use XYZ blah`
  * `use XYZ qux`
* This syntax works the same even if `XYZ` or `blah` have dots in them, so:
  * `use Util.External Chris.Pretty` brings `Util.External.Chris.Pretty` into scope, bound to the name `Chris.Pretty`.
* That's it. No wildcard imports, imports that do renaming, etc. We can consider adding some features like this later.

**Comment by pchiusano** [comment]
Exciting progress! Looking forward to trying it out.
