### ISSUE TITLE
Add (builtin) capability of running shell commands.

### ISSUE THREAD

**Issue by mechadense** [unisonweb/unison#2931]
As just one rather specific example this would be needed e.g. for
starting up some OpenSCAD code via shell that was 
formerly generated and written to file by unison.

**Comment by aryairani** [comment]
Maybe something like this to start:
```unison
readProcessWithExitCodeSource : FilePath -> [Text] -> String ->{IO} (ExitCode, String, String)
--                             executable    args     stdin          exitcode  stdout  stderr
```
Lots of inspiration here: https://hackage.haskell.org/package/process-1.6.14.0/docs/System-Process.html

**Comment by mechadense** [comment]
Signature looks good.

I don't understand the reasoning behind the command name 
"readProcessWithExitCodeSource"
Why "read" at front and "Source" at the end?
Maybe something shorter that one would likely be to search for 
like e.g.: "executeShellCommand"?

**Comment by LoganDark** [comment]
IMHO, you should properly differentiate between running *shell* commands and running *system* commands. *Shell* commands are a single string, parsing sigils like `;`, `||` and `&&`, redirections, pipes and so on, and splitting arguments (requiring escaping). *System* commands simply start a process with the specified arguments - not requiring escaping or anything like a shell would.

Also, Windows does not have one _shell_ - it has CMD.EXE, as well as (various versions of) PowerShell, and it would be unreasonable to choose one for the user, especially since both of them are nearly impossible to escape for. CMD.EXE's syntax is entirely undocumented (and buggy, for backwards-compatibility reasons) and PowerShell is not much better. This issue does not exist on any other operating system but it is worth bringing up as some people are indeed stuck with Windows.

It should be up to the user to invoke the shell explicitly (`/bin/sh -c "command here"`) if they need a string to be parsed as a shell command; I think Unison would gain the most by exposing system commands directly and making it clear that it is a *system* command and not a *shell* command.

**Comment by pchiusano** [comment]
A simple asynchronous API: 

```
io.exec.impl : [Text] ->{IO} Either Failure ProcessId
```

but might want something that returns `Handle` for standard in / out to support redirect, and a process id, to be able to kill the process or whatever.

**Comment by hojberg** [comment]
This came up during this weeks community day. It would be awesome to get it prioritized. Seems simple to do?

**Comment by aryairani** [comment]
> A simple asynchronous API:
> 
> ```
> io.exec.impl : [Text] ->{IO} Either Failure ProcessId
> ```
> 
> but might want something that returns `Handle` for standard in / out to support redirect, and a process id, to be able to kill the process or whatever.

Let's at least split out the executable from the args.  I'm not sure if it's possible to pass in a ProcessId and get back some handles after the fact, but it's worth considering.
