### ISSUE TITLE
Codebase editor sometimes prompts for input twice

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#294]
Note the printing of the prompt twice:

![image](https://user-images.githubusercontent.com/130916/50990869-43d8f580-14e1-11e9-8775-34f245eb1d2d.png)

The second prompt appears about a second after the first one.

**Comment by francisdb** [comment]
I'm looking into this one but some things are not clear so I am somewhat stuck

Reproducer:
1) a watch expression is updated / triggered
2) the user requests a `add` or `update`

The request in turn requests a `SlurpFileI` which normally bails out if there are no changes. But in this case the `LoopState` refers to the file that had the expression update. This causes the branch to be updated (that .unison/branches/master/###.ubf file keeps on growing after every `add` request). Which in turn causes the branch watcher to pick up the branch update causing the second (async) prompt.

So my question is should these watch expressions cause an update on the branch or are they only for debugging and should this LoopState not contain the update?

Could this be related to a missing filter here?
https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/UnisonFile.hs#L124

**Comment by pchiusano** [comment]
@francisdb ahh, this is very good research. Thank you!

A couple ideas I want to try:

1. Let's not update the `Branch` in the LoopState, until the `add` completes. If the `add` is a no-op, there shouldn't be any branch file change.
2. We shouldn't respond to a branch file update that was generated by the user interacting with the `unison` tool. The branch file update events are just supposed to catch branch files that arrive externally (like if you did a `git pull` outside the `unison` tool). I thought we already had some logic for this but I imagined this or it's just wrong...

Will take a look shortly.

**Comment by pchiusano** [comment]
@francisdb okay, just pushed a fix. You can take a look at the 2aeae34 commit. The fix was two parts:

1. Don't edit the branch if there's no actual change to it. This was the change to `Branch.modify`.
2. Avoid generating an event for file writes of the current branch. This required updating the command line app state BEFORE doing the file write, and then having the branch file watching logic be aware of the current branch so it could skip generating an event for things it already knows about.

Thanks again!

**Comment by francisdb** [comment]
Good to see my research helped :-)
