### ISSUE TITLE
`unison transcript unison-src/transcripts-round-trip/main.md` is failing on Windows

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2940]
````
```unison
    docTest2 : Doc2
    docTest2 =
      {{ # Full doc body indented

        ``` raw
        myVal1 = 42
        myVal2 = 43
        myVal4 = 44
        ```

        ``` raw
        indented1= "hi"
        indented2="this is two indents"
        ```

        I am two spaces over }}

  You can edit them there, then do `update` to replace the
  definitions currently in this namespace.

```
````
````
```ucm
.> load scratch.u

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:

    ⍟ These names already exist. You can `update` them to your
      new definition:

      docTest2 : Doc2

```
````

**Comment by ChrisPenner** [comment]
Investigated further, this is caused by carriage returns being inserted at the end of lines within codeblocks when pretty-printing on windows.

We'll probably want to either strip those out when parsing, or avoid printing them in the first place (but that might wreak havoc for some windows text editors).
My thought would be to strip them out when parsing and add them back in when printing.

Alternatively we can represent the lines of code-blocks semantically in the Doc AST and avoid the problem altogether, but that's likely more work than its worth. 🤷🏼‍♂️ 

I'll dig into the parsing and printing code and see what's easiest.

**Comment by aryairani** [comment]
There should be a text mode for the file handles that does the right thing automatically (i.e. on windows, turns CRLF into LF on read, and turns LF into CRLF on write; and does no translation on unix?).  We don't want to bake the solution into our parsing rules.

**Comment by ChrisPenner** [comment]
Ah, yeah that's a much better solution. I'll adjust the file Handle newline mode in the parser.
