### ISSUE TITLE
Weird decompilation of this program

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2985]
````
x = {{

@typecheck ```
x = 42
v = (Value.value x : base.Value)
bs = (Value.serialize v : Bytes)
Right v = Value.deserialize bs
Value.load v
```

}}
````

doing `display x` gives

```
        x = 42
        v : base.Value
        v = value x
        bs : Bytes
        bs = Value.serialize v
        Right bs v = Value.deserialize bs
        Value.load v
```

Not super urgent

**Comment by dolio** [comment]
I don't understand what's wrong in this example.

**Comment by ceedubs** [comment]
@dolio the `Right bs v = Value.deserialize bs` doesn't look right to me. The `bs` shouldn't be on the left, should it?

**Comment by pchiusano** [comment]
Right, what @ceedubs said.

This may just be a pretty-printer bug with the rendering of some destructuring binds - this could be verified just by adding that definition to the codebase (outside a doc) and seeing what it looks like when `view`d.

**Comment by dolio** [comment]
So, I think this program might not be what you think.

    Right v = ...

is defining a function (that is never used), because you don't have the pattern in parentheses. The `bs` argument is getting added because decompilation information happens after the enclosing step, I think. So the decompilation output is roughly equivalent to the input.

**Comment by ceedubs** [comment]
Ahh. Tricky.

**Comment by pchiusano** [comment]
Ah! Okay, I'll close.
