### ISSUE TITLE
Improve error message when using keyword

### ISSUE THREAD

**Issue by 3nigm4** [unisonweb/unison#3036]
```
.> pull https://github.com/unisonweb/share.git:.unison.website.learn.labs.wordle.solutions.stubs .local.namespace 
I expected an identifier but found local.namespace
.>
```

Hey, I found this in a tutorial and I was very confused, as I am completely new to unison. Maybe the error message could point out why this failed. @pchiusano said "namespace" is a reserved keyword!?

Anyway have a great day!

**Comment by aryairani** [comment]
I think this specific situation can't come up anymore, if only because we can't pull into a subnamespace anymore. But here's the new error message for a similar situation:

```
.> move frog namespace.frog

  1:10:
    |
  1 | namespace.frog
    |          ^
  reserved word: namespace
```

So although I still think there's room for improvement, I will close this for now; but feel free to open another ticket if you run into an issue like this in the future.
