### ISSUE TITLE
Make ucm history length configurable

### ISSUE THREAD

**Issue by dantb** [unisonweb/unison#3053]
Might only be my workflow, but I tend to max out shell history lengths for everything. Means I can reverse search some substring of a command I knew I did at some point, even if it was years ago. Found myself wanting it for `ucm` so thought it might be useful here too!

**Comment by dolio** [comment]
This actually can be configured already, because ucm is using a library for the command line handling that has its own configuration (similar to readline). On unix-like systems, at least, the configuration is in `~/.haskeline`. I recently put the following in mine:

    maxHistorySize: Just 2000
    historyDuplicates: IgnoreAll

This gives you 2000 lines of history, and only stores one copy of an identical command in the history (so, `foo` then `bar` then `foo` results in a history of `bar` then `foo` I imagine).

Other options are here:

https://github.com/judah/haskeline/wiki/UserPreferences

**Comment by dantb** [comment]
Thanks @dolio this worked on Mac. I didn't have the file but creating it with those lines seems to allow `.unisonHistory` to go higher
