### ISSUE TITLE
Value.load can turn anything into anything

### ISSUE THREAD

**Issue by iacore** [unisonweb/unison#3077]
Try to run this code with only builtins.

```unison
plus0_deser : '{IO} Either [Term] Nat
plus0_deser = '(load plus0_code)


plus0_code : Value
plus0_code = value plus0


plus : Nat -> Nat -> Nat
plus a b =
  use Nat +
  a + b


main : '{IO} ()
main =
  'let
      (Right a) = !plus0_deser
      n = plus a a
      trace "" n
```

```
.> run main

  dumpData: bad closure: PAp (CIx #aut6j 292 65536) [] (fromListN 1 [DataU1 ##Nat 983040 0])
  expected type: ##Nat
```

**Comment by pchiusano** [comment]
Value.load is an unsafe operation, by design. It is mainly used as a low level primitive for supporting distributed execution, in conjunction with Value.serialize.

Like other languages, Unison doesn’t retain type information at runtime (especially not full polymorphic type instantiations), so this function can’t really do anything else than to just trust the programmer.
