### ISSUE TITLE
Parser should support hash-qualified names

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#315]
This is so that you can write code which references hash-qualified definitions and have it still parse / typecheck.

Needs some thought: what about viewing a hash-qualified definition? What happens when you parse and typecheck it again? I’d say it should probably strip out the hashing from the name (and tell the user it’s done so).

**Comment by aryairani** [comment]
No, instead of stripping them out, the output should warn of use of / list deprecated references.

**Comment by pchiusano** [comment]
@aryairani - Agree on the warning, but I was talking about if the name of the definition itself is hash qualified, as in, the thing to the left of the = sign. You get this when viewing something conflicted..

**Comment by pchiusano** [comment]
Clarifying with an example:

```
edit foo#2823
```

And that dumps a definition to your file...

```
foo#2823 = 42 + 1
```

which you then edit (`42 + 2`) and then `add`.

Maybe we just don't support this, or put the `#2823` as a comment?

**Comment by pchiusano** [comment]
Arya: "Make sure to look up in oldnames too if needed."

**Comment by aryairani** [comment]
Thought on implementation: have the lexer generate hash qualified tokens. Take these tokens, produce a `Set HashQualified`, use some magic function `Set HashQualified -> Branch m -> m Names0` which produces a `Names0` covering the input, by looking through the `Branch` history.

Side note: I'm thinking we will have multiple uses for a function that folds through causal "merge" nodes in parallel (instead of recursively following one path back to the root), with early termination after some condition, such as having found all the things you're looking for.

**Comment by aryairani** [comment]
I'm currently implementing `findHistoricalNames0 :: Set HQ.HashQualified -> Branch m -> m Names0` for #535.
