### ISSUE TITLE
Pattern match guard expressions don't have access to variables introduced by the pattern

### ISSUE THREAD

**Issue by francisdb** [unisonweb/unison#327]
As I understood unison should support guards on a pattern match but this does not seem to be working

```
f blah =
  case blah of
    x | x == "woot" -> false
    y | y == "foo" -> true
```

```
master> 
I'm not sure what x means at line 135, columns 9-10

  135 |     x | x == "woot" -> false

Whatever it is, it has a type that conforms to Text.
```

**Comment by pchiusano** [comment]
@francisdb good catch. I'm changing the title of this issue. It looks like the guard doesn't have access to the variables introduced by the pattern, which is a bug.

Unrelated - there's no polymorphic `==` yet, so I'm not sure this code would typecheck unless you were to put a signature on it which let Unison know the type of `blah`.

**Comment by pchiusano** [comment]
@francisdb you might be able to take a crack at this one, though it might get tricky if it turns out there are type checker changes needed (I suspect not though). 

If you look at the [`matchCase` parser](https://github.com/unisonweb/unison/blob/master/parser-typechecker/src/Unison/TermParser.hs#L88-L93), which parses a single `pattern -> body` element of a `case` expression, there seems to be a bug. The `guard` which is parsed does not have the variables bound which are introduced by the pattern, like the body of the matchCase does (that `ABT.absChain' boundVars t`) expression. The fix may be as simple as just inserting that same `absChain'` call there. If you take a crack at this and it turns out to be more complicated, involving typechecker changes, let me know. :)

Also fyi, a bit of background on [how abstract binding trees encode pattern matching](http://semantic-domain.blogspot.com/2015/03/abstract-binding-trees-addendum.html) which might be interesting reading.

**Comment by francisdb** [comment]
pr will be on it's way soon
