### ISSUE TITLE
generally troubleshoot stew's file lock issue

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3330]
https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1660673968753289

/cc @stew

**Comment by ChrisPenner** [comment]
We’re doing a silly thing right now where we write to files within the pretty printer, which we shouldn’t do, but also where we pretty-print then append each definition one-at-a-time; we should print them all, append them all together, then make a single scratch-file edit.

**Comment by ChrisPenner** [comment]
Though as Stew realized, there’s also the issue here that pretty printing for edit (and view, etc….) is waaaay too slow

I have a few ideas to speed those up, but the fastest way would just be to limit the names they use to the current namespace, we’ve been putting it off for a while, but I think it’s probably been long enough now?
So if folks are okay with fully committing to self-contained namespaces I can make that change.

**Comment by aryairani** [comment]
The evidence is lost to slack, but we can revisit if it recurs.

**Comment by ChrisPenner** [comment]
Yeah I think part of this was partially fixed by moving IO mostly out of the pretty-printer anyways 👍🏼
