### ISSUE TITLE
Share API: Project Fav - `PUT /users/:handle/projects/:project-slug/fav`

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#3385]
Toggle the project favorite status on/off (heart icon). Requires logged in user.

**Endpoint:**
```
PUT /users/:handle/projects/:project-slug/fav
```

**Response body**
```
Empty
```

**Comment by ChrisPenner** [comment]
I think you're missing a Request here, but I'll suggest:

```
{
  "isFaved": bool
}
```

**Comment by hojberg** [comment]
The intention was to include that in the project endpoint result.

**Comment by ChrisPenner** [comment]
Oh, is this API meant to just toggle the state from what it is right now? I think I just assumed that `PUT` was always declarative, but I'm second guessing that now.

But also I think an explicit `PUT` where the frontend specifies what declaratively what state the user has set is maybe a better choice here; since if the user clicked an un-lit "heart" then they wanted to 'fav' the project regardless of what the server's state is, if they already fav'd it in a different tab and this one was out of date we wouldn't want to un-fav it and show the user that the heart is still unlit after they just clicked it.
