### ISSUE TITLE
misleading error when using `::` instead of `:` in term annotation

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#360]
This program
```haskell
x :: Nat
x = 1
```
produces this error
```
Token {payload = WordyId "x", start = Pos 1 1, end = Pos 1 2} :| []
/Users/arya/unison/unison-src/tests/solitary-annotated-def.u:1:1:
unexpected x
expecting ability, effect, or use
    1 | x :: Nat
```
Would be nice if the error pointed to the `::` rather than the `x`.

**Comment by pchiusano** [comment]
It's trying to parse that as the definition of an operator, `::`, as in:

``` haskell
hd :: tl = Cons hd tl
```

... which would be a perfectly fine definition. I guess it's not until the `x` that it realizes "oh, this isn't defining an operator `::`. Seems like the newline and virtual semi would be enough to realize the problem at the top level. But note that this parses fine (but isn't what you expect):

```
foo x = 
  x :: Foo -- parses as an action
  x = 42 -- followed by a separate declaration
```

**Comment by pchiusano** [comment]
This could probably use some wordsmithing and the whole `PrintError.hs` file needs cleanup and moving away from manual wrapping, but parser now detects this as a custom error. It's a special case of the more general error of there being a top level expression, rather than a binding, watch expression, etc. Here's the errors:

<img width="940" alt="Screen Shot 2019-04-27 at 12 34 04 AM" src="https://user-images.githubusercontent.com/11074/56844796-47bc3800-6884-11e9-8bb7-765a67d2c705.png">

<img width="1014" alt="Screen Shot 2019-04-27 at 12 31 20 AM" src="https://user-images.githubusercontent.com/11074/56844798-57d41780-6884-11e9-8520-32840dc17240.png">

Note that due to the thing I mentioned [in my comment above](https://github.com/unisonweb/unison/issues/360#issuecomment-481060432) we can't get the same custom error inside of a block, since expressions and bindings are allowed within a block.

**Comment by aryairani** [comment]
Those screenshots look good
