### ISSUE TITLE
discrepancy between getTempDirectory and createTempDirectory results

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3622]
`getTempDirectory.impl` returns a trailing slash, but `createTempDirectory.impl` does not.

```
main = do
  trace "getTempDirectory.impl" !getTempDirectory.impl
  trace "createTempDirectory.impl testing" (createTempDirectory.impl "testing")
```

```
trace: getTempDirectory.impl
Right
  "/var/folders/4z/f583hmpd7f5dcq_4hc85bq8r0000gn/T/"
trace: createTempDirectory.impl testing
Right
  "/var/folders/4z/f583hmpd7f5dcq_4hc85bq8r0000gn/T/testing-9f939adbe93e1185"
```

This is troublesome, because if you do something like `FilePath (toText !getTempDirectory ++ "foo")` then you will be working in the `foo` subdirectory but if you swap `!getTempDirectory` out for `createTempDirectory "testing"` then you will be referring to a non-existent directory like `/tmp/testingfoo` instead of `/tmp/testing/foo`.

My inclination is that `getTempDirectory.impl` should _not_ append a trailing slash. But either way is probably fine if they are consistent.

Separately we might want a helper `FilePath./` function, because it's cumbersome to do combinations of `toText`, `++` and `FilePath`. This function could potentially even detect the presence of a trailing slash and do the right thing.

**Comment by ceedubs** [comment]
Here is an implementation of the helper that I suggested. I plan on submitting some proposals for base soon and I'll try to remember to include it:

```
(up.FilePath./) : FilePath -> Text -> FilePath
(up.FilePath./) base suffix =
  baseText = FilePath.toText base
  separator = if endsWith "/" baseText then "" else "/"
  FilePath (baseText ++ separator ++ suffix)
```

**Comment by hojberg** [comment]
@dolio the suggested plan is to change the builtin to never include a slash on the end.

**Comment by dolio** [comment]
The primops are just wrapping some underlying functionality. I can add post-processing, but encouraging something like `/` is probably a better general solution. The Haskell library has a similar operator, `</>` which is smarter about combining file paths than just concatenating strings.

For instance, if `afp` is an absolute file path, like `/usr/bin`, then `fp </> afp` is the same as `afp`, because its behavior is specified to be that `fp0 </> fp1` is equivalent to using `fp1` while `fp0` is the current directory, and absolute paths don't depend on the current directory. It also avoids having duplicated slashes, of course.

I don't know if that exact logic is desirable for us, but I think using something with built in separator logic is better than relying on the particularities of what the primops return. (Also, it appears that `createTempDirectory` uses `</>`, so the behavior of the latter will affect the former.)

**Comment by ChrisPenner** [comment]
@ceedubs  will add a 'smart' filepath concatenation primitive to base
@dolio  will remove the trailing slash from the builtin.

We'll likely need an OS dependent builtin for filepath separator in the future, but this will do for now.
