### ISSUE TITLE
Text.take returns empty string for n > maxInt

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3660]
I'm guessing that this is an issue of a an unsigned Nat being treated as a signed integer in the builtin/runtime.

```
    18 | > Text.take (truncate0 maxInt) "abc"
           ⧩
           "abc"
  
    19 | > Text.take (truncate0 maxInt |> increment) "abc"
           ⧩
           ""
```

**Comment by dolio** [comment]
Yeah, that's what it's going to be.

I'm wondering what to do about this, though. It's actually possible to build lists bigger than `maxInt` if you're clever enough, but the underlying implementation will also be confused about how big they are (because it's using a signed integer, and doesn't check for overflow). So maybe I should just check if I see this case and return an identical list? Because I'm not sure any operation would reliably work in that case.

**Comment by pchiusano** [comment]
Probably the right move is to have the `Text` / `Rope` type use `Word64` for sizes. Since they're represented as separate chunks, I don't think it matters if they underlying chunk type uses `Int`.

I don't think we have to worry about text that's bigger than `maxInt`. That's over 9 thousand **petabytes**.

**Comment by dolio** [comment]
Oh yeah. I was actually testing out squences, though, which have the same issue, and we can't really change their implementation.

**Comment by ChrisPenner** [comment]
@dolio  will change the implementation to behave like `id` for Nat's which are greater than maxInt.
