### ISSUE TITLE
Share - Clicking the Join type on my draw library loads up Doc from base

### ISSUE THREAD

**Issue by alvaroc1** [unisonweb/unison#3706]
Go to:
https://share.unison-lang.org/@alvaroc1/p/code/latest/namespaces/public/draw/main

And click the `Join` type, which loads:
https://share.unison-lang.org/@alvaroc1/p/code/latest/namespaces/public/draw/latest/;/types/Join

The UI loads up `Doc` from base.

**Comment by hojberg** [comment]
Whats going on here is that the backend returns a list of results and the frontend is just picking the first one in the list.

One option is to always use a hash qualified reference when clicking items, but this would mean we can't have any relative urls. Some more investigation is needed in figuring out the right course of action here.

**Comment by hojberg** [comment]
cc @ChrisPenner @pchiusano

**Comment by ChrisPenner** [comment]
> but this would mean we can't have any relative urls

I'm not understanding where this comes from; can you expand on it?

**Comment by hojberg** [comment]
@ChrisPenner — Maybe I don't understand that option well enough, but its my understanding that we'd have to include a hash in the URL (because we need it for the requests) when clicking on links in the sidebar right?

Alternative option: the namespace path given here is precise, and I think the UI always gives a precise path (if the base Join was clicked, `lib.base.Doc` would be part of the URL). Maybe we can sort the results based on that or provide an option to only give exact results?

**Comment by ChrisPenner** [comment]
Ah, I see. I didn't realize the backend was doing a suffix-based search rather than looking up exactly the name provided at the perspective.

Is it safe in all cases to assume that we want exactly the term at `<perspective> + <name>` ? If so I can probably just tweak the backend to return the exact result at that position rather than search by suffix.

**Comment by aryairani** [comment]
Holding this until the "precise pretty printer" is ready. (Consult with @ChrisPenner)

**Comment by hojberg** [comment]
@aryairani @ChrisPenner any update?

**Comment by ChrisPenner** [comment]
Should be fixed in the latest release via https://github.com/unisonweb/unison/pull/4485
