### ISSUE TITLE
Let TDNR look outside of a recursive definition if types don't match? 

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#372]
```haskell
a == b = case (a,b) of
  ((ta, va), (tb, vb)) -> ta == tb && va == vb
```
![image](https://user-images.githubusercontent.com/538571/54065219-b74e6900-41eb-11e9-97b1-98805f67f861.png)
The error here makes sense (apart from the coloring, which makes no sense); the typechecker assumes the `==` in the body is a recursive call, when it wasn't meant to be (ta and tb are Text, va and vb are Json, and they have their own `==` qualified definitions that can be found with TDNR.  The fix is to qualify the internal calls or rename the or qualify the name of the function being defined.  e.g.
```haskell
a X.== b = case (a,b) of
  ((ta, va), (tb, vb)) -> ta == tb && va == vb
```
But is there a reasonable algorithm to extend the "do what I mean" way that TDNR otherwise lets you work?

**Comment by pchiusano** [comment]
Hmm. My take - if you want to refer to something in an outer scope, don’t shadow it. It’s simple and non magical, and the rules for shadowing and lexical scope aren’t something I want to mess with.

Also think this ‘problem’ goes away when names are qualified, which they will be in practice (don’t forget about the namespace block which makes defining qualified stuff more convenient).

If you wanna fight for this, you can take lead on fleshing out what you’d like in detail, otherwise I’d close this one. 😀

**Comment by pchiusano** [comment]
Btw in this particular case, having universal equality would make things much simpler. The universal equality function would be the main one that everyone would import and then the monomorphic versions would just get used if you were doing something weird.

**Comment by aryairani** [comment]
Probably a better error message would go a long way:

![image](https://user-images.githubusercontent.com/538571/54077041-16aa8880-4281-11e9-9e2d-803fad9c39c6.png)
