### ISSUE TITLE
File system loop detected in codebase.

### ISSUE THREAD

**Issue by philderbeast** [unisonweb/unison#3746]
Do we need these symlinks? They can send a tool that recursively iterates over the tree into an infinite loop, https://github.com/ndmitchell/hlint/issues/1443.

```
$ find -L . -type l
find: File system loop detected;
  ‘./codebase2/codebase-sqlite/unison’ is part of the same file system loop as
  ‘./codebase2/codebase-sqlite’.
find: File system loop detected;
  ‘./unison’ is part of the same file system loop as
  ‘.’.
```

**Comment by ChrisPenner** [comment]
As far as I can recall, the symlinks are there because TH splices (like this one: https://github.com/unisonweb/unison/blob/fa378f7601bc624aa6ec8029bf4cfb6949752f16/codebase2/codebase-sqlite/U/Codebase/Sqlite/Queries.hs#L292) are run with a different working directory at different times; whether this is an issue with stack or cabal or simply our build process I'm not sure.

Presumably there's some way to sort this out 🤔
