### ISSUE TITLE
Typechecker fails to generalize closed inner functions

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3752]
Issue noticed by @SystemFw. Here's an example that doesn't typecheck. We define a polymorphic function, `id`, inside another function. If you annotate `id` it works fine, but 

```
foo = do
  id x = 
    _ = 1
    x
  id ()
  id "hi"
```

This gives a type error:

```
  The 1st argument to `id`
  
            has type:  Text
      but I expected:  Unit
  
      7 |   id "hi"
```

Implying that `id` isn't being generalized.

This example doesn't use TDNR (or I can't see how it does), which I thought could be a confounding factor,  so I'm not sure what's going on. 

The typechecker does have some logic in `synthesizeWanted` to generalize the types of inner definitions if they are closed and have no free variables, but for some reason it isn't being triggered here.

## Clues

Another clue is that if `id` is defined as `id x = x` (so without the extraneous binding `_ = 1`) then it works fine. Weird, right?

Second clue is that this example works, just removing the `do`: 

```
foo =
  id x = 
    _ = 1
    x
  id ()
  id "hi"
```

It's interesting that this second example works, since inferring the body of the `do` should go throught he same inference logic.

Possible idea: I wonder if when you add the `do` it actually ends up *checking* the body of the `do` lambda against some type signature with existentials in it, so it doesn't end up in the synthesize code path that does the generalization.

Not urgent but would be nice to get to the bottom of this.

**Comment by dolio** [comment]
Clue 1 seems to no longer be the case. Even just `id x = x` gets rejected.

**Comment by dolio** [comment]
So, it appears your hypothesis was close. The difference is that in the case that works, we have:

    let rec id x = x

and in the other case we have

    let id x = x

For some reason, the non-recursive let checking does not generalize the binding while the recursive one does. I'm just going to try changing this unless someone can think of a reason for this behavior.

**Comment by dolio** [comment]
Actually, I realized there is a reason. It's a standard problem with polymorphic references. If you do:

    let r = IO.ref '(bug "whatever")

then generalizing it gives `r` the type `forall a. Ref {IO} 'a`. But since it's a `let` it's a particular reference, which means it's now a means of unsafe coercion.

So, the check for whether the binding can be generalized needs to be more strenuous in this scenario. We have a check in a different path that generalizes if the binding is closed, but that's not good enough, because the above is closed (no free vars at least). I think it needs to be more like, 'is pure.'
