### ISSUE TITLE
UnkownDecl error in record type

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#3861]
This code

```
unique type Foo = {
  i : Instant
}
```

Gives this error:

```
  UnknownDecl:
    data type
    reference = Instant
```

This works fine though:

```
unique type Foo = Foo Instant
```

As does this:

```
unique type Foo = {
  i : Text
}
```

**Comment by pchiusano** [comment]
@tstat is this possibly related to pattern coverage checking not loading all the datatypes it needs? I don't totally get why it'd be an issue, since the data decl mentions `Instant` so that dependency should surely be loaded. Is it that you aren't loading transitive dependencies of the data types in the environment, only the transitive dependencies of the terms being typechecked?

**Comment by pchiusano** [comment]
@runarorama also are you using latest trunk? @tstat fixed something related to this somewhat recently.

**Comment by runarorama** [comment]
Yeah this is on trunk as of 12 hours ago.

**Comment by tstat** [comment]
It seems very likely that this is related to the pattern match work. 

I'm not sure what the issue is either, but I will look into it today.

**Comment by aryairani** [comment]
This at least begs for a unit test that would fail here.
