### ISSUE TITLE
`docs 1` on result of `find` doesn't work

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#3939]
Reason is that numbered args includes hashes, and `docs` command isn't expecting a hash-qualified name. Would be an easy fix and nice quality of life improvement:
```
@unison/distributed/remote2> find List.map

  1. up.base.List.map_ : (a ->{g} b) -> [a] ->{g} ()
  

@unison/distributed/remote2> docs 1

  😶
  
  No results. Try using the `link` command to add metadata to a definition.

@unison/distributed/remote2> debug.
debug.clear-cache            debug.dump-namespace-simple  debug.pull-exhaustive
debug.doc-to-markdown        debug.file                   debug.push-exhaustive
debug.doctor                 debug.name-diff              debug.tab-complete
debug.dump-namespace         debug.numberedArgs
@unison/distributed/remote2> debug.numberedArgs

  1. up.base.List.map_#r8ond6vvemip5jlbhplrdbncm8q1hregrpbnsn22u1ngcgpchkn95hu4h815969htedtreg3c9nqfbc6ns46hfbnsmdidpr5ld03flo

@unison/distributed/remote2> 
```

**Comment by pchiusano** [comment]
New user hit this recently, generating confusion.

**Comment by sellout** [comment]
The output I get a year later is a little different:
```
lucky-marmot/main> find List.map

  ☝️
  
  I couldn't find matches in this namespace, searching in 'lib'...

  1.  lib.base.data.List.map : (a ->{𝕖} b) -> [a] ->{𝕖} [b]
  2.  lib.base.data.List.map.doc : Doc
  3.  lib.base.data.List.map.tests.functor : [Result]
  4.  lib.base.data.List.map2 : (a ->{e} b ->{e} c) -> [a] -> [b] ->{e} [c]
  5.  lib.base.data.List.map2.doc : Doc
  6.  lib.base.data.List.mapIndexed : (Nat ->{𝕖} a ->{𝕖} b) -> [a] ->{𝕖} [b]
  7.  lib.base.data.List.mapIndexed.doc : Doc
  8.  lib.base.data.List.mapIndexed.tests.ex1 : [Result]
  9.  lib.base.data.List.mapIndexed.tests.ex2 : [Result]
  10. lib.base.data.List.mapIndexed.tests.mapsAndIndexes : [Result]
  11. lib.base.data.List.mapRight : (a ->{g} b) -> [a] ->{g} [b]
  12. lib.base.data.List.mapRight.doc : Doc
  
lucky-marmot/main> docs 1
lib.base.data.List.map#ko93h54ensirkthhekqb7898lk1j1klhv5mplfpcui1bh03dcrg9i2tp3ibfk3r1qp36uhie79el2fbc15rpm6bkgl7l1tfahst2m6g

  ⚠️
  
  The following names were not found in the codebase. Check your spelling.
    lib.base.data.List.map.doc#ko93h54ensirkthhekqb7898lk1j1klhv5mplfpcui1bh03dcrg9i2tp3ibfk3r1qp36uhie79el2fbc15rpm6bkgl7l1tfahst2m6g
lucky-marmot/main> 
```
But I think the problem is the same.

The issue seems to be that the derived `Functor HashQualified` instance is wrong. You can see from the above (hashes truncated):
```
lib.base.data.List.map#ko93h54ensirkthhekqb
lib.base.data.List.map.doc#ko93h54ensirkthhekqb
```
The hashes are the same, even though they refer to different names. The `Functor` instance should invalidate the hash, converting any `HashQualified` into a `NameOnly`.

Because of this, there also shouldn’t be a `Functor HashQualified` at all (since there’s no way to modify the `Name` of a `HashOnly`), and `Functor HashQualified'` needs to be hand-written.

**Comment by sellout** [comment]
Ok, cool. That fixed it. PR incoming, depending on how much that `Functor HashQualified` instance is used …

**Comment by aryairani** [comment]
@sellout Apart from the `Functor` issue (we can delete it if it's invalid; converting a `HashQualified` into a `NameOnly` would also violate the Functor identity law, wouldn't it?), I think this is a perfect example of when the command should consume less than what may be available. Only the `Name` part of the input is relevant to the `docs` command.

**Comment by sellout** [comment]
> @sellout Apart from the `Functor` issue (we can delete it if it's invalid; converting a `HashQualified` into a `NameOnly` would also violate the Functor identity law, wouldn't it?)

You’re right. There’s no way to preserve identity with that change.

The thing is that the current instances obeys the functor laws, but it’s really easy to accidentally invalidate the expectations we have for the type. However, this one call is the only one in the code base that _actually_ invalidates it. The others are all prefixing, or `unsplit`ing or whatever in a way that doesn’t change the referent.

So, I’m tempted to replace the functors with just a differently-named function, like `invariantMap` or something, so that callers have to think about it and why it’s not just `fmap`, but 🤷🏼 And that’s not required to fix this issue.

> I think this is a perfect example of when the command should consume less than what may be available. Only the `Name` part of the input is relevant to the `docs` command.

Yeah, that makes sense – that’s what I was effectively doing anyway. Changing `DocsI` to expect `Name` instead of `HQSplit'` means this should be based on #4962 (which is what I figured before I noticed the Functor issue).
