### ISSUE TITLE
Pulling to a relative path now gives a confusing error message

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#3953]
```
.tmp> pull unison.public.base.latest base
 
  base/main does not exist.
```

It works fine if I change it to `.tmp> pull unison.public.base.latest .tmp.base`

**Comment by mitchellwrosen** [comment]
Indeed - there's a syntactic ambiguity between project branches and single-segment paths, so the current implementation of `pull` treats such things as project branches.

There's one thing that's easy to resolve and already on the todo list: similar to https://github.com/unisonweb/unison/pull/3952, instead of parsing the second argument to a two-argument pull as a [project or branch or project-plus-branch], treat it as a [branch or project-plus-branch].

That, combined with a more context-aware handler, would make the above example unambiguous, as `base` cannot refer to a project branch named `base`, since you're not on a branch, you're in loose code `.tmp`.

But we would still have the exact same issue if you were instead on some project branch, trying to pull into a relative single-segment path. We could do a couple different things here:

1. Don't ever parse the second argument of a two-argument `pull` as a project branch at all. If you want to pull into a branch that's _not_ the current branch, just switch to it first and perform a one-argument `pull`.
2. When ambiguous, do nothing, but present a list of unambiguous alternatives. For example,

    ```
    What's that mean? Try one of these instead:
  
    1. pull unison.public.base.latest :here.base
    2. pull unison.public.base.latest /base
    ```
    
    (Note: we don't have the `:here` syntax yet)
