### ISSUE TITLE
improve error message for incorrect infix operator use

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#396]
Given:
```
Test.busy n = if n Nat.equal 0 then 0 else Test.busy (n `Nat.drop` 1)
```

Currently:

![image](https://user-images.githubusercontent.com/538571/54568052-4574dd00-49ac-11e9-944a-1065e82f80cb.png)

Probably if the annotation for `(Nat -> Nat ->{𝛆} Boolean) -> Nat -> Boolean` was restricted to just the `n Nat.equal 0` region, it would help.  Beyond that, it should be possible to notice that the type `(a -> b -> c) -> b -> c` mismatched against type `a` is probably exactly this situation.

**Comment by pchiusano** [comment]
Sounds plausible... is the proposed algorithm:

- If it's a type mismatch
- In a function call `f x y`
- Where `f : a` and `x : a -> b -> c` for any `b` and `c` types
- Then give a hint that maybe you meant `f \`x` y`

Aside: a type annotation on `Test.busy` would have given a better message here since that would have pinned down the type of `n`. As its written, it just merrily assumes `n` is a function and only much later detects an inconsistency.

**Comment by aryairani** [comment]
Infix wordy operator syntax was removed altogether.
