### ISSUE TITLE
Command to edit entire namespace

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4004]
Currently a common way to work on a project is to edit an entire namespace in a scratch file. There may be less need for this in the future as the update process improves, but for now it's all but necessary.

The simple albeit somewhat clunky way to do this is:

- `cd mynamespace`
- `find`
- `edit 1-249`

However, there are some downsides to this approach:

- It's 3 commands and the `find` can be slow.
- It puts all `unique` types in the scratch file, so unless you comment them out you'll run into #2196.
- It puts generated record fields (accessor, `set`, `modify`) in the scratch file, so if you change the record type you'll have to change all of these too (or comment them out). Also you can run into #3733.

I think that a piece of low-hanging fruit that would help a lot would be a new command that does the following:

- Print all* terms/types in the namespace (recursive) in a scratch file
  - Don't descend into `lib` namespaces
- Comment out unique types to avoid #2196. Also putting these at the top of the file can be helpful since when you edit them you often want to put everything else "below the fold".
- Comment out or omit record accessor/`set`/`modify` fields since the user will just modify the record type (and to avoid #3733).

You could maybe call this command `edit.namespace`. I don't think that it's very helpful to have it accept a namespace argument, because you'd only want to do this on your current namespace. What I'd be more likely to want to provide is the name of a scratch file to print it to, but I don't think that there's a precedent for that, so for now we could just use the scratch file convention of last-saved or `scratch.u`.

**Comment by aryairani** [comment]
I also want this command, as a sanity check. Like it could even be `debug.edit.namespace`. I just want to verify that none of my definitions are messed up or showing hashes even though `todo` and `namespace.dependencies` are empty.

Ultimately when we start feeling more confidence in the normal commands, that they "do the right thing", I guess this would no longer be necessary; wdyt @ceedubs? 

But I'm not keen to have it do much post-processing:
* "Yes" to leaving out `lib`, definitely
* Unique types: It would be easy enough to comment out unique types, but let's just fix the churn issue instead
* record functions: unfortunately we may have trouble recognizing record types due to possibly the same bugs; so we should just try to fix those. Otherwise we'd be like commenting out things that are _called_ `get`/`set`/`modify`

**Comment by ceedubs** [comment]
I'm all for fixing unique type churn and record functions instead of hacking around them with this command. But those issues have been around for years; I wanted something that could save me time while working on Unison code _now_.

**Comment by ceedubs** [comment]
Also regarding having more confidence in the normal commands:

Even if `todo` and `namespace.dependencies` are improved, I'll continue to use this development flow until the update/patch process is improved, and I think that's a longer term issue.

**Comment by aryairani** [comment]
- #4535
