### ISSUE TITLE
bad error message if a block ends in a variable declaration

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#4077]
In the following code, the `foo` function ends with a declaration of the variable `x` (`x = 3`), but we don't actually use or return `x`. The compiler catches this as an error (which is good), but it gives a bad error message:

```
foo =
  x = 3
```

```
  I couldn't find any definitions matching the name _100003 inside the namespace .__projects._90b3d793_b355_4859_b6e2_6ba8b33c55a5.branches._e56b737a_033a_4866_9883_6691ba53715b
  
      2 |   x = 3
  
  Some common causes of this error include:
    * Your current namespace is too deep to contain the definition in its subtree
    * The definition is part of a library which hasn't been added to this project
  
  To add a library to this project use the command: `fork <.path.to.lib> .__projects._90b3d793_b355_4859_b6e2_6ba8b33c55a5.branches._e56b737a_033a_4866_9883_6691ba53715b.lib.<libname>`
  
  There are no constraints on its type.
```

## Notes

- This output also includes an issue with pretty-printing of a project namespace, but that's a separate issue.
- This has happened for a long time so I figured there would be an issue for it, but I couldn't find one.

**Comment by aryairani** [comment]
A better message would be:
```
I was expecting this block to end with a result expression that conforms to this type: <blah>
```
or if there are no constraints on the type:
```
I was expecting this block to end with a result expression.

Check out https://www.unison-lang.org/learn/language-reference/blocks-and-statements/ for an overview of blocks.
```

**Comment by runarorama** [comment]
A little writeup on why this happens:

1. The parser encounters the missing result and inserts a fresh `MissingResult` variable named `_100003` as a placeholder for the result expression. The idea is that we'll infer the type of this variable and use that in the error report.
2. The typer, before entering TDNR, replaces all placeholders with fresh `Blank` variables, including this one. This forgets that the variable is a `MissingResult` variable.
3. TDNR fails to resolve the blank since `_100003` is not a name it knows about. Produces an `UnknownTerm` error with a `User` variable generated from the missing name.
4. The error reporter reports it as a `User` variable, so as if the user had put a variable reference to `_100003` at the end of the block.

**Comment by runarorama** [comment]
I tried skipping the substitution of `Blank` for `MissingResult` variables. This skips TDNR for these variables. However, this ends up synthesizing a `MissingResult` type variable named `_100003`. The typer fails with `UnknownType`.
