### ISSUE TITLE
Rendering an infix function created using `cases` produces invalid code

### ISSUE THREAD

**Issue by alvaroc1** [unisonweb/unison#4239]
Version: release/M5b

A somewhat weirdly defined (but presumably valid) infix function:
```
(>>>>) : Nat -> Nat -> ()
(>>>>) n = cases
  _ -> bug ""
 ```
 
 After adding it and viewing it:
 ```
 @unison/httpserver/main> view >>>>

  (>>>>) : Nat -> Nat -> ()
  error = cases _ -> bug ""
 ```
 
 (Note the `error` name after the type)
 
 Example on share:
 https://share.unison-lang.org/@unison/httpserver/code/releases/0.3.0/latest/terms/Routes/%3E%3E%3E

**Comment by aryairani** [comment]
@ChrisPenner Hoping this is something obvious in the declaration printer?

**Comment by kylegoetz** [comment]
Of note:

```
useful-walrus/main> display

  '(cases _ -> bug "")

useful-walrus/main> view

  (>>>>) : Nat -> Nat -> ()
  error = cases _ -> bug ""
```

**Comment by kylegoetz** [comment]
Assuming that is valid code, then it's a bug in `TermPrinter.hs`:

```haskell
defnLhs v vs
          | infix' = case vs of
              x : y : _ ->
                PP.sep
                  " "
                  [ fmt S.Var $ PP.text (Var.name x),
                    styleHashQualified'' (fmt $ S.HashQualifier v) $ elideFQN im v,
                    fmt S.Var $ PP.text (Var.name y)
                  ]
              _ -> l "error"
          | null vs = renderName v
          | otherwise = renderName v `PP.hang` args vs
```

If it's an infix op, then the printer guards for infix, and if so, it handles two outcomes:

1. at least two arguments for the operator
2. otherwise print "error"

If it finds only one (as in this case), it prints "error" for the LHS.

I thought this might be fun to work on, so I added a pattern for just one argument:

```haskell
x : _ ->
                PP.sep
                  " "
                  [
                    styleHashQualified'' (fmt $ S.HashQualifier v) $ elideFQN im v,
                    fmt S.Var $ PP.text (Var.name x)
                  ]
```

AFter building, this parses without "error" but it's not parenthesizing the infix op:

```
insightful-polecat/main> view >>>>

  (>>>>) : Nat -> Nat -> ()
  >>>> n = cases _ -> bug ""
```

I also created a regression test but it keeps failing saying it found an unexpected virtual semicolon:

```
termprinter.(>>>>) : Nat -> Nat -> ()
(>>>>) n = cases 
  _ -> bug "" EXCEPTION!!!: offset=11:
unexpected <virtual semicolon>
expecting ->
    2 | (>>>>) n = cases 

CallStack (from HasCallStack):
  error, called at tests/Unison/Test/Common.hs:52:11 in main:Unison.Test.Common
💥  termprinter.(>>>>) : Nat -> Nat -> ()
(>>>>) n = cases 
  _ -> bug ""
termprinter.(>>>>) : Nat -> Nat -> ()
(>>>>) n = cases 
  _ -> bug "" EXCEPTION!!!: offset=11:
unexpected <virtual semicolon>
expecting ->
    2 | (>>>>) n = cases 

CallStack (from HasCallStack):
  error, called at tests/Unison/Test/Common.hs:52:11 in main:Unison.Test.Common
💥  termprinter.(>>>>) : Nat -> Nat -> ()
(>>>>) n = cases 
  _ -> bug ""
```

In the test I am invoking TermPrinter's `pretty`. Looks like maybe I should be testing DeclPrinter instead and using `prettyDecl` in the test but I'm not sure.

Some scratchwork I did https://github.com/kylegoetz/unison/tree/4239/cases-infix
