### ISSUE TITLE
Don't use ! syntax in pretty-printer if there's more args after

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#4258]
<img width="541" alt="image" src="https://github.com/unisonweb/unison/assets/11074/ee45cc40-1ecd-490f-b10a-8f5f17e6ee99">

**Comment by kylegoetz** [comment]
I'm assuming here that

```
Transaction.write : 'SomeTableHandle -> LinkedMap -> Something
```

So is the idea then that it's preferable instead to parenthesize the thunk and then apply it with `()`, and after that you provide the next arg(s) as usual?

```
Some linkedMap -> linkedMap
None ->
  (Transaction.write table)() newLinkedMapIfNeeded
  newLinkedMapIfNeeded
```

**Comment by kylegoetz** [comment]
@pchiusano I'm looking at this one, but can you let me know what the type sig is for Transaction.write?

I'm unclear if the issue is just an aesthetic one (should be `(Transaction.write table)() newLInkedMapIfNeeded` or if it is actually erroneous (should be `(Transaction.write table newLinkedMapIfNeeded)()`. I.e., I'm not sure which part of `Transaction.write` is delayed: `'(a -> b -> c)` vs `'a -> b -> c` vs something else.

**Comment by SystemFw** [comment]
No part of `Transaction.write` is delayed. The signature is:
 ```haskell
 Transaction.write : Table k v -> k -> v ->{lib.cloud.State.Transaction} ()
 ```
 
 but it's being called on `Table () Something`
