### ISSUE TITLE
Needs design: exactly how does a Unison programmer create, publish, maintain, and use libraries?

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#440]
Replace this description with a write-up of the above.

**Comment by ChrisPenner** [comment]
Does Unison have an RFC process currently?

**Comment by ChrisPenner** [comment]
Question; do namespaces affect hashes? I assume not.

Since Unison has perfect tree-shaking AND code identification, is there a reason to have `packages` or `libraries` at all? I think probably not for CODE reasons, but obviously for HUMAN readability and maintenance there is. Maybe we use namespaces for the human things and just have unison code depend on a bunch of hashes rather than any sort of library?

This adds the question of what a 'library upgrade' means I suppose, and how we avoid dependency hell when libs share types which application code is passing between each other. Sounds like a tricky problem that most package managers won't have needed to address at this level of granularity.

**Comment by aryairani** [comment]
@ChrisPenner We don't have a formal RFC process yet.  Mostly we've whipped up some write-ups and sometimes have the presence of mind to share them with the community for feedback :)

@francisdb "Unison programmer" — a person trying to write code using the Unison language and tools.

@ChrisPenner Yes exactly, here "package" or "library" is used loosely to mean "code that someone else has written" or "code that I'm not really editing" or "code that I want to publish in a useful form".  I haven't come up with any definition that doesn't break down almost immediately.  Where does my application end and your library start?  What if it's my "library"? What if I need to change your library?

There won't be any package managers per se, but there will need to be some organizational facilities to support human sanity, as you've said.

**Comment by aryairani** [comment]
> Question; do namespaces affect hashes? I assume not.
@ChrisPenner I think the answer is no, but not sure I understood the question.  The hash for a type or term definition doesn't depend on any of the names in it, nor on how it might be bundled with other definitions.

**Comment by mbernat** [comment]
Since Unison is already using a git-like versioning and editor, why not "just" go all in and add remote repos? This bypasses the need for libraries entirely, you "just" need a way to host and discover code (for starters a centralized repo index, a la github).

Libraries might emerge on top of this infrastructure (e.g. some repos treated as libraries and versioning handled by branches), or they might not. It's certainly conceivable that people would learn to use fine-grained dependences in most cases, pulling single functions from many repos as they see fit, as opposed to building behemoth libraries like normal languages tend to do.

I'm also wondering how the Unison cryptographic deps relate to stuff like Nix. There are likely many things one could learn from non-standard package managers.

I'm sure all of this and more have occurred to you guys already. Just couldn't help sharing my 2c, since I had been thinking about exactly this kind of granular code reuse recently :)

**Comment by aryairani** [comment]
Hey @mbernat! We’re definitely considering being able to `import` definitions directly from a remote github repo, from your editor.

Definitely appreciate your 2¢; plus if it’s about something we’re already considering then that motivates us and helps us know we’re on the right track.

**Comment by pchiusano** [comment]
Just doing some cleanup. I'm going to close this issue as we do have a design for this, and it's being implemented as part of #470. That said, feel free to continue any discussion on this thread if you have ideas.
