### ISSUE TITLE
RFC: testing in Unison

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#444]
See writeup [here](https://github.com/unisonweb/unison/blob/master/docs/testing.markdown)

Subsumes #356

**Comment by ChrisPenner** [comment]
This all sounds very nice in theory; but there's not much mention of tests which use IO; which of course people might WANT to re-run very often. E.g. maybe the tests actually test the behaviour of some external system rather than the unison code themselves. For these sorts of things it would be helpful to have some way of grouping these tests or searching through them. E.g. run the tests that validate our database schema is correct; I suspect at some point in the future it will be nice to have metadata 'tags' on definitions so this grouping could be implemented in terms of that somehow.

In addition; it's sometimes harmful to run definitions which use IO arbitrarily. They may make side-effecting HTTP calls; write to file-system, etc.

**Comment by pchiusano** [comment]
@ChrisPenner certainly, tests that do `IO` are important too. :) That's covered as the first thing in the document... not much is said about it because right now there's nothing special planned in the core tool editing tool to support it. I think your point about using metadata to discover and run `IO`-based tests in bulk is good. 

We haven't really fleshed out the design for metadata but when we do this is a good use case to keep in mind so thanks for flagging.

**Comment by aryairani** [comment]
@runarorama and @aryairani to give feedback on the design doc :+1:

**Comment by pchiusano** [comment]
See #495 and #477
