### ISSUE TITLE
Baffling error messages when using / instead of Float./ 

### ISSUE THREAD

**Issue by stefanholzmueller** [unisonweb/unison#4543]
To reproduce with UCM 0.5.12, I have to be inside a project that clones `yap`:
```
clone @dfreeman/yap bug4543/
```
Then I put the following in my scratch file:
```
test : Float -> Float
test x = x * (1.0 / x)

> test 1.0
```
which provokes this error:
```
dumpDataNoTag: bad closure: PAp (CIx (ReferenceDerived (Id "01j2nvlku4s0sgpbhstjegb1t5t9d8m8l1nfph194h019i252i70o" 0)) 609 0) [] (fromListN 0 [])
  expected type: ReferenceDerived (Id "nk9jfsoidsc5h3nhcf1p6528t6c5hqui3hridbvaqnruel4jns3qo6plgups2sgi82c9jgt9ba1qlkum1bdjdgp75h7si2thbo7tcfg" 0)
```

If I remove the explicit signature, it does not type-check at all:
```
The 2nd argument to `(Float./)`
  
            has type:  Bag a
      but I expected:  Float
  
     45 |   x * (1.0 / x)
```
(no idea where `Bag` comes from!)

Everything works if I change the `/` operator to `Float./`, or add a `use Float /` line, but without the qualified name, the error messages are just very surprising to me.

**Comment by aryairani** [comment]
Thanks for reporting this very weirdness @stefanholzmueller

**Comment by dolio** [comment]
Here's some information about what's going on.

First, this won't happen all the time. It's somehow specific to the project/namespace you're currently in, and how it affects name resolution. An example of an affected project is:

    @dfreeman/yap

on share. The bug will occur at the top level of that project, or within the `lib` namespace, but not if you are in either of the two libraries therein. A possible relevant factor is that the two libraries are a version of `base` and a version of `exists` which contains a version of `base` nested under it. The fact that there are two copies of `base` (and the problem involves definitions from `base`) seems like it's probably relevant.

Some debugging shows that the runtime is getting fed the code:

```
let
  use Float /
  use base_2_9_1.data.Bag *
  test : Float -> Float
  test x = x * (1.0 / x)
  ()
```

This is the code that generates the type error in the un-annotated case, but somehow with the `Float -> Float` annotation, execution makes it all the way to the runtime, which is then running type incorrect code.

I've looked at debug tracing for the type checking process, and it _seems_ to go through the process of TDNR, and do a final check with both `Float./` and `Float.*`. So, it seems like it figures out it should be using `Float` operations, does a final check with them, but then sends some other code to the runtime instead. Maybe things are getting paired up incorrectly somewhere, such that the `(Float, Float)` case is paired with `(Bag, Float)` erroneously. And if the two copies of base are relevant, maybe it has to do with removing duplicates somehow.

Manually specifying `Float./` causes the runtime to be provided with the code that also uses `Float.*`. I haven't investigated exactly why, but a guess would be that when you do that, only `*` has to be resolved by TDNR, and the candidates are restricted, because TDNR will know it has to have type `a -> Float -> b`. So `Bag.*` won't even be a candidate. From what I could tell, the types used in TDNR for the problem example were very general, like `a -> b -> c` for `*` and `Float -> b -> c` for `/`. So a lot more combinations get tried.

**Comment by dolio** [comment]
Here's some additional information based on type checking tracing.

I'm finding it difficult to understand why the TDNR queries (assuming I'm looking at them correctly) are what they are. First, consider the ones that I do understand. That is the un-annotated case:

```
test x = x * (1.0 / x)
```

The way this works, I believe, is that the definition is checked with 'blanks' for `*` and `/`. We infer the type of the expression, which causes some refinement of what their types must be. Then we try to match those against types of things in the codebase with the right name. Here are the types in the un-annotated case:

```
* : a -> b -> c
/ : Float -> a -> b
```

I think these come out quantified in the variables, but I took care to make the variables cohere with how they must actually match up in the expression. According to my mental inference, this is as good as we can expect. We don't know the type of `x`, nor an expected result type, so all we know is that the first argument to `/` must be matchable with `Float`. With this information, the TDNR seems to pick `Bag.*` and `Float./`, then bombs checking the expression yielded by those choices. It doesn't seem to check any other expressions, so it _seems_ like it's just going with its first choices of each _independently_, not considering how they have to cohere.

Now, consider:

```
test : Float -> Float
test x = x * (1.0 / x)
```

This follows some different type checking paths. Like, we should check `x * (1.0 / x)` against type `Float` under the hypothesis that `x : Float`. This _should_ yield the conclusions:

```
* : Float -> b -> Float
/ : Float -> Float -> b
```

_However_, in addition to that, it looks as if it is _also_ doing the same TDNR queries as in the un-annotated case. Somehow it decides to check the resolved term with both `Float` operations, but then maybe the 'naive' resolution above is what actually gets reported as the result? And nothing afterwards checks that the naive resolution makes sense, or notices that it wasn't the resolved term whose type was verified. I'm still not sure how the bad term gets selected for evaluation.

Again, it only looks like it checks one resolution. So it seems like it's not selecting based on the choices cohereing in any way. It just happens that the more refined types get a coherent answer in this case, but then the less refined information is used for whatever it finally returns.

**Comment by dolio** [comment]
So, here's something else weird.

If I write this:

```
test x y = x * y
```

Then in e.g. `@dolio/internal` I get a complaint that `*` is ambiguous. Could be Bag, Int, Nat, Float etc.

In `@dfreeman/yap` it gets resolved to `base_2_9_1.Bag.*`, even though all those other options also exist.

However:

    test x y = x / y

is still ambiguous in the problem project.

Perhaps commit #4502 is related?
