### ISSUE TITLE
Confusing TDNR related error message

### ISSUE THREAD

**Issue by hojberg** [unisonweb/unison#4632]
I was working on the Share SDK library and some JSON Decoders and ran into this error message:

https://github.com/unisonweb/unison/assets/2371/f9dba78b-99bb-48a1-a5c2-d0e9f7d94eb0

Its confusing on a series of fronts:

1. `text` worked before, and now doesn't. The real issue is that `or` isn't qualified, but this is reported via `text`
2. There's so much output on the screen that my eyes just glaze over. The message is about as effective as a message that just said "error" (meaning not effective).
3. The project guts are showing. We have a few cases where this is still the case and I think a filter on output messages could help a lot on this area. I know we plan to a different storage mechanism for projects, but in the meantime its really hurting the usability of these error messages

**Comment by aryairani** [comment]
Thanks for reporting this weird message. What is `or`? Shouldn't it come first?
```
or (object.at! "annotation (object.at "tag" text)) "blank"
```

**Comment by hojberg** [comment]
@aryairani yeah the bug in my code was with how I was using `or`.

**Comment by runarorama** [comment]
Issues with this error message:

1. "Inside the namespace..." shows the internal name of the project namespace. We should eradicate all places where we're showing such namespaces to the user.
2. The "common causes" section doesn't list the true cause which is that there is a different type error somewhere in the code and the resolution of this ambiguous name is masking that error. Suggest e.g. "I'm stuck on looking up `text` by its type because of a type error somewhere else in your code. Using the full name of `text` would help me out."
3. The instructions for adding a library are wrong, and also irrelevant in this case.
4. The library adding instructions also show the internal name of the project namespace.
5. The list of matching names shows the full namespace path (relative to the project root) of every term. It could instead show the shortest unique suffix.
6. The list of matches is in no particular order. Perhaps sort by the length of the namespace path to the term, shortest first
