### ISSUE TITLE
Version: getTag succeeds for release tarball in non-unison git repo

### ISSUE THREAD

**Issue by juhp** [unisonweb/unison#4692]
I think this is a corner case, but I build Unison for Fedora in a [package git repo](https://github.com/fedora-haskell/unison).

[This](https://github.com/unisonweb/unison/blob/trunk/unison-cli/unison/Version.hs#L40) causes the git hash of HEAD of my package git repo to appear in the startup message:

```
You are running version: eee72b4'
```

when I build the package locally.

I am tweaking my version [patch](https://github.com/fedora-haskell/unison/blob/main/unison-version.patch) to workaround it.

**Comment by juhp** [comment]
Given that it defaults to "unknown": I guess this is probably notabug/wontfix anyway...

**Comment by aryairani** [comment]
Thanks for reporting. I do think this could be improved, but I'm not exactly sure how.

It would be nice if "version" was correct even when you download a release tarball; but it's also nice if that can be derived automatically instead of something that has to be manually updated.

Maybe the `release.yaml` CI action could do something? Open to suggestions.

**Comment by aryairani** [comment]
We'll continue this in #4667
