### ISSUE TITLE
reduce lag for `run` command?

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4735]
can we do something to precompute intermediate code for runnable terms?

**Comment by ceedubs** [comment]
Do you have metrics on the lag that you wish to overcome? My anceotal experience is that it has seemed pretty snappy for main terms that return Unit but can be quite slow to pretty print complex results even when the run was otherwise fast. Though this got much better with the recent change to avoid a global PPE.

**Comment by aryairani** [comment]
Closing this until I have more specifics
