### ISSUE TITLE
In UCM find with ? wildcard doesn't work as per documentation

### ISSUE THREAD

**Issue by piotrga** [unisonweb/unison#4763]
`wordle/main> find .builtin.List.?

  ☝️

  I couldn't find matches in this namespace, searching in 'lib'...

  😶

  No results. Check your spelling, or try using tab completion to supply
  command arguments.

  `find.global` can be used to search outside the current namespace.

wordle/main> find lib.base.builtin.List.?

  ☝️

  I couldn't find matches in this namespace, searching in 'lib'...

  😶

  No results. Check your spelling, or try using tab completion to supply
  command arguments.

  `find.global` can be used to search outside the current namespace.

wordle/main> find lib.base.builtin.List

  ☝️

  I couldn't find matches in this namespace, searching in 'lib'...

  1. builtin type lib.base.builtin.List
  2. lib.base.builtin.List.++ : [a] -> [a] -> [a]
  3. lib.base.builtin.List.+: : a -> [a] -> [a]
  4. lib.base.builtin.List.:+ : [a] -> a -> [a]
  5. lib.base.builtin.List.at : Nat -> [a] -> Optional a
  6. lib.base.builtin.List.drop : Nat -> [a] -> [a]
  7. lib.base.builtin.List.empty : [a]
  8. lib.base.builtin.List.size : [a] -> Nat
  9. lib.base.builtin.List.take : Nat -> [a] -> [a]

wordle/main>`
<img width="1264" alt="image" src="https://github.com/unisonweb/unison/assets/129663/a913a6d0-d030-42b4-bc6f-6704aef16833">

**Comment by piotrga** [comment]
And the docs url: https://www.unison-lang.org/docs/labs/wordle/docs/core-logic/

**Comment by rlmark** [comment]
Thank you for mentioning this @piotrga! This is a documentation issue that I'll fix. The `?` operator was removed with this ticket:https://github.com/unisonweb/unison/pull/4595. I've copied your ticket over to the website repo on Unison Share (it's where the docs content is warehoused) so I can add it to the website update queue. 

For tracking, that ticket is here: https://share.unison-lang.org/@unison/website/tickets/1

I'll close this ticket since it'll get a fix in the Unison Share repo.
