### ISSUE TITLE
'test' omits to run one of my tests

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#488]
I typechecked a file in which a pre-existing test was broken, did `update`, and then `test` missed out that test.  Wrongly?

- I added two tests A and B, both using definition `fac`
- I typechecked a file containing a broken version of `fac` and B
- I did `update` then `test`
- I found it didn't run B.  I think it should have done.  
It still knew about B when I tried `view` and `ls`.

See https://gist.github.com/atacratic/60c0ec8f50f1e78abec240734d673379 for a session transcript.

**Comment by pchiusano** [comment]
Yeah, test propagation not implemented yet, that was mentioned in the PR though maybe wasn’t clear from my writeup. It will need to be redone after the branchless refactoring which is why I didn’t bother yet.

**Comment by atacratic** [comment]
But the test command should run all the tests right?  Regardless of what's recently been changed.  It only ran one of the two in the codebase.  I may have misunderstood.

**Comment by pchiusano** [comment]
It should, yes, or else update should do it when propagating the update. This is what I was calling test propagation above.

Right now the test command is really just showing you a report of all previously cached tests. Note that in order to add a test to the codebase, it will be cached. But tests that are updated indirectly during a propagate aren’t rerun.

**Comment by atacratic** [comment]
OK, feel free to close this issue if that's more helpful.

**Comment by pchiusano** [comment]
Well I want it tracked somewhere, maybe somewhere more consolidated with other todos on the refactoring but will leave it here for now 😀

**Comment by pchiusano** [comment]
This is fixed in `wip/branchless`, so it actually looks through all the definitions in the branch, figures out which ones are tests, looks them up in the cache, and then only runs the ones not found in the cache:

<img width="1087" alt="Screen Shot 2019-06-25 at 4 53 19 PM" src="https://user-images.githubusercontent.com/11074/60132585-c987ef00-9769-11e9-8940-4992b3c0af28.png">
