### ISSUE TITLE
Add command for listing only functions defined by user (not library functions) [Feature request]

### ISSUE THREAD

**Issue by sullyj3** [unisonweb/unison#496]
Currently, the `find` command lists all available names, including library functions and types, which is very noisy. Most of the time, I just want to see functions I've defined in the current branch.

My preference would be for `find` to list only functions defined by me, with a switch (for example `-a` by analogy with `ls -a`) available to list library names as well. However this could also be achieved by keeping the current default and adding a switch to list only my functions.

**Comment by pchiusano** [comment]
@sullyj3 thanks for the report. We're in the middle of a refactoring that makes the branch structure a tree rather than a flat 2-level thing, I think it will address this concern nicely. You'll be able to work at any arbitrary path in the tree, and `find` can recursively look under your current path.

So for example, the builtins will be in `/unison/builtins` or some such, and you'll be working in `/sullyj3`. You'll `cd /sullyj3`, write your code, and `find` will only show the code you've written under that `/sullyj3` path (or maybe like `find / foo.bar` searches for `foo.bar` from the root namespace).

**Comment by pchiusano** [comment]
Hi @sullyj3 I think this is well-addressed by the new wip/branchless stuff, which is still WIP, but after that gets merged, please try it out and reopen or create a new ticket if you feel like it still isn't there. But the general idea is you can just keep "your code" and "external" code at different paths, and `find` will only show results under your current path.

**Comment by pchiusano** [comment]
We also added a metadata system that will let you link author or whatever other metadata to individual definitions, so when we have some metadata search, that might be another way to handle this: "find me everything that I wrote in this path"
