### ISSUE TITLE
Confusing error message about reserved keyword

### ISSUE THREAD

**Issue by ceedubs** [unisonweb/unison#5060]
This error message is really confusing.

```
     The identifier used here isn't allowed to be a reserved keyword: 
      
          1 | this.is.a.long.namespace.path.foo = "foo1"
```

What it's _trying_ to say is that I can't use `namespace` as a namespace segment. But it doesn't tell me which word it's unhappy about, and it's telling me that it isn't allowed to be a keyword as opposed to telling me that I can't use it because it _is_ a reserved keyword.

**Comment by aryairani** [comment]
That is confusing, thanks for the report.

Also confusing: You can try putting namespace in backticks and see if that works 🤫

**Comment by sellout** [comment]
I took a look at this, and I agree that the message is inverted, and that it could use a helpful suggestion, like the backticks.

However, in the output
```
     The identifier used here isn't allowed to be a reserved keyword: 
      
          1 | this.is.a.long.namespace.path.foo = "foo1"
```
“namespace” is colored red in terminals that support it (and since we just use standard terminal colors, we shouldn’t have to worry about color blindness, I think). So I don’t think it’s quite true that “it doesn't tell me which word it's unhappy about”.

The question is – @ceedubs is apparently seeing this output in a context where the color isn’t apparent. What context is that? One is certainly like this ticket – copy/pasted text. Are there other contexts where ANSI color fails? Say, a terminal that doesn’t support it (should we be checking for ANSI support and falling back to other options when color isn’t available). And even when it works, is that enough information? Should we instead rephrase the message to something like “The identifier ‘namespace’ used here …”? that reiterates the identifier in question?

**Comment by ceedubs** [comment]
@sellout oh good catch you are right that `namespace` is in red if I put this code in a scratch file.

I was running into this in a transcript, and compile error output in a transcript doesn't seem to do any highlighting.

**Comment by sellout** [comment]
It seems like a good short-term solution for error messages is to not have non-textual content (like highlighting) be the sole source of any information (in this case, which identifier is a problem). There may be a different way to handle it, but cases like copy/pasting into an issue make it seem like there’s no way to avoid losing that information.
