### ISSUE TITLE
Cannot add two functions with the same source but different types to the codebase

### ISSUE THREAD

**Issue by TomasMikula** [unisonweb/unison#514]
The source

```
idNat: Nat -> Nat
idNat i = i

idInt: Int -> Int
idInt i = i
```

correctly successfully typechecks:

```
 ┌
  │  ✅
  │  
  │  I found and typechecked these definitions in /Users/thomas/projects/unison/source.u:
  │  
  │    idInt : Int -> Int
  │    idNat : Nat -> Nat
  │  
  │  Now evaluating any watch expressions (lines starting with `>`)...
  └
```

but only one of the functions can be added to the codebase, supposedly because they have the same hash:

```
master> add

  ┌
  │  ✅
  │  
  │  I added these definitions:
  │  
  │    idNat : Nat -> Nat
  └
```

**Comment by pchiusano** [comment]
Fixed in wip/branchless, thanks for the report!

<img width="547" alt="Screen Shot 2019-07-02 at 11 00 42 PM" src="https://user-images.githubusercontent.com/11074/60560348-5c51fc00-9d1d-11e9-99a5-f7b5dd9e9fab.png">

Issue was the `isRedundant` function in the typechecker, which checks if a function's signature is redundant, was incorrect, causing the signature to get thrown out for purposes of computing the hash.
