### ISSUE TITLE
Prettyprinter should do something to avoid conflicts between local names and names chosen for any refs

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#525]
Paul will do a longer writeup of this issue.

**Comment by aryairani** [comment]
example: 
```
cat = 3
bar = 
  foo = 6
  cat + foo
> bar -- 9
```
If we `add` these definitions, rename `cat` to `foo`, and `edit bar`, we get:
```
bar =
  foo = 6
  foo + foo
> bar -- 12
```

Alpha-renaming would give something like:
```
bar =
  foo1 = 6
  foo + foo1
> bar -- 9
```
Hash-qualifying would give something like:
```
bar = 
  foo = 6
  foo#abc + foo
> bar -- 9
```

**Comment by atacratic** [comment]
Is it a choice between alpha renaming and hash qualifying? The latter looks less arbitrary to me. The former, with the appended 1 or however it's done, feels like the code being bent out of shape, whereas the latter feels like it's just having a clarification added.

**Comment by aryairani** [comment]
Yeah, it’s a choice between those two (or some other option!), the requirement is that the edited code still compile with the existing meaning, and that it be as pleasant as possible.

**Comment by pchiusano** [comment]
Some implementation notes:

Alpha-renaming is going to be simple, as the ABT machinery is well set up to do that sort of thing. First you call `Term.dependencies`. You get the names for each dependency. Then call an ABT-generic function to freshen any `Abs` node whose variable clashes with the name of a dependency. A nice thing about this way of doing it is done once, up front, and then the prettyprinting code is unaffected.

To do it the other way, you'd probably have to annotate each node with its set of bound variables. When printing out a ref, you check to see if the name the PPE has for that ref is the same as any of your bound variables. If yes, you hash qualify the name of that ref. Also might be like 3 lines of code, or it might be a more complicated refactoring, due to having to change the annotation type on the tree.

I think I prefer the alpha renaming. It's nice to reserve hash qualifying for referring to conflicted or old definitions. Seeing the `#` is then more of a clue.

**Comment by pchiusano** [comment]
This could be considered the same issue as https://github.com/unisonweb/unison/issues/2699
