### ISSUE TITLE
Unison crashes when adding definitions that use functions defined in the same file and are also in the codebase.

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#538]
1. Add `Base.u` to the codebase.
2. Add the following definitions to `Base.u`

```
List.diagonal : [[a]] -> [a]
List.diagonal =
  let 
    stripe aas = case aas of
      [] -> []
      [] +: xxs -> stripe xxs
      (x +: xs) +: xxs -> cons [x] (zipCons xs (stripe xxs))
    zipCons xs ys = case (xs, ys) of
      ([], ys) -> ys
      (xs, []) -> map (x -> [x]) xs
      (x +: xs, y +: ys) -> cons (cons x y) (zipCons xs ys)
    List.join . stripe
```

Crashes with:

```
unison2: can't hashComponents if bindings have free variables:
  [".","List.join","List.map"]
  ["List.diagonal"]
CallStack (from HasCallStack):
  error, called at src/Unison/ABT.hs:596:11 in unison-parser-typechecker-0.1-GCbDdvuyVnaIzD02H3kxIu:Unison.ABT
```

**Comment by aryairani** [comment]
Oh wow.

**Comment by pchiusano** [comment]
Fixed this! Issue was that:

1. The typechecked file is "filtered" before being added to the codebase. The filtering of a typechecked file drops duplicates and other things that aren't being added to the codebase for whatever reason.
2. But hashing of terms was being done _AFTER_ filtering, so the hashing was being given a file that wasn't self contained for purposes of computing a hash.
3. The fix I implementetd: term hashes are now part of `TypecheckedUnisonFile`, computed at construction - so now `hashTerms` is just a field rather than a function, something we've considered previously. The lowercase `typecheckedUnisonFile` has the same signature as the old constructor and the `hashTerms` has the same signature as before so it was a pretty surgical change.
