### ISSUE TITLE
Forking a branch makes everything appear twice.

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#542]
If you say e.g. `fork . Foo`, then from now on every time something like `Foo.bar` shows up in e.g. an `add` or `update` response, it shows up as `Foo.bar, .bar` or `bar, Foo.bar` depending on which branch you're in. If you have a lot of branches, this can get really long really fast.

Maybe it's a little annoying that we can't tell the difference between a branch and a name. Maybe the solution is as simple as picking the one most "proximate" name for something and just displaying one name in this view. Getting all the names for a definition can be a separate operation.

![image](https://user-images.githubusercontent.com/130916/60343893-50fc7a80-9983-11e9-99a3-93174650df27.png)

**Comment by aryairani** [comment]
Yeah.  We might consider encouraging `move . Foo` instead of `fork . Foo` although that move is currently called `rename.path`, (i.e. `rename.path . Foo`) although that fails with some kind of parse error currently.  The original thinking was that you don't really work from the root if you are going to have branches, you work in the individual branches.

Alternatively, we could distinguish between names and branches.  I was starting to lean that way myself.
