### ISSUE TITLE
Typechecking annotated refs always succeeds

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#575]
In `wip/branchless`, there's a regression that causes typechecking of annotated references to always succeed:

Add this to the codebase:
```
x = [1,2,3]
```

Once added, `x` can be annotated with any type:

```
   1 | > (x : Int)
          ⧩
          [1, 2, 3]
```

**Comment by pchiusano** [comment]
Okay, after the 1 line diff in bf9c897 we get:

<img width="819" alt="Screen Shot 2019-07-16 at 4 21 04 PM" src="https://user-images.githubusercontent.com/11074/61326962-e605cd00-a7e5-11e9-945f-0a222cc92f5c.png">

This is with `x = +1` prerviously added to the codebase.

I think an even better message would be that `x` has that type because `x` is an external definition with that type.
