### ISSUE TITLE
Open to Nix?

### ISSUE THREAD

**Issue by wpcarro** [unisonweb/unison#592]
Is Unison open to supporting a Nix build? I'd be open to trying to support it if the team is open to a pull request.

**Comment by aryairani** [comment]
We don't know what's involved, but we're open to it.

**Comment by sfultong** [comment]
I think I talked to @pchiusano like 2-3 years ago about this, and I think I remember him saying he looked into it but it didn't seem like a good idea for whatever reason.

Nix has come a long way since then, though, and the ethos behind it seems to fit with Unison.

I support nix for every project!

One question is how you want to integrate it.

Do you want to...
- have a nix-shell you enter, then use stack as usual?
- integrate with stack and have stack call out to a 'shell-file'?
- have a nix-shell you enter, then use cabal to build?
- use something like https://github.com/nmattia/snack ?

The second option is probably too intrusive, and I'm not sure about the implications for building on windows.

**Comment by tscholak** [comment]
I have started nixifying the repo today. If all goes well, expect a PR tonight.

**Comment by aryairani** [comment]
Per https://github.com/unisonweb/unison/pull/622#issuecomment-541758099, we don't feel we can support nix internally, but would be supportive if someone wanted to maintain a Nix-ified fork!
