### ISSUE TITLE
figure out how to handle `WarnIncomingRootBranch` long term

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#616]
Note that it's currently triggered in normal operation by an `update` or `merge` or `pull` with stuff to propagate.  Maybe we could refactor some of the helpers to support threading an updated branch in memory, instead of having them `sync` or `get` every time?

>I think the spurious branch file arrival message is due to the fact that we calling sync twice in the command, but that IORef with the current branch, which controls the file watch events, is updated on different schedule? Like after each command finishes?

**Comment by pchiusano** [comment]
Also the warning seems to be triggered on every `add`.

**Comment by pchiusano** [comment]
A clue: with default metadata switched off, this doesn't happen for me. With default metadata turned on, it happens every time.

**Comment by pchiusano** [comment]
Think I know what's going on. We are setting the root branch twice in some commands, including `add` when there's default metadata. Here's `HandleInput`, which calls `stepAt` and `addDefaultMetadata`, both of which end up calling `updateRoot`, which issues a `SyncLocalRootBranch` command:

https://github.com/unisonweb/unison/blob/6b34b1ac2fd9326f63ab8a2bbcabf73294ef9f36/parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs#L1387-L1404

https://github.com/unisonweb/unison/blob/6b34b1ac2fd9326f63ab8a2bbcabf73294ef9f36/parser-typechecker/src/Unison/Codebase/Editor/HandleInput.hs#L2227-L2231

Each `SyncLocalRootBranch` triggers a disk write and the logic for ignoring file events for our writes is too fragile. Here's the sequence of events when the spurious warning occurs:

1. Phase 1 of the add command produces branch with hash `h1` and issues a `SyncLocalRootBranch` and sets the "ignore this namespace hash" event to `h1`. This triggers a file system event at some indeterminate point in the future.
2. Phase 2 of the add command issues for the default metadata issues another `SyncLocalRootBranch` and sets the "ignore namespace hash" to `h2`.
3. The file system event from phase 1 is triggered and an `h1` event comes in, after the "ignore namespace hash" has already been set to `h2`.

One fix is a) to not consider it a warning if the hash(es) that arrives is `before` the current hash - it's just a stale event from the file watching API and can be ignored. This would just be a `Branch.before` check instead of a `/=` check here I think:

https://github.com/unisonweb/unison/blob/6b34b1ac2fd9326f63ab8a2bbcabf73294ef9f36/parser-typechecker/src/Unison/CommandLine.hs#L69-L70

Another option is b) to go through all the commands and be careful to make sure that `updateRootBranch` is only called once. Basically anytime it's called twice in rapid succession it can generate this behavior. I'm not sure there's anything necessarily wrong with a command that calls `updateRootBranch` more than once... what if it's a command with two phases? (Like `update` then `propagate`).

I think I like option a).

**Comment by aryairani** [comment]
I hadn't thought too much about it, but I was imagining some kind of `Set` of expected root writes, that could then be ignored or cleaned up, but wasn't sure how hard it would be to make sure it didn't accumulate garbage?

**Comment by runarorama** [comment]
Related: #1554

**Comment by aryairani** [comment]
@runarorama What do you think about tracking a set?

**Comment by pchiusano** [comment]
You want something that also works properly given the user may undo or reset-root. If you just keep a Set then that becomes something you gotta keep consistent with what the current root is. You can think of a causal as a lazy set of hashes where access to more recent hashes is fast, so it can be the single source of truth.

I think the best answer is the trimmed check I suggested - if something super old shows up, that’s fine to trigger the warning. 

There’s no way to distinguish definitively an event triggered by the current running UCM vs one triggered by something external. All the file watch tells us is that a file has been written to the _head directory. We don’t have any way to tell the file system “hey, ignore this particular write”. 😀

**Comment by aryairani** [comment]
> You want something that also works properly given the user may undo or reset-root.

Yes

> If you just keep a Set then that becomes something you gotta keep consistent with what the current root is.

Yes

> You can think of a causal as a lazy set of hashes where access to more recent hashes is fast, 

Okay

> so it can be the single source of truth.

The truth of what?

> I think the best answer is the trimmed check I suggested - if something super old shows up, that’s fine to trigger the warning.

You mean something that searches the history to some pre-determined depth? Okay.

> There’s no way to distinguish definitively an event triggered by the current running UCM vs one triggered by something external.

This seems definitely not true.

> All the file watch tells us is that a file has been written to the _head directory. We don’t have any way to tell the file system “hey, ignore this particular write”. 😀

Right

**Comment by pchiusano** [comment]
Okay, I’ll add the trimmed check to #1553 PR I have open, should be trivial. Since it feels pretty special purpose, I’ll probably move it out of Causal and just put the function right by that use site.
