### ISSUE TITLE
Give `view` command (and `execute`) access to latest typechecked file

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#632]
I get as far as 

```
  ✅
  
  I found and typechecked these definitions in ~/u1/scratch.u. If you do an
  `add` or `update` , here's how your codebase would change:
  
    ⍟ These new definitions are ok to `add`:
    
      square : base.Nat -> base.Nat
  
  Now evaluating any watch expressions (lines starting with `>`)...
  Ctrl+C cancels.

.> 
```

and then I experience a strong urge to see `square` before I add it - does it look like what I intended?  How does it look once it's been through the pretty-printer?  Has unison really parsed it right?

But `view square` doesn't work until I've done `add`, so I feel like I have to commit to the definition before I'm really ready.  

Maybe a live-with, I don't know, I'm not taking a position on whether there should be a design change here, just describing my experience...

**Comment by pchiusano** [comment]
Interesting. I haven’t personally felt this as much but I think it’s easy to give view access to latest typechecked file and maybe a note about that in the message for discoverability. I think it helps build more trust in the tool and with letting go of attachment to the textual source. 😀

Note that for now you can always add, then view, then undo. Not great.

**Comment by pchiusano** [comment]
Also incorporate #417 into this. Should just involve adding latest typechecked file to the `LoopState` in `HandleInput.hs` and making use of this field in `view` and `execute`.

**Comment by aryairani** [comment]
@atacratic Do you still want to be able to `view` within the latest typechecked file, and if so, why?

**Comment by atacratic** [comment]
For me the urge is starting to subside.  I'm sure other people will feel it though, while they're still getting used to the idea of Unison eating their source.  

I'm still not taking a strong position either way as to whether this is better how it is or better to change - up to you obvs!

**Comment by aryairani** [comment]
My current motivation is just to close tickets :)  But we can keep it open (or reopen it) if it's something that needs to happen.

**Comment by anovstrup** [comment]
@aryairani Note that #417 was closed in favor of including `execute` support in this issue — to me, that seems more useful/important than `view`.  Kinda related, I'd like to be able to see how unison _type-checks_ (rather than prints) the definitions in the scratch file even when some definitions fail to type-check or some watch expressions can't be evaluated.

**Comment by aryairani** [comment]
@anovstrup Ah, thanks.

Re. typechecking, agree that would be nice.  Currently it doesn't because they are typechecked together (as they may depend on one another).  I could imagine approximating a topological sort before typechecking, and using it to typecheck in dependency order.  Want to open a feature request issue for it?

**Comment by anovstrup** [comment]
@aryairani I feel like an issue already existed for that, but I haven't been able to find it so I went ahead and created https://github.com/unisonweb/unison/issues/1300. Hopefully not a duplicate.

**Comment by mitchellwrosen** [comment]
We think the parse/print loop has improved enough that being able to `view` before `add` isn't as important as it was.
