### ISSUE TITLE
TDNR hang in this weird example

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#664]
From fresh repo, on current master:

```
.> pull git@github.com:unisonweb/unisonbase.git
```

Then in a scratch file do:

```
use .base
use .test.v1

filter : (a -> Boolean) -> [a] -> [a]
filter f as = foldl step [] as
```

Hangs during typechecking it seems.

Changing that `foldl` to `List.foldl` causes it to not hang.

@runarorama

**Comment by aryairani** [comment]
Still reproducible as of e16c5114.

**Comment by ceedubs** [comment]
As far as I can tell this no longer hangs.

A bit has changed since this was created. When saved the code as written I pretty quickly got an error about not being able to find `foldl`. When I changed it to `foldLeft` I get an error about not being able to find `step`. When I defined `step` I quickly got an error about a lot of different `foldLeft` definitions being in scope. It would be nice for TDNR to recognize that `List.foldLeft` is the right one, but I still think that we can close out this bug about it hanging.
