### ISSUE TITLE
ucm manages to mess up tmux status line (osx in terminal)

### ISSUE THREAD

**Issue by virusdave** [unisonweb/unison#681]
Don't ask me how, but it manages to do so.

Normal window's statusline:
![image](https://user-images.githubusercontent.com/6148271/62665242-92058880-b94c-11e9-8337-71c4453d7ef6.png)

When using `ucm`:
![image](https://user-images.githubusercontent.com/6148271/62665284-af3a5700-b94c-11e9-87fc-53e7e4670f09.png)

This weirdness then starts to plaster across the window as `ucm` prints more text.

![image](https://user-images.githubusercontent.com/6148271/62665347-ec064e00-b94c-11e9-95c9-340d667da394.png)

**Comment by pchiusano** [comment]
I think I know what’s going on, we are using ANSI console setTitle which I didn’t realize messed with tmux. It’s not super important to set the title so I say let’s just not do it.  @virusdave if you wre feeling inspired you can submit PR update OutputMessages.hs to remove all calls to Console.setTitle (just search for it in that file), and see if this does the trick for you.

Otherwise one of core committees will get to it sometime soon.

**Comment by seagreen** [comment]
This looked like an easy first issue: https://github.com/unisonweb/unison/pull/706
