### ISSUE TITLE
Unison accepts my incorrect type signature

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#691]
Unison accepts my program written as:

```haskell
hello : '()
hello _ = base.io.printLine "hello"
```

and infers `hello`'s type to be

```haskell
hello : '{base.io.IO} ()
```

I'd have expected my manually-written type signature to be equivalent to:

```
hello: '{e} ()
```

and thus rejected, as I have not put that the program needs access to IO.

**Comment by atacratic** [comment]
I think this is working as intended. Take a look at https://github.com/unisonweb/unison/blob/master/docs/ability-typechecking.markdown#type-annotations-and-ability-inference, first bullet. Unison is getting to `'{e} ()` like you say, but that's not a universally quantified e; it's a variable it's then inferring based on the abilities you're using in your function.

So if you want to be specific about abilities in your type signature you need to have some {} brackets in it. Otherwise unison will help you out by working out what you meant.

I also hadn't realised til now that ability inference happens sometimes even if you give a type signature! I'll keep this issue open to track working that into the docs.

**Comment by runarorama** [comment]
Yeah, maybe the ability inference is too surprising here.

To assert that `hello` should definitely be pure, you need `hello : '{} ()`.

**Comment by pchiusano** [comment]
You want ability inference / generalization for unadorned arrows, so your functions can become ability polymorphic without any extra work. It’s bad for the library ecosystem when functions are made inconsistently ability polymorphic - generates extra plumbing code and/or confusing type errors.

The tradeoff is it takes some unlearning if you are coming from Haskell: a -> b is not a pure type, it’s a ->{e} b for some to be inferred ability e. If you require purity then you gotta say so explicitly.

That said, maybe there is a case for making ‘a desugar as ‘{} a. Like if you are quoting, we flip the convention and assume purity by default? 

I guess this seems a little weird to me and wonder if we just need better docs or messages. Like alerting the user when ability inference of a concrete ability happens and pointing them to some docs might be good. “You didn’t provide an ability set here so I inferred IO. If you mean for this function to be pure, use ‘{} () as its type annotation. See <link> to learn more.”

**Comment by mitchellwrosen** [comment]
Interesting points, thanks! It's an interesting design space for sure. My instinct is that these defaults are a bit backwards, as I intend to _mostly_ write pure functions, only reaching for effects sparingly, so I am willing to opt into the `{IO}` syntax as necessary. ...But my source code is ephemeral, and when pulled out of the code database, my inferred effects will appear!

**Comment by pchiusano** [comment]
I agree about writing mostly pure functions, but even pure functions can usually be profitably generalized to be ability polymorphic in some way, and that's a major win (Like `List.map` works as `traverse` for free). Being ability polymorphic is another name for being pure, similar to how a function `forall m . Monad m => a -> m b` is isomorphic to `a -> b` (just choose the identity monad).

In Haskell there's a big syntactic overhead to making code effect polymorphic so you usually don't do so unless you anticipate it being useful (and then if you change your mind later, you have some tedious refactoring to do). That instinct is something I'd like to unlearn since it is worse for the ecosystem and just unnecessary in a language with algebraic effects. :)

I still lean towards my idea above of generating a message to the user if ability inference on an arrow produces a _concrete_ ability like `IO`, just so they are in the loop. If ability inference produces a generic ability variable, then that's no problem IMO. Maybe a lighter message in this case could still be good too.

**Comment by mitchellwrosen** [comment]
@pchiusano Absolutely, when I said "pure functions" above, I meant functions like 

```
forall e. a ->{e} b
```
not 
```
a ->{} b
```
They are pure at the definition site, not necessarily the usage. It's very useful to be able to read a type signature and know if it can perform IO. 

...and I misspoke above! I thought that even though Unison accepts my program

```
hello : '()
hello _ = printLine "Hello"
```
with the inferred type
```
hello : '{IO} ()
```
I thought by the time I grabbed my function back out of the code database it would have its effects pretty-printed for me. This isn't the case:
```
> add hello
> edit hello
hello : '()
hello _ = base.io.printLine "Hello"
```
So (at least for the source-code-viewing workflow) this still seems wrong-ish to me. To clarify, my main concern is being able to see, at a glance, which functions are performing IO and which ones aren't.

@pchiusano can you please clarify why type checking works this way? I see that it is explained in the link @atacratic gave:

> Except, what if that function `a ->{e} b` were actually being passed (within the body of map) to some other function that was expecting an `a ->{} b`? We can't just generalize this willy nilly, we actually need to typecheck with the enriched type.

But I'm not sure I totally understand. I see above you suggested that perhaps Unison should throw a helpful warning message when it infers a concrete ability - what would go wrong (ergonomically) if this was instead an error?

Thanks!

**Comment by pchiusano** [comment]
> I thought by the time I grabbed my function back out of the code database it would have its effects pretty-printed for me. This isn't the case:

That looks like a bug. Should definitely show IO there. Could you submit a separate ticket just for that?

You could have inference of a concrete ability be an error, I don’t think there’s any serious problem with that. Tradeoff is you can’t just have Unison infer concrete abilities for you, you have to mention them explicitly everywhere in the signature. It also feels kind of arbitrary to me. Why is that an error, whereas inferring some ability variable is not an error? 

I like the perspective that unadorned arrows is a request for the typechecker to infer. If you don’t want the inference, you can specify ability lists manually.

**Comment by mitchellwrosen** [comment]
Cool... sounds good! I'll close out the issue.

**Comment by atacratic** [comment]
I've raised #717 for the warning that Paul proposed.

@mitchellwrosen:

> when I said "pure functions" above, I meant functions like
>
> forall e. a ->{e} b
>
> not
>
> a ->{} b
>
> They are pure at the definition site, not necessarily the usage. It's very useful to be able to read a type signature and know if it can perform IO.

I think that those two signatures are actually equivalent, because of the `forall e`.  i.e. the first one is also 'pure at the usage site'.  I think you're thinking of `a ->{e} b` with `e` as a type variable waiting to be unified with something.  

Shout if you think I'm wrong - I want to make sure I understand this stuff.
