### ISSUE TITLE
Typechecker or runtime soundness bug in this example

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#693]
Atop current unisonbase:

```Haskell
use .base
use .base.Optional
use .Pair
ability Parse where
  anyToken : Nat
  choose : '{Parse} a -> '{Parse} a -> {Parse} a
runTextParser : List Nat -> Request Parse a -> Optional a
runTextParser xs req =
  case req of
    { Parse.anyToken -> next } ->
      case xs of
        [] -> None
        (x +: xs) ->
          handle runTextParser xs in next x
    { Parse.choose l r -> next } ->
      lResult = handle runTextParser xs in !l
      case lResult of
        None -> handle runTextParser xs in !r
        Some x -> Some x
    { a } -> Some a
many : '{Parse} a -> {Parse} [a]
many p =
  unfold () '(choose '(Some (!p, ())) 'None)
bogusValue : Optional [Nat]
bogusValue =
  handle runTextParser [1,2,3] in many 'Parse.anyToken

> bogusValue
```

This returns `Some (Some (1, ()))`.

Thnaks to @zenhack for finding and minimizing this one.

**Comment by zenhack** [comment]
Trimmed it down some more:

```
use .base
use .base.Optional

ability Parse where
  anyToken : Nat
  choose : '{Parse} a -> {Parse} a

runTextParser : Request Parse a -> Optional a
runTextParser req =
  case req of
    { Parse.anyToken -> _ } -> None
    { Parse.choose l -> _ } -> handle runTextParser in !l
    { a } -> Some a

many : '{Parse} a -> {Parse} [a]
many _ =
  unfold () '(choose 'None)

bogusValue : Optional [Nat]
bogusValue =
  handle runTextParser in many 'Parse.anyToken

> bogusValue
```

bogusValue evaluates to `Some None`, which is still the wrong type.

**Comment by zenhack** [comment]
Just hit this again, using the codebase at https://github.com/zenhack/unison-parsers/tree/77f30b5c39c473942dd29ed1d9cdb6d0bb466313, you can get something similar by doing:

```
cd .parsers.tests
```

and evaluating the watch expression:

```
> parseText "00" '(many anyToken)
```

You get:

```
(.Either.Right .Optional.None, "")
```

Note the `None`, which should be a value of type `[.Char]`.

**Comment by aryairani** [comment]
Trimmed down example is a typechecker bug; runtime is okay:
```
use .base
use .base.Optional

ability Parse where
  anyToken : Nat
  choose : '{Parse} a -> {Parse} a

runTextParser : Request Parse a -> Optional a
runTextParser req =
  case req of
    { Parse.anyToken -> _ } -> None
    { Parse.choose l -> _ } -> handle runTextParser in !l
    { a } -> Some a

many : '{Parse} a -> {Parse} [a]
many _ =
  unfold () '(choose 'None)

bogusValue : Optional [Nat]
bogusValue =
  handle runTextParser in many 'Parse.anyToken

> bogusValue
```

Expanding by hand:
```
handle runTextParser in many 'Parse.anyToken
```
The implementation of `many` throws out the arg `'Parse.anyToken`:
```
handle runTextParser in unfold () '(choose 'None)
```
```
handle runTextParser in
  go f s acc = case f s of
    Optional.None -> acc
    Optional.Some (a, s) ->
      use List :+
      go f s (acc :+ a)
  go '(choose 'None) () []
```
Expand the call to `go`:
```
handle runTextParser in
  go f s acc = case f s of
    Optional.None -> acc
    Optional.Some (a, s) ->
      use List :+
      go f s (acc :+ a)
  case '(choose 'None) () of
    Optional.None -> acc
    Optional.Some (a, s) ->
      use List :+
      go f s (acc :+ a)
```
Expand the call to '(choose 'None)
```
handle runTextParser in
  go f s acc = case f s of
    Optional.None -> acc
    Optional.Some (a, s) ->
      use List :+
      go f s (acc :+ a)
  case choose 'None of
    Optional.None -> acc
    Optional.Some (a, s) ->
      use List :+
      go f s (acc :+ a)
```
The `choose` in runTextParser doesn't call its continuation, so it's replaced with the match body:
```
handle runTextParser in None
```
`None` is pure, and the the pure case of `runTextParser` is `Some a`:
```
Some None
```
But now where exactly is the type error?

**Comment by aryairani** [comment]
Slightly more minimized:
```
use .base
use .base.Optional

ability Parse where
  choose : '{Parse} a -> {Parse} a

runTextParser : Request Parse a -> Optional a
runTextParser req =
  case req of
    { Parse.choose l -> _ } -> handle runTextParser in !l
    { a } -> Some a

bogusValue : Optional [Nat]
bogusValue = handle runTextParser in
  unfold () '(choose 'None)

> bogusValue
```

**Comment by aryairani** [comment]
Guessing this is a different symptom of the same bug:
```
use .base
use .base.Optional

ability X where
  x : a ->{X} a

h : Request X b -> Optional b
h req = case req of
-- incompatible pattern not caught during typechecking
  { X.x ([c]) -> _ } -> handle h in c 
  { d } -> Some d

bogus3 : Optional [Nat]
bogus3 = handle h in [x 5]

> bogus3
```
```
  ✅
  
  I found and typechecked these definitions in ~/unison/u.u. If you do an `add` or `update` ,
  here's how your codebase would change:
  
    ⍟ These new definitions are ok to `add`:
    
      ability X
      bogus3 : Optional [Nat]
      h      : Effect X b -> Optional b
  
  Now evaluating any watch expressions (lines starting with `>`)... Ctrl+C cancels.

  💔💥
  
  I stopped evaluation after encountering an error:
  
    bug: type error in pattern match: tryCase (5, PatternSequenceLiteral [PatternVar])
    CallStack (from HasCallStack):
      error, called at src/Unison/Runtime/Rt1.hs:723:17 in unison-parser-typechecker-0.1-DvRFZqD6CChI4KPo8H7ee2:Unison.Runtime.Rt1
  
  I'm sorry this message doesn't have more detail about the location of the failure. My makers plan
  to fix this in a future release. 😢

.> 
```

**Comment by pchiusano** [comment]
Good work narrowing it down...

This here should not typecheck

```
ability X where
  x : a ->{X} a

h : Request X b -> Optional b
h req = case req of
  { X.x c -> _ } -> handle h in c
  { d } -> Some d
```

`c` here is going to be `exists e . e`, which differs from the `b` it has to return. Seems like just something with pattern checking.

**Comment by pchiusano** [comment]
I suspect the following needs to happen but isn't being done - existential types in a constructor should get introduced as universal type vars during pattern checking. Suspect the reverse is happening, those existential vars are getting introduced as existential types during typing the pattern.

**Comment by anovstrup** [comment]
This is probably the same issue (minimized from [an Abort example](https://unisonlanguage.slack.com/archives/CLUNF0J5S/p1580505103114900)):

```unison
ability X where
  x : a

h : Request X a -> a
h r = case r of
  { x } -> x
  { X.x -> k } -> handle !k with h

bogus4 : '{X} Char
bogus4 _ = X.x

> handle !bogus4 with h
```

Outputs:
```
    13 | > handle !bogus4 with h
           ⧩
           ()
```

**Comment by zenhack** [comment]
Since the notes @pchiusano sent me back in the fall is past the limit on slack history it is sadly gone, but I'll at least dump out what's still in my head: we did a pair debugging session and determined his hypothesis was basically right. IIRC, we developed a fix that broke other stuff, did some whiteboarding and figured out what it *should* do. The solution was a little more sutble than just swapping which quantifier we used in the constructor. We were reasoning from the intuition that a free monad over a functor `f` is roughly:

```haskell
data Free f a where
  Pure :: a -> Free f a
  Bind :: f x -> (x -> Free f a) -> Free f a
```

(I half suspect I'm mis-remembering that definition and it's too late in the evening for me to be able to stare at it and check that it's right, but it's close enough for the explanation).

IIRC, the broken fix we developed did the naive flip from existential to universal, and that fixed the failing test cases in this issue, but broke stuff involving e.g. `State s a`, because, we determined, the behavior on `s` should *not* be changed, only the behavior on `a`.

The intuition for why that is is that `s` is part of the functor `State s`, and in the above definition the functor `f` is universally quantified. But `a` is the argument to the functor, which, in the `Bind` case, corresponds to `x`, which is existentially quantified.

I really wish we'd recorded this six months ago. @pchiusano, I don't suppose you still have what was in that working tree somewhere?

**Comment by pchiusano** [comment]
@zenhack I remember the issue in this case, but this is a good reminder mirror important info to GitHub 😀.

Yeah you are right, the issue is that the typechecker needs to convert type vars of a constructor to either existentials or universals when unwrapping the constructor type. Any type variable not mentioned in the {} of the final arrow of the ability operation is existential - when unwrapping the constructor type those will turn into universals.

**Comment by pchiusano** [comment]
@dolio just adding this to your queue. Don't think it is too involved and I can give you a steer when you are ready to start working on it. 😀

**Comment by dolio** [comment]
I'm looking into this. Unfortunately, the simple solution doesn't work. I wrote a function

```skolemize :: (Var v, Ord loc) => Type v loc -> M v loc (Type v loc)```

analogous to `ungeneralize`, which just uses `Universal` rather than `existential`. However, this is incorrect. To see why, consider:

```
ability X b where
  x : b -> a -> a
```

Unison will store the type of `x` as something like `forall b a. b -> a ->{X b} a`. However, `b` and `a` do not have the same status. `b` is a parameter, and is supposed to be informed by the `X b` we know we are matching on, while `a` is existentially quantified in the `Request` structure, and should be skolemized.

I think it might be possible to figure this out from the constructor types, but it's not stored in a very convenient way.

**Comment by pchiusano** [comment]
@dolio yeah I think any type variable not mentioned in the {} on the final arrow is an existential, and should become a universal/skolem when unraveling the type during pattern match checking
