### ISSUE TITLE
Pretty-printed function does not show ability

### ISSUE THREAD

**Issue by mitchellwrosen** [unisonweb/unison#703]
Steps to reproduce:

1. Define

```
hello : '()
hello _ = .base.io.printLine "Hello"
```

2. Add

```
> add
```

3. Pretty-print

```
> edit hello
```
```
hello : '()
hello _ = .base.io.printLine "Hello"
```

Expected:

```
hello : () ->{.base.io.IO} ()
```

Note: if you write `hello` with the type signature `'{IO} ()` instead, then it pretty-prints correctly.

**Comment by atacratic** [comment]
Note that it does show the correct signature in slurp/add output.  But not in view/edit.

```
.temp> add

  ⍟ I've added these definitions:
  
    hello : '{.base.io.IO} ()

.temp> view
.temp> view hello

  hello : '()
  hello _ = .base.io.printLine "Hello"

```

**Comment by runarorama** [comment]
I think this has to do with the following code:

```
    -- First, typecheck (using annotateLetRecBindings') the bindings with any
    -- user-provided annotations.
    (body, vts) <- annotateLetRecBindings' True
    -- Then, try typechecking again, but ignoring any user-provided annotations.
    -- This will infer whatever type.  If it altogether fails to typecheck here
    -- then, ...(1)
    withoutAnnotations  <-
      resetContextAfter Nothing $ Just <$> annotateLetRecBindings' False
    -- convert from typechecker TypeVar back to regular `v` vars
    let unTypeVar (v, t) = (v, Type.generalizeAndUnTypeVar t)
    case withoutAnnotations of
      Just (_, vts') -> do
        r <- and <$> zipWithM isRedundant (fmap snd vts) (fmap snd vts')
        btw $ TopLevelComponent ((\(v,b) -> (Var.reset v, b,r)) . unTypeVar <$> vts)
      -- ...(1) we'll assume all the user-provided annotations were needed
      Nothing -> btw
        $ TopLevelComponent ((\(v, b) -> (Var.reset v, b, False)) . unTypeVar <$> vts)
```

**Comment by runarorama** [comment]
When saving the term, we check if the type annotation is redundant. In this case, it’s not redundant as it’s different from the inferred type. So we save the annotation with the term, which is the reason the annotation is preserved when you edit or view it. That is, the term is pretty-printed exactly as it was defined by the programmer.

Maybe we need to be more careful about saving type annotations that are going to have inferred abilities though.

**Comment by pchiusano** [comment]
I was curious if the `IO` is there in the type but being stripped from the display or if it isn't even making its way into the type that's stored in the codebase. It looks like it's there in the type:

```
.> add

  ⍟ I've added these definitions:
  
    main : '{builtin.io.IO} ()

.> view main
  main : '()
  main () = builtin.io.putText builtin.io.stdout "Hello world 222!!\n"
```

But if I try to force `main` in a pure definition, it correctly complains:

```
.> 

  The expression in red  needs these abilities: {builtin.io.IO, 𝕖15}, but this location does not have access to any abilities.
  
      6 |   !main
  
```

So this just appears to be some incorrect tweaking of the type before display.

Clarification on the redundancy checking that @runarorama mentioned above: 

* It is more interesting than just a type equality check (see the `isRedundant` impl)
* Even in cases where the user-provided type is not redundant, the provided type is elaborated to have any inferred abilities. It's this elaborated user type that is stored.

**Comment by runarorama** [comment]
The same kind of thing happens with `map`. Are we saying this is incorrect behaviour?

```unison
map : (a -> b) -> [a] -> [b]
map f xs = case xs of 
  x +: xs -> f x +: map f xs
  [] -> []
```

```ucm

  I found and typechecked these definitions in scratch.u. If you
  do an `add` or `update`, here's how your codebase would
  change:
  
    ⍟ These new definitions are ok to `add`:
    
      map : (a ->{𝕖} b) ->{𝕖} [a] ->{𝕖} [b]
   
  Now evaluating any watch expressions (lines starting with
  `>`)... Ctrl+C cancels.

```
```ucm
.> add

  ⍟ I've added these definitions:
  
    map : (a ->{𝕖} b) ->{𝕖} [a] ->{𝕖} [b]

.> view map

  map : (a -> b) -> [a] -> [b]
  map f xs =
    case xs of
      x +: xs ->
        use builtin.List +:
        f x +: map f xs
      [] -> []

.> find map

  1. map : (a ->{𝕖} b) ->{𝕖} [a] ->{𝕖} [b]
  

```

**Comment by pchiusano** [comment]
Yeah, it's incorrect behavior, any universally quantified ability parameter which is used more than once in the signature should be displayed. 

Also interesting that `find` shows the correct signature but `view` does not, I guess they are going through different codepaths.

**Comment by runarorama** [comment]
"the right thing is to just always include the hash of the type signature with the term, regardless of whether that signature can be inferred. the only issue with doing this now is it might lead to doing a lot of spurious updates for terms whose types can still be inferred"

We can do these updates in bulk

**Comment by pchiusano** [comment]
Updating how hashing is done is tracked by https://github.com/unisonweb/unison/issues/2435

I think this issue might just be fixed when #2435 is done, though it's possible it's just some pretty-printing bug..

**Comment by runarorama** [comment]
I've verified that this is not a pretty-printing issue. I think that #2435 also probably won't fix the OP issue.

```
hello : '()
hello _ = .base.io.printLine "Hello"
```

The term here is `Ann .<() -> ()>. .<printLine "Hello">.`. So the type annotation in the binding is literally `() -> ()`. I'm not sure why the type that's stored in the codebase differs from this, but it does (it's the correctly inferred type).

Should this term even typececk? `() -> ()` is not a valid type for this term. Nor is `forall e. () ->{e} ()`. Whatever it's doing just seems incorrect.

**Comment by pchiusano** [comment]
Take a look at this transcript:

```
.> view hello

  hello : '()
  hello _ = printLine "Hello"

.> find hello

  1. hello : '{IO, Exception} ()
``` 

`hello` has the correct type in the codebase - try calling it from another pure function and you'll get a type error. However the term has an unelaborated signature without abilities instantiated. The pretty-printer is using that unelaborated signature when printing, rather than the elaborated signature that exists in the codebase.

The pretty-printer should always use the codebase signature that exists on the definition, and replace any top-level `Ann` that exists on the definition with the codebase signature. I'm not sure why it isn't already doing that, but it should and that will fix the bug.

#2435 will also fix the issue in a roundabout way depending on how it's done, since I'm assuming that will replace the term with a term that includes the elaborated annotation with all abilities instantiated. But I think the pretty-printer should also be fixed to use the codebase signature, since that is the thing the typechecker will be using when typechecking definitions that reference `hello`.

**Comment by pchiusano** [comment]
cc @aryairani

**Comment by pchiusano** [comment]
I re-added pretty-printer since this is in fact a pretty-printer bug! The typechecker is inferring the correct type, and the type of the definition is being tracked correctly in the codebase. The pretty-printer / `view` command is just discarding the codebase type signature in favor of the (unelaborated) `Ann` that exists on the term.

**Comment by runarorama** [comment]
I mean, the pretty-printer isn't even receiving the codebase type for a term it's printing.

**Comment by pchiusano** [comment]
@runarorama yeah, you're right - it's in the code that calls `TermPrinter.prettyBindings` (likely somewhere in `view`/`edit` command handling) that is wrong. So the bug is not literally in the `TermPrinter` module.

There is probably a check somewhere in the caller of `TermPrinter.prettyBindings` that's like "if the term already has an annotation, ignore the codebase signature for the term" when it should actually replace the annotation on the term.

**Comment by ceedubs** [comment]
As far as I can tell this is resolved. If you don't give `hello` an explicit type signature then `{IO, Exception}` is inferred. If you annotate it as `'()` or `'{} ()` then you get a type checker error saying `The expression in red needs the {Exception} ability, but this location does not have access to any abilities.`
