### ISSUE TITLE
ucm test harness

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#722]
- [x] `assert.noTodo`
- [x] `assert.testOk`
- [x] `assert.definitionExists`
- [x] By default, run the transcript on a fresh codebase, and alert the user at the end how they can pull the resulting codebase into their existing codebase
- [x] `ucm mymain.u` for scripting
- [x] test harness which runs all the transcript files under `unison-src/tests/transcripts` and `unison-src/tests/mains`

**Comment by pchiusano** [comment]
Note: decided not to have separate `assert.*` commands. Instead, the transcript runner interprets failing outputs as a transcript failure. What counts as a failing output? Well, I made what seemed like obvious choices, like test failures, parse errors, and typechecking failures are all considered failures, and so on.

But regardless of the default classification, if what is classified as a failure is expected in your transcript, you can tell the transcript runner this on a per-block basis and then the failure won't kill the transcript.

Rationale: no need to write or remember a bunch of separate commands and then have these pollute the transcript. I think it's also nice that the decision about what is considered a failure and how to respond to it is up to the transcript runner, rather than those assert commands needing to have some strategy baked in.
