### ISSUE TITLE
Provide real implementation of `Cryptography` interface

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#79]
We are currently looking for folks with some crypto/security background to help with auditing the implementation produced by @tmciver.

See [`Unison.Cryptography` in shared](https://github.com/unisonweb/unison/blob/topic/node-container/shared/src/Unison/Cryptography.hs). Implementation of this interface should be added to `node`, under `Unison.Runtime.Cryptography`, which should export some sort of function to produce a `Cryptography` (probably given a [Noise](http://noiseprotocol.org/) keypair).

Provide an actual implementation of this, using [`cryptonite`](https://hackage.haskell.org/package/cryptonite) and [`cacophony`](https://hackage.haskell.org/package/cacophony) packages. 

Noise should be used for the `publicKey` type, and for establishing encrypted, forward-secret sessions (the implementation of `pipeInitiator` and `pipeResponder`).

Background reading: http://noiseprotocol.org/ which describes the Noise protocol framework.

Other notes: work in a branch off of topic/node-container

**Comment by pchiusano** [comment]
@tmciver is ON THE CASE!! Tim, feel free to post any updates here.

**Comment by pchiusano** [comment]
I re-added the [help-wanted label](https://github.com/unisonweb/unison/labels/help%20wanted), since I think it would be good to find another set of eyeballs to help audit this code, which is of critical security importance for Unison.

**Comment by tmciver** [comment]
@pchiusano I have a few questions about the [Cryptography data type](https://github.com/unisonweb/unison/blob/94d01e89df6a80622a30305b84c7bc88c5917901/shared/src/Unison/Cryptography.hs#L51).  I suppose this type aims to be generally applicable to many different cryptography implementations.  If so, I further suppose that some of the functions defined by the type will not be applicable to all implementations.  Is that a fair assessment so far?

In the case of using cacophony, my current thinking is that the `pipeInitiator` and `pipeResponder` functions will be the main entry points to using the underlying library.  If this is the case, would I be correct to assume that the `encrypt` and `decrypt` functions (and possibly the `encryptAssymetric` and `decryptAssymentric` functions) would not be applicable here?  And, if so, what would be a reasonable value for these unneeded fields?  I suppose setting them as `undefined` (as I have them now) is not a good solution.

I noticed that for the [`noop`](https://github.com/unisonweb/unison/blob/94d01e89df6a80622a30305b84c7bc88c5917901/shared/src/Unison/Cryptography.hs#L23) implementation you do have implementations for all functions/values.  Perhaps I'm wrong and you expect all the fields to require implementation.

**Comment by pchiusano** [comment]
Hey @tmciver, so the intent is all fields have an implementation, definitely should not be undefined for any of the fields. However, not all the functions will use the same library for the implementation necessarily. Here's some suggestions for implementations:

* `publicKey` is a noise public key, and the function to generate the `Cryptography` will take a full noise key pair.
* `generateSignKey` generates an elliptic curve keypair, for use in ECDSA, for instance using [cryptonite's functions][ECDSA]. I'm a little unclear on how to generate the keypairs for that, but I'm guessing [this module is involved somehow](https://hackage.haskell.org/package/cryptonite-0.19/docs/Crypto-PubKey-ECC-Generate.html)
* `hash` uses any hash function to hash the bytes. I guess I'd go with [Blake2b_512](https://hackage.haskell.org/package/cryptonite-0.19/docs/Crypto-Hash-Algorithms.html#t:Blake2b_512). I'd be curious if Blake2bp_512 is faster (it uses SIMD primitives I believe).
* `sign` and `verify` use the functions of the [ECDSA][] module to sign and verify signatures.
* `randomBytes` uses some cryptographically secure source of random bytes. You can use [these functions](https://hackage.haskell.org/package/cryptonite-0.19/docs/Crypto-Random.html) from cryptonite for that.
* `encryptAsymmetric` and `decryptAsymmetric` should use noise with one of the 'one-way' handshakes. These are handshakes that aren't interactive.
* `encrypt` and `decrypt` should use some symmetric cipher. I guess I'd go with [ChaCha](https://hackage.haskell.org/package/cryptonite-0.19/docs/Crypto-Cipher-ChaCha.html) with 20 rounds unless it is really too slow.
* `pipeInitator` and `pipeResponder` should use noise protocol framework with one of the interactive handshakes that provides mutual authentication and forward secrecy. It's particularly important that the recipient be assured that the sender has knowledge of the corresponding private key for the public key they advertise during handshaking, since the recipient will be using the public key to do authorization checks (i.e, a Unison node allows nodes authenticated with the public key `xyz` to use the `launchMissiles` function). 

In general, I want this interface to be impossible to use incorrectly in a way that compromises security. So any things like adding padding, message authentication, whatever, should be baked into the implementation. Some more specific security questions I have - 

* `encrypt` and `decrypt` - is it a good idea to add some some random padding to the front of the messages before encryption? How about message authentication? Like, what prevents someone from truncating the stream or flipping some of the bits?
* Probably same deal with encrypt/decrypt asymmetric
* What are security issues around signing that we should be aware of?

[ECDSA]: https://hackage.haskell.org/package/cryptonite-0.19/docs/Crypto-PubKey-ECC-ECDSA.html

**Comment by tmciver** [comment]
@pchiusano Wow, thanks for elaborating on those fields; that's very helpful.  I'd like to begin as simply as possible and I'm now thinking that I should start with implementations for `encrypt` and `decrypt` using ChaCha rather than attempting `pipeInitiator` and `pipeResponder` using cacophony.   Sound reasonable?

**Comment by pchiusano** [comment]
Sure!

**Comment by tmciver** [comment]
I just pushed a branch `topic/encryption`: 8c99adb495e166b66cb6447c0465ac50da0aa6f0 containing my work so far.  There's an implementation for the functions `randomBytes`, `encrypt` and `decrypt`.  There's a test that does a round-trip test of the encryption-decryption which seems to work.

The one problem I see with it is that I hard-coded the nonce value needed by ChaCha.  Obviously, this is not a correct way to implement it, but I'm not sure what to do instead (other than add it as a parameter to the `encrypt`/`decrypt` functions).

Also, I was wondering about the type of `decrypt`.  Should the second parameter be `CypherText` rather than `ByteString`?

**Comment by tmciver** [comment]
There's been a lot of discussion about this issue in gitter and during scrum meetings so I thought I'd post an update here about the current status.

An implementation of `encrypt` and `decrypt` were added (starting with commit c90a2ff926171d7a43ae70287ab15d4892905fd2) that used ChaCha Poly 1305 authenticated encryption found in the cacophony library. But this method is being abandoned because the ChaCha scheme, as well as the similar Salsa scheme, uses a nonce that has, at most, 96 bits and it is thought that this is not large enough so support using a random value (a random nonce that can be sent in the clear with the ciphertext is desired so that state does not need to be persisted between messages; otherwise we could use an incrementing nonce).

My current thinking is to use the cryptonite library directly and use its [GCM](https://en.wikipedia.org/wiki/Galois/Counter_Mode) implementation (see https://github.com/haskell-crypto/cryptonite/blob/master/Crypto/Cipher/AES/Primitive.hs#L341 which starts the functions that implement this).  This will allow use to use a random 128 bit IV (initialization vector).  GCM is an industry standard authenticated encryption mode and is also a NIST standard.

**Comment by pchiusano** [comment]
@tmciver using GCM seems reasonable to me

**Comment by proegssilb** [comment]
I noticed this issue has the "help wanted" tag, but aside from needing someone to audit the code when it's ready, you guys seem to have this under control.

Or is there still an issue with selecting an IV?

**Comment by pchiusano** [comment]
@proegssilb yes, I think using GCM with a random IV seems reasonable for the symmetric encrypt/decrypt functions. We might have some other questions about how best to implement other functions in the API, though... @proegssilb are you the crypto expert that this project has been seeking?? If so we will probably pepper you with lots of questions and/or ask you to get your hands dirty implementing stuff. :)

**Comment by proegssilb** [comment]
I'm not an expert (and don't do audits), but I know a thing or two about a thing or two (IE, SMPC and homomorphic encryption, Diffie-Helman Key Exchange, RNGs, and more), and I care enough about Unison to check in on it every now and then.

As long as you don't need to encrypt with one computer and decrypt with another, GCM/Random IV should be fine for scenarios where you don't have a remote code execution flaw or an attacker with physical access to the computer. 

Happy to help if I can. Keep me posted when questions come up.

**Comment by pchiusano** [comment]
Cool. Can you explain your comment "as long as you don't need to encrypt
with one computer and decrypt with another"? As long as both computers
'somehow' have access to the symmetric key, there's no problem, right?

Were you just emphasizing that symmetric crypto is not what you use to
establish an encrypted pipe between two different nodes? (You'd do DH key
exchange and/or use Noise or TLS...)

**Comment by proegssilb** [comment]
Warning: Outsider's Perspective, and I'm being paranoid.

It sounded like there was some cavalier attitude towards protecting the IV, but I think I might have missed some detail while I was skimming. Yes, there's the issue of "don't just use symmetric crypto for a two-way tunnel." There's also "you've got 5 GB of data you encrypt with a plaintext IV and store locally", Separately from either of those is "You've got 5 GB of data you encrypted with a plaintext IV, pass both of those to another computer over an insecure connection, and let the other computer do the decryption." It's that last category that causes me to raise my eyebrows with what I'm reading in this thread.

In the world of Security, people often prefer not to disclose anything they don't have to. Crypto-wise, sending IVs over plaintext isn't immediately fatal as long as your key stays secure. Depending on your attacker and payload size, and how often the same IV is used or how predictable the IV is, maybe Unison should consider a secure tunnel for the IV, or do a decrypt/re-encrypt/send, so that you don't have an IV sent over the network at all. Another factor complicating the "just protect the key" philosophy is how you manage key rotation (if you can do it at all!)

But, all of that depends on how likely it is that the attacker is going to be able to sniff the IV. If you're dealing with a corporation's edge network, or the open internet at all, I'd assume that IV is going to get logged somewhere, possibly by The Wrong People. A plaintext IV just makes the attacker's life easier, because it's one less variable to deal with. It's not THE secret (that's the key), but it's extra information that shouldn't be too hard to protect (depending on the implementation details).
