### ISSUE TITLE
The Unison Data Type Nat includes 0

### ISSUE THREAD

**Issue by PankajShet** [unisonweb/unison#837]
The Data type Nat represents Natural Number. 
But it also includes 0 according to the specification,
In my opinion, as our number system says that, "Natural Numbers starts from 1 and not 0." either the data type needs to be changed to "Whole Number" or  Natural number data type needs to be changed to "not include 0."

**Comment by atacratic** [comment]
Hi @PankajShet :-) 

Including zero in the natural numbers is accepted modern practice in mathematics and computer science ([ref](https://en.wikipedia.org/wiki/Natural_number#Modern_definitions)).  

It is intended that we have a data type for integers starting from zero - using it for example to count the elements in a list.

I think it's important that Unison documentation is clear what it means by the natural numbers, since in common parlance there is less consensus over whether zero is included.  But at the moment we're missing a facility to document a type!  (There will be one soon.)  

Please add a comment if you see some documentation that could be improved here already.  I will close this now, but thanks for raising it, and feel free to discuss further and get involved in the slack, linked from https://www.unisonweb.org/community :smile:

**Comment by pchiusano** [comment]
It's funny that the controversy about whether the natural numbers should include 0 has made its way into a GitHub issue on this project.

@PankajShet if you felt strongly about this one, you might choose to `move.type .builtin.Nat .builtin.WhatetverYouWant` in your local Unison codebase, and you could choose to publish your namespace for other to use. You can assign whatever names you like to these types, without breaking compatibility with code others have written, and the names you see in the documentation are just the starting names for these types.

**Comment by PankajShet** [comment]
Its funny, thats true and I felt the same but I reported it as I believe this particular language has been designed around mathematical background. The datatype "Nat" certainly stroked my mind about the natural numbers and inclusion of 0 with it and hence I reported it. :)

**Comment by runarorama** [comment]
As @atacratic points out, it's very common in modern mathematics to define the natural numbers inductively starting from 0. That is, a "natural number" is defined as either having the form `0` or the form `1+n` where `n` is a natural number.

I personally prefer to use "strictly positive integers" for the set of natural numbers with 0 removed.
