### ISSUE TITLE
Investigate/implement IPFS-based implementation of `BlockStore`

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#87]
See #86 for some context.

[IPFS](https://ipfs.io/) is big project, but the part we are most interested in is the distributed, content-addressed file-system, which could work as a nice backend for `BlockStore`. It would have the advantage that IPFS-backed Unison nodes would all share a common Universe, which eliminates the hash-syncing step of the distributed evaluation protocol. It also has a solution to the hash distribution problem - common hashes are replicated based on demand across the IPFS network, which can minimize bottlenecks and bring the data closer to where it is needed.

Something I was rather concerned about was [this issue](https://github.com/ipfs/go-ipfs/issues/2917), but it looks like the IPFS folks are [on the case](https://github.com/ipfs/go-ipfs/issues/3065).

The goal is to investigate and possibly implement an IPFS-based `BlockStore`. At first glance, IPFS doesn't look like a natural fit for the `Series` concept that `BlockStore` has. Perhaps it could be implemented using [IPNS](https://github.com/ipfs/examples/tree/master/examples/ipns), or perhaps we don't rely on IPFS for that aspect of the implementation.

/cc @jbenet - Juan, not sure if you get this notification, but hello! IPFS seems like a great project. We may be building atop it. Also, looking forward to meeting you at Full Stack Fest this year.

**Comment by jbenet** [comment]
Hey @pchiusano :) fan of unison too, i was excited when it was announced. In short:

- we need to fix the resource limits, but that's purely optimization
- you can use IPNS i think. and aim not 100% sure, but i think you want what we're calling "authenticated streams" (think of a co-recursive merkle-dag, meaning you listen on H and get a stream of objects, all of which have H as a descendant (well, ancestor in merkle-dag terms, since arrows point back in time).
- yeah let's definitely chat at FullStack Fest
- Highly recommend looking into our IPLD work-- i think it may be super relevant to unison. 
- In general, dive into our abstraction pool-- there's lots of good stuff there.
- And, highly recommend to use something like https://github.com/multiformats/multihash ( https://github.com/multiformats/multiformats ) to ensure interop for a long time :)
