### ISSUE TITLE
`ucm` shell should cancel input at `ctrl+c` and quit at `ctrl+d`

### ISSUE THREAD

**Issue by matthewess** [unisonweb/unison#872]
Most shell/repl environments have lead me to assume that the behavior of keyboard commands is as follows:
- `ctrl + c` : cancel current input and begin a new input line
- `ctrl + c` during evaluation : kill current evaluation and begin a new input line
- `ctrl + d` : kill shell/repl (EOF) [works as expected in `ucm` but mentioning here for completeness]

Currently, it seems like `ucm` responds to `ctrl + c` by immediately shutting down, rather than trapping the signal. Ideally, `ucm` would handle signals like other shells, and simply swallow `ctrl + c` / `SIGINT` signals to cancel the current input line.

**Comment by pchiusano** [comment]
Something I've noticed is that Ctrl+C works to cancel evaluation and exit back to `ucm` prompt... once. But then if you cancel another evaluation, it exits `ucm`. (Does anyone else notice this behavior?) My suspicion is that the second Ctrl+C actually shows up in Haskell as a different exception than the first one. 

Possibly relevant:

http://neilmitchell.blogspot.com/2015/05/handling-control-c-in-haskell.html

Note: we are using `Control.Exception.try` to catch all errors that occur during evaluation here:

https://github.com/unisonweb/unison/blob/95c9673e6d7309b4687f8365f9c22452ba09a9e9/parser-typechecker/src/Unison/Runtime/Rt1IO.hs#L473-L475

I would have thought that would reliably catch signal-based async exceptions too, but maybe not.

Would love help from someone in tracking this one down, and then once we figure out how to do this trapping reliably we can do the same inside the main loop, even when not evaluating. Also, I notice that GHCi does this properly so that might be a place we could look at to see what it's doing.

**Comment by matthewess** [comment]
I'm planning on taking a look at this!

**Comment by matthewess** [comment]
@pchiusano Playing around on master, it looks like ctrl+c _consistently_ works to cancel the evaluation of presently-running unison code. For example, with
```
delayed : '{IO} ()
delayed = '(delay 10000000)
```
then ```
.> run delayed
^C
.> run delayed
^C
.> run delayed
^C
.>```
works consistently. As far as I can tell, the only issue is that before a command line has been entered, ctrl+c will kill the whole process rather than cancelling input and returning you to the prompt.

**Comment by matthewess** [comment]
followup work in #1131 and #1132
