### ISSUE TITLE
Operator precedence for `&&` and `||` doesn't work

### ISSUE THREAD

**Issue by noahhaasis** [unisonweb/unison#895]
The `&&` and `||` operators currently don't have precedence over other operators/functions.
So this code
```haskell
> 1 == 3 || 3 == 3
```
results in a parse error.
![Bildschirmfoto 2019-10-26 um 16 09 32](https://user-images.githubusercontent.com/26230013/67620806-0a247180-f80b-11e9-8b96-c996a16a5936.png)

So to work around that you currently have to wrap sub expressions in paretheses.
```haskell
> (1 == 3) || (3 == 3)
```

**Comment by sellout** [comment]
The behavior in 0.5.23 is different
```unison
> 1 == 3 || 3 == 3
```
```
  The arguments to || have to be Boolean , but this one is Nat :
  
      1 | > 1 == 3 || 3 == 3
```
(the `3` after the `||` is colored yellow, to indicate that that is the `Nat` it’s complaining about). It’s being treated as `((1 == 3) || 3) == 3`.

I think this is the expected behavior for the time being. All operators are left-associative with effectively the same precedence.

Not that this issue should be closed, but just to bring it up-to-date. The workaround (`(1 == 3) || (3 == 3)`) remains the same.
