### ISSUE TITLE
Add pretty-printer support for Doc literals

### ISSUE THREAD

**Issue by atacratic** [unisonweb/unison#936]
As of #914 Unison accepts code like
```
use .builtin
docs.List.take = [:

`@List.take n xs` returns the first `n` elements of `xs`. 

## Example:

@[source] List.take.ex1
:]
```

But at the moment, doing a view/edit on it returns
```

  docs.List.take : builtin.Doc
  docs.List.take =
    use builtin.Doc Blob
    use builtin.Link Term
    builtin.Doc.Join
      [ Blob "`",
        builtin.Doc.Link (Term termLink builtin.List.take),
        Blob " n xs` returns the first `n` elements of `xs`. \n\n## Example:\n\n",
        builtin.Doc.Source (Term termLink List.take.ex1),
        Blob "" ]

```

We should add support for the `[: :]` sugar to the pretty-printer, so that Docs are output in code as nicely as they are input.  Otherwise they will be hard to edit.  

I will implement this.  (It might be a small handful of weeks before it's done.)

@pchiusano can you give me an extra steer about how I should go about determining in the pretty-printer whether a term corresponds to a fully evaluated doc?  Am I checking that it's composed solely of calls to Doc's constructors (note to self: cf DataDeclaration.pairCtorRef), `[]`, text literals, and uses of termLink?  Any other function call (even a `$`) means we give up a revert to non-sugared printing, at least at that level of the tree.  Right?

(note to self: maybe pre-annotate the tree with the 'render with sugar' decision, to avoid quadratic behaviour in the no-sugar case - maybe overkill?)

**Comment by pchiusano** [comment]
@atacratic quick idea, if you want to have a go at this (would be hugely appreciated!!) - I'd maybe write a pure function, `isEvaluatedDoc : Term -> Bool` which can have a straightforward implementation using the same smart patterns you see used in `DisplayPatterns`:

```haskell
isEvaluatedDoc d = case d of
  DD.DocJoin docs = all isEvaluatedDoc docs
  _ -> Nothing
```

Note - I think a `Term.Ref` is okay, as that can become a `@[include]`.

Then in your main `TermPrinter` logic, when you see a constructor applied to some stuff and that constructor is a `Doc` constructor, you can check this function. If yes, can jump to function that uses the same smart patterns to do nice pretty printing back to the same syntax.

To avoid doing this redundantly, you could have reader-monad style "am I inside a `Doc`" flag maintained as you move down in the pretty-printer (rather than needing to accumulate anything up the tree).
