### ISSUE TITLE
Few design questions around language

### ISSUE THREAD

**Issue by ashishnegi** [unisonweb/unison#958]
First of all, great work with this project. There are definitely many interesting ideas which i really liked.

I recently watched the [strangeloop talk](https://www.youtube.com/watch?v=gCWtkvDQ2ZI). I have few questions around the language:

1) As part of development, are build obj/dll files are part of the source code repository ? 
I thought this is what Paul meant when he talked about code only building once when developer checks in the code and later other developers don't need to build as generated builds can be cached.

     Does not generated builds in the code repo increase the size of the repo significantly ?
Otherwise, everyone has to build the code. 
     Is it that there is central cache server for the build code corresponding to hashes ?

2) I understand that renaming is faster as that does not need code re build.
However, Paul talked about renaming will not hurt the library consumers.
How will it work when i rename functions `Foo` with `Bar` without causing confusion for app developers ? App developers will think that their is an existing `Foo` function in library but when reading the latest library doc they won't be able to find it, even though code will compile. Right ?

3) About question on dependency dll warning, from the language design point of view, Does the language supporting multiple versions of the same class in the code base ? 
Isn't it worse than current situation where we find and try to solve this problem up front as soon as it comes up ? because now, language defers this problem to later where code base becomes more difficult to maintain. Humans are reading the code as text where they don't know that multiple versions of the same class exist unless they hit the issue much later in their design or coding.

4) Is it considered to move distributed code execution of functions using hashing as a separate library rather than part of the language ?

5) Have you thought about append only code base from the point of creating different namespaces where new code in new namespace inherits code from old namespace + overrides older functions + adds new functions ?

Thanks for reading my questions. Really interested in knowing the language design in more detail.

**Comment by noahhaasis** [comment]
DISCLAIMER: I'm no expert this is just my partial understanding
1. There no build files in the directory but there is a .unison directory which contains mappings from names to hashes and hashes to serialized AST's. So yes the repo size increases as you add code but you don't have text files with code anymore so the repo size increases similar to any conventional programming language. [Here's](https://github.com/unisonweb/unison/blob/5e3037b8f1338eaa754b1aced73102f6944bec96/docs/repoformats/v1-DRAFT.markdown) a draft on the .unison directory structure.
2. If you just rename a function the hash stays the same. And docs refer to hashes just like everything else in unison does. So if you rename something the docs stay the same but they are rendered with the new name. [Here's](https://github.com/unisonweb/unison/blob/ab0d49aa004b0d3df0a3b285d269aa8df78e8507/unison-src/transcripts/docs.md) a description of the doc API.
3. I don't now if if fully understand your question. As I understand it the problem you describe is that there're different pieces of code which have the same name? Do you mean typeclasses like in haskell? There're never different pieces of code with the same name in Unison because code is addressed by it's hash. You can associate a name with a hash and there may be different mappings for that name in different namespaces but since the hash is unique it's easy to see which implementation you use. (and find it's documentation)
4. The [distributed programming API](https://github.com/unisonweb/unison/blob/a87e7ff6c921e4fb6f0296ea5adbb44af21b5d37/docs/distributed-api-discussion-v1.md) is still in progress. Because of algebraic effects a computation does only know a API. It is up to the caller to provide a implementation. So if you don't like the built-in implementation you can write your own and you don't have to change the code using it.
5. In unison there is this concept of a `Release` which is a function `Namespace -> Namespace`. So you can take the old namespace and add definitions to it. You can't really override old functions because the new functions have different hashes but you can replace all references to the old function with the new function (if it is type preserving).

**Comment by aryairani** [comment]
Hi all, good questions and good answers.

1. Just to clarify, we have (a) text/source code, which are typically thrown away once they are typechecked and added to the codebase, (b) serialized ASTs, which comprise the codebase, and (c) eventually, machine code.  The current implementation of Unison only deals with (a) and (b). Like @noahhaasis said, the repo size increases as you add ASTs, just like a conventional repo's size increases as you add source code to it.  Note that git repos already contain every past revision of ever source file, so this isn't much different.  As far as compiled machine code goes, we may JIT-compile, and/or we may cache signed machine code somewhere TBD.

2. If a library maintainer renames a function function in today's conventional text-based libraries, the developers who are the library's users may be confused, as you said, when writing new code, and their existing code will also no longer build.  If a Unison library maintainer renames a function, ucm will show an automatically-generated summary of changes (including API renames).  And while the library's users may still be confused in spite of the notice, but at least their existing code will still run unchanged.

3. The codebase may include multiple versions of functions (Unison doesn't have classes in the C++/Java sense of the word), but the developers are only exposed to the specific versions they intend to be exposed to for new development.  Tooling (like ucm) will guide developers through updating to directly use the latest version of a library if they want to, rather than continuing to run on older versions, though "continuing to run on older versions" may be the common case, since a lot of code will run fine forever without maintenance, as long as there isn't an endless string of sweeping architectural changes happening in its dependencies.

4. The distributed execution API will be a library, but we feel that the fundamental assumptions needed to enable a simple implementation (i.e. distinct definitions have distinct identifiers, code and computations are first-class, serializable values) are better baked into the language.

5. Yes, a Unison codebase is an append-only codebase.  You `fork` a namespace (including all its functions) as an _O(1)_ operation, and replace/override/add functions from there.

**Comment by v217** [comment]
So unison would just work fine, if I recursively change the file attributes of all files in `~/.unison` to append-only, e.g.: `sudo chattr -R +a  ~/.unison`? Thanks.

**Comment by aryairani** [comment]
Not certain what effect that would have, but it might!

**Comment by ashishnegi** [comment]
>Just to clarify, we have (a) text/source code, which are typically thrown away once they are typechecked and added to the codebase

@aryairani  Do you have a sample small app code base in unison language ? Does text editor parse the .unison directories for showing the code base ?

**Comment by aryairani** [comment]
@ashishnegi The Unison codebase manager (`ucm`) parses the .unison directories for showing the codebase.  You can use the `edit` command to copy selected definitions into your text editor for modification.

**Comment by aryairani** [comment]
I'm going to close this ticket for now, but feel free to reopen it or join us [on Slack](unison-lang.org/slack) if you have more questions!
