### ISSUE TITLE
Update `Rt1IO` to support historical hashes for `IO`

### ISSUE THREAD

**Issue by runarorama** [unisonweb/unison#964]
We have updated `IOSource`, but we need to support both the old hash and the new hash in `RT1IO`.

We should write up a protocol to help us remember what all steps need to happen when IOSource.hs is updated.

It’s gonna:
• imply a new hash, which gets added to new .builtin (I still think there’s a case for overwriting .builtin on startup, or having it be a magic read-only overlay
• possibly add to a .builtin.patch
• apply the patch to unisonweb/base
• update or append to the list of hashes that Rt1IO / execute (/ etc?) recognize as IO (edited)

**Comment by aryairani** [comment]
@runarorama We reverted the push to `base` until this is merged.   Question, I guess the comment above is just the excerpt from slack; we haven't actually updated `IOSource` yet, but we need to do that, right?

We need a way to dump the updated `io` source back from unison to `IOSource.hs`, so that `.builtin.io` is also up-to-date, I think?  Or is there a way we can stop relying on `IOSource.hs` altogether?

**Comment by runarorama** [comment]
Wontfix. See #981
